/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.vendas.view;

import java.awt.Image;
import java.awt.Toolkit;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import projeto.vendas.control.Conexao;
import projeto.vendas.control.DaoPFisica;
import projeto.vendas.control.DaoPJuridica;
import projeto.vendas.control.DaoVendedor;
import projeto.vendas.model.Login;
import projeto.vendas.model.PessoaFisica;
import projeto.vendas.model.PessoaJuridica;
import projeto.vendas.model.Vendedor;

/**
 *
 * @author Cleiton
 */
public class GuiAlterar_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form GuiAlterar_Cliente
     */
    public GuiAlterar_Cliente(Login login) {
        initComponents();
        this.login = login;
        GuiAlterar_Cliente.this.setTitle("Alterar CLientes         " + "Usuário:  " + login.getNome()+
                "         " +"Codigo:  " + login.getCodigo());
        
        URL caminhoIcone = getClass().getResource("/projeto/vendas/model/icones/logotipo.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Alterar = new javax.swing.JTabbedPane();
        Painel_Pessoa_Fisica = new javax.swing.JPanel();
        Painel_Contato_Pessoa_Fisica = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNomePF = new javax.swing.JTextField();
        lblRG = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmailPF = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblVendedor_Responsável = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        ftxtCelularPF = new javax.swing.JFormattedTextField();
        lblData_Nascimento = new javax.swing.JLabel();
        ftxtData_NascPF = new javax.swing.JFormattedTextField();
        ftxtTelefonePF = new javax.swing.JFormattedTextField();
        ftxtCPFPF = new javax.swing.JFormattedTextField();
        ftxtRGPF = new javax.swing.JFormattedTextField();
        cbxVendedorRespPF = new javax.swing.JComboBox<>();
        lblCPF_Cliente = new javax.swing.JLabel();
        Painel_Endereço = new javax.swing.JPanel();
        lblCidade = new javax.swing.JLabel();
        txtCidadePF = new javax.swing.JTextField();
        lblRua = new javax.swing.JLabel();
        txtRuaPF = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairroPF = new javax.swing.JTextField();
        lblUF = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        txtNumeroPF = new javax.swing.JTextField();
        lblCEP = new javax.swing.JLabel();
        ftxtCEPPF = new javax.swing.JFormattedTextField();
        txtComplementoPF = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        cbx_UFPF = new javax.swing.JComboBox<>();
        btnLimparPFisica = new javax.swing.JButton();
        btnAlterarPFisica = new javax.swing.JButton();
        btnConsultarPFisica = new javax.swing.JButton();
        btnDesativarPF = new javax.swing.JButton();
        btnVoltarPFisica = new javax.swing.JButton();
        lblSituacao = new javax.swing.JLabel();
        txtSituacao = new javax.swing.JTextField();
        txtCodigoPFisica = new javax.swing.JTextField();
        lblCodigoPF = new javax.swing.JLabel();
        ftxtConsultarCPF = new javax.swing.JFormattedTextField();
        Painel_Pessoa_Juridica = new javax.swing.JPanel();
        Painel_Cadastro = new javax.swing.JPanel();
        lblNome_Fantasia = new javax.swing.JLabel();
        txtNome_Fantasia = new javax.swing.JTextField();
        lblEmail_PJ = new javax.swing.JLabel();
        txtEmailPJ = new javax.swing.JTextField();
        lblCNPJ = new javax.swing.JLabel();
        ftxtCNPJ = new javax.swing.JFormattedTextField();
        lblVendedor_Responsável_PJ = new javax.swing.JLabel();
        cbxVendedorRespPJ = new javax.swing.JComboBox<>();
        Painel_Endereço_PJ = new javax.swing.JPanel();
        lblCidade_PJ = new javax.swing.JLabel();
        txtCidadePJ = new javax.swing.JTextField();
        lblRua_PJ = new javax.swing.JLabel();
        txtRuaPJ = new javax.swing.JTextField();
        lblBairro_PJ = new javax.swing.JLabel();
        txtBairroPJ = new javax.swing.JTextField();
        lblUF_PJ = new javax.swing.JLabel();
        cbxUF_PJ = new javax.swing.JComboBox<>();
        lblNumero_PJ = new javax.swing.JLabel();
        txtNumeroPJ = new javax.swing.JTextField();
        lblCEP_PJ = new javax.swing.JLabel();
        ftxtCEP_PJ = new javax.swing.JFormattedTextField();
        lblComplemento_PJ = new javax.swing.JLabel();
        txtComplementoPJ = new javax.swing.JTextField();
        lblCNPJ_Cliente_PJ = new javax.swing.JLabel();
        ftxtConsultarCNPJ = new javax.swing.JFormattedTextField();
        btnConsultarPJuridica = new javax.swing.JButton();
        lblSituacao_PJ = new javax.swing.JLabel();
        txtSituacao_PJ = new javax.swing.JTextField();
        btnVoltarPJuridica = new javax.swing.JButton();
        btnLimparPJuridica = new javax.swing.JButton();
        btnAlterarPJuridica = new javax.swing.JButton();
        btnDesativarPJ = new javax.swing.JButton();
        Painel_Contato = new javax.swing.JPanel();
        lblcontato1 = new javax.swing.JLabel();
        txtNome_Contato1 = new javax.swing.JTextField();
        txtAsteristico3 = new javax.swing.JFormattedTextField();
        txtAsteristico7 = new javax.swing.JFormattedTextField();
        lblTelefone1 = new javax.swing.JLabel();
        txtAsteristico8 = new javax.swing.JFormattedTextField();
        ftxtTelefone1 = new javax.swing.JFormattedTextField();
        lblAsteristico11 = new javax.swing.JLabel();
        lblAsteristico14 = new javax.swing.JLabel();
        lblcontato2 = new javax.swing.JLabel();
        lblTelefone2 = new javax.swing.JLabel();
        txtNome_Contato2 = new javax.swing.JTextField();
        ftxtTelefone2 = new javax.swing.JFormattedTextField();
        lblcontato3 = new javax.swing.JLabel();
        txtNome_Contato3 = new javax.swing.JTextField();
        ftxtCelularPJ = new javax.swing.JFormattedTextField();
        lblCelular1 = new javax.swing.JLabel();
        txtCodigoPJ = new javax.swing.JTextField();
        lvlCodigo_PJ = new javax.swing.JLabel();
        lblAlterar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alterar Cliente");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Painel_Contato_Pessoa_Fisica.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        lblNome.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblNome.setText("Nome");

        txtNomePF.setEnabled(false);

        lblRG.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblRG.setText("RG");

        lblEmail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmail.setText("Email");

        txtEmailPF.setEnabled(false);

        lblTelefone.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblTelefone.setText("Telefone");

        lblCPF.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCPF.setText("CPF");

        lblVendedor_Responsável.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblVendedor_Responsável.setText("Vendedor Responsável");

        lblCelular.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCelular.setText("Celular");

        try {
            ftxtCelularPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCelularPF.setText("");
        ftxtCelularPF.setEnabled(false);

        lblData_Nascimento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblData_Nascimento.setText("Data Nascimento");

        try {
            ftxtData_NascPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtData_NascPF.setText("");
        ftxtData_NascPF.setEnabled(false);

        try {
            ftxtTelefonePF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtTelefonePF.setText("");
        ftxtTelefonePF.setEnabled(false);

        try {
            ftxtCPFPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCPFPF.setText("");
        ftxtCPFPF.setEnabled(false);

        try {
            ftxtRGPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtRGPF.setText("");
        ftxtRGPF.setEnabled(false);

        cbxVendedorRespPF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbxVendedorRespPF.setEnabled(false);

        javax.swing.GroupLayout Painel_Contato_Pessoa_FisicaLayout = new javax.swing.GroupLayout(Painel_Contato_Pessoa_Fisica);
        Painel_Contato_Pessoa_Fisica.setLayout(Painel_Contato_Pessoa_FisicaLayout);
        Painel_Contato_Pessoa_FisicaLayout.setHorizontalGroup(
            Painel_Contato_Pessoa_FisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Contato_Pessoa_FisicaLayout.createSequentialGroup()
                .addGroup(Painel_Contato_Pessoa_FisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome)
                    .addComponent(txtNomePF, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Painel_Contato_Pessoa_FisicaLayout.createSequentialGroup()
                        .addGroup(Painel_Contato_Pessoa_FisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelefone)
                            .addGroup(Painel_Contato_Pessoa_FisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ftxtTelefonePF, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ftxtCPFPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(24, 24, 24)
                        .addGroup(Painel_Contato_Pessoa_FisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCelular)
                            .addComponent(ftxtCelularPF, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Painel_Contato_Pessoa_FisicaLayout.createSequentialGroup()
                        .addGroup(Painel_Contato_Pessoa_FisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Painel_Contato_Pessoa_FisicaLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(lblRG, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(81, 81, 81)
                        .addComponent(lblData_Nascimento))
                    .addComponent(lblVendedor_Responsável)
                    .addGroup(Painel_Contato_Pessoa_FisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbxVendedorRespPF, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmailPF, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Painel_Contato_Pessoa_FisicaLayout.createSequentialGroup()
                            .addGap(116, 116, 116)
                            .addComponent(ftxtRGPF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)
                            .addComponent(ftxtData_NascPF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        Painel_Contato_Pessoa_FisicaLayout.setVerticalGroup(
            Painel_Contato_Pessoa_FisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Contato_Pessoa_FisicaLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomePF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_Contato_Pessoa_FisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(lblData_Nascimento)
                    .addComponent(lblRG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_Contato_Pessoa_FisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtData_NascPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCPFPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtRGPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(Painel_Contato_Pessoa_FisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(lblCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_Contato_Pessoa_FisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtTelefonePF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCelularPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVendedor_Responsável)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxVendedorRespPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lblCPF_Cliente.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCPF_Cliente.setText("Digite o CPF do cliente");

        Painel_Endereço.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        lblCidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCidade.setText("Cidade");

        txtCidadePF.setEnabled(false);

        lblRua.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblRua.setText("Rua/Avenida/Estrada/Viela");

        txtRuaPF.setEnabled(false);

        lblBairro.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblBairro.setText("Bairro");

        txtBairroPF.setEnabled(false);

        lblUF.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblUF.setText("UF");

        lblNumero.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblNumero.setText("N°");

        txtNumeroPF.setEnabled(false);

        lblCEP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCEP.setText("CEP");

        try {
            ftxtCEPPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCEPPF.setText("");
        ftxtCEPPF.setEnabled(false);

        txtComplementoPF.setEnabled(false);

        lblComplemento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblComplemento.setText("Complemento");

        cbx_UFPF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbx_UFPF.setEnabled(false);

        javax.swing.GroupLayout Painel_EndereçoLayout = new javax.swing.GroupLayout(Painel_Endereço);
        Painel_Endereço.setLayout(Painel_EndereçoLayout);
        Painel_EndereçoLayout.setHorizontalGroup(
            Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                .addComponent(lblComplemento)
                .addGap(0, 319, Short.MAX_VALUE))
            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtComplementoPF)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Painel_EndereçoLayout.createSequentialGroup()
                        .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCidade)
                            .addComponent(txtCidadePF, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCEP)
                            .addComponent(ftxtCEPPF, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblRua, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBairro, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRuaPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(txtBairroPF, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroPF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUF)
                    .addComponent(cbx_UFPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel_EndereçoLayout.setVerticalGroup(
            Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(lblUF)
                    .addComponent(lblCEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidadePF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCEPPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_UFPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRua)
                    .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRuaPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBairro)
                .addGap(0, 0, 0)
                .addComponent(txtBairroPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblComplemento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtComplementoPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        btnLimparPFisica.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnLimparPFisica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Limpar.png"))); // NOI18N
        btnLimparPFisica.setText("Limpar");
        btnLimparPFisica.setEnabled(false);
        btnLimparPFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparPFisicaActionPerformed(evt);
            }
        });

        btnAlterarPFisica.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnAlterarPFisica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Alterar.png"))); // NOI18N
        btnAlterarPFisica.setText("Alterar");
        btnAlterarPFisica.setEnabled(false);
        btnAlterarPFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPFisicaActionPerformed(evt);
            }
        });

        btnConsultarPFisica.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnConsultarPFisica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Consultar.png"))); // NOI18N
        btnConsultarPFisica.setText("Consultar");
        btnConsultarPFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPFisicaActionPerformed(evt);
            }
        });

        btnDesativarPF.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnDesativarPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Desativar.png"))); // NOI18N
        btnDesativarPF.setText("Desativar Cliente");
        btnDesativarPF.setEnabled(false);
        btnDesativarPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesativarPFActionPerformed(evt);
            }
        });

        btnVoltarPFisica.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnVoltarPFisica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Voltar.png"))); // NOI18N
        btnVoltarPFisica.setText("Voltar");
        btnVoltarPFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarPFisicaActionPerformed(evt);
            }
        });

        lblSituacao.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblSituacao.setText("Situação");

        txtSituacao.setEnabled(false);

        txtCodigoPFisica.setEnabled(false);

        lblCodigoPF.setBackground(new java.awt.Color(255, 255, 255));
        lblCodigoPF.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCodigoPF.setText("Codigo");
        lblCodigoPF.setToolTipText("");

        try {
            ftxtConsultarCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout Painel_Pessoa_FisicaLayout = new javax.swing.GroupLayout(Painel_Pessoa_Fisica);
        Painel_Pessoa_Fisica.setLayout(Painel_Pessoa_FisicaLayout);
        Painel_Pessoa_FisicaLayout.setHorizontalGroup(
            Painel_Pessoa_FisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Pessoa_FisicaLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(Painel_Pessoa_FisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_Pessoa_FisicaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblCPF_Cliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxtConsultarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(btnConsultarPFisica))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_Pessoa_FisicaLayout.createSequentialGroup()
                        .addComponent(btnVoltarPFisica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimparPFisica)
                        .addGap(47, 47, 47)))
                .addGap(65, 65, 65)
                .addComponent(lblSituacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCodigoPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoPFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(Painel_Pessoa_FisicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel_Contato_Pessoa_Fisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_Pessoa_FisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Painel_Pessoa_FisicaLayout.createSequentialGroup()
                        .addComponent(btnAlterarPFisica)
                        .addGap(165, 165, 165)
                        .addComponent(btnDesativarPF))
                    .addComponent(Painel_Endereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        Painel_Pessoa_FisicaLayout.setVerticalGroup(
            Painel_Pessoa_FisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Pessoa_FisicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_Pessoa_FisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF_Cliente)
                    .addComponent(lblSituacao)
                    .addComponent(txtSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtConsultarCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigoPF)
                    .addComponent(txtCodigoPFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarPFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Painel_Pessoa_FisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Painel_Contato_Pessoa_Fisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Painel_Endereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(Painel_Pessoa_FisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarPFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparPFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltarPFisica)
                    .addComponent(btnDesativarPF))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Painel_Alterar.addTab("Pessoa Física", Painel_Pessoa_Fisica);

        Painel_Cadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        lblNome_Fantasia.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblNome_Fantasia.setText("Nome Fantasia");

        txtNome_Fantasia.setEnabled(false);

        lblEmail_PJ.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmail_PJ.setText("Email");

        txtEmailPJ.setEnabled(false);

        lblCNPJ.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCNPJ.setText("CNPJ");

        try {
            ftxtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCNPJ.setEnabled(false);

        lblVendedor_Responsável_PJ.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblVendedor_Responsável_PJ.setText("Vendedor Responsável");

        cbxVendedorRespPJ.setEnabled(false);

        javax.swing.GroupLayout Painel_CadastroLayout = new javax.swing.GroupLayout(Painel_Cadastro);
        Painel_Cadastro.setLayout(Painel_CadastroLayout);
        Painel_CadastroLayout.setHorizontalGroup(
            Painel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_CadastroLayout.createSequentialGroup()
                .addGroup(Painel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_CadastroLayout.createSequentialGroup()
                        .addGroup(Painel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail_PJ)
                            .addComponent(lblVendedor_Responsável_PJ)
                            .addGroup(Painel_CadastroLayout.createSequentialGroup()
                                .addGroup(Painel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNome_Fantasia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNome_Fantasia, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(23, 23, 23)
                                .addGroup(Painel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCNPJ)
                                    .addComponent(ftxtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtEmailPJ)
                    .addComponent(cbxVendedorRespPJ, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Painel_CadastroLayout.setVerticalGroup(
            Painel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_CadastroLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(Painel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome_Fantasia)
                    .addComponent(lblCNPJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome_Fantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail_PJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVendedor_Responsável_PJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxVendedorRespPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Painel_Endereço_PJ.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        lblCidade_PJ.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCidade_PJ.setText("Cidade");

        txtCidadePJ.setEnabled(false);

        lblRua_PJ.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblRua_PJ.setText("Rua/Avenida/Estrada/Viela");

        txtRuaPJ.setEnabled(false);

        lblBairro_PJ.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblBairro_PJ.setText("Bairro/Vila/Parque");

        txtBairroPJ.setEnabled(false);

        lblUF_PJ.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblUF_PJ.setText("UF");

        cbxUF_PJ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));
        cbxUF_PJ.setEnabled(false);

        lblNumero_PJ.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblNumero_PJ.setText("N°");

        txtNumeroPJ.setEnabled(false);

        lblCEP_PJ.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCEP_PJ.setText("CEP");

        try {
            ftxtCEP_PJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCEP_PJ.setText("");
        ftxtCEP_PJ.setEnabled(false);

        lblComplemento_PJ.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblComplemento_PJ.setText("Complemento");

        txtComplementoPJ.setEnabled(false);

        javax.swing.GroupLayout Painel_Endereço_PJLayout = new javax.swing.GroupLayout(Painel_Endereço_PJ);
        Painel_Endereço_PJ.setLayout(Painel_Endereço_PJLayout);
        Painel_Endereço_PJLayout.setHorizontalGroup(
            Painel_Endereço_PJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Endereço_PJLayout.createSequentialGroup()
                .addGroup(Painel_Endereço_PJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRua_PJ)
                    .addComponent(lblComplemento_PJ)
                    .addGroup(Painel_Endereço_PJLayout.createSequentialGroup()
                        .addGroup(Painel_Endereço_PJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtComplementoPJ, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBairro_PJ, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRuaPJ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Painel_Endereço_PJLayout.createSequentialGroup()
                                .addGroup(Painel_Endereço_PJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCidade_PJ)
                                    .addComponent(txtCidadePJ, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(Painel_Endereço_PJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCEP_PJ)
                                    .addComponent(ftxtCEP_PJ, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtBairroPJ, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(23, 23, 23)
                        .addGroup(Painel_Endereço_PJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUF_PJ)
                            .addComponent(cbxUF_PJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumero_PJ))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        Painel_Endereço_PJLayout.setVerticalGroup(
            Painel_Endereço_PJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Endereço_PJLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_Endereço_PJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade_PJ)
                    .addComponent(lblUF_PJ)
                    .addComponent(lblCEP_PJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_Endereço_PJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidadePJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxUF_PJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCEP_PJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_Endereço_PJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRua_PJ)
                    .addComponent(lblNumero_PJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_Endereço_PJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRuaPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBairro_PJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBairroPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComplemento_PJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtComplementoPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        lblCNPJ_Cliente_PJ.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCNPJ_Cliente_PJ.setText("Digite o CNPJ do Cliente");

        try {
            ftxtConsultarCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtConsultarCNPJ.setText("");

        btnConsultarPJuridica.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnConsultarPJuridica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Consultar.png"))); // NOI18N
        btnConsultarPJuridica.setText("Consultar");
        btnConsultarPJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPJuridicaActionPerformed(evt);
            }
        });

        lblSituacao_PJ.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblSituacao_PJ.setText("Situação");

        txtSituacao_PJ.setEnabled(false);

        btnVoltarPJuridica.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnVoltarPJuridica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Voltar.png"))); // NOI18N
        btnVoltarPJuridica.setText("Voltar");
        btnVoltarPJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarPJuridicaActionPerformed(evt);
            }
        });

        btnLimparPJuridica.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnLimparPJuridica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Limpar.png"))); // NOI18N
        btnLimparPJuridica.setText("Limpar");
        btnLimparPJuridica.setEnabled(false);
        btnLimparPJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparPJuridicaActionPerformed(evt);
            }
        });

        btnAlterarPJuridica.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnAlterarPJuridica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Alterar.png"))); // NOI18N
        btnAlterarPJuridica.setText("Alterar");
        btnAlterarPJuridica.setEnabled(false);
        btnAlterarPJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPJuridicaActionPerformed(evt);
            }
        });

        btnDesativarPJ.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnDesativarPJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Desativar.png"))); // NOI18N
        btnDesativarPJ.setText("Desativar Cliente");
        btnDesativarPJ.setEnabled(false);
        btnDesativarPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesativarPJActionPerformed(evt);
            }
        });

        Painel_Contato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        lblcontato1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblcontato1.setText("Nome do contato 1");

        txtNome_Contato1.setEnabled(false);

        txtAsteristico3.setEditable(false);
        txtAsteristico3.setBorder(null);

        txtAsteristico7.setEditable(false);
        txtAsteristico7.setBorder(null);

        lblTelefone1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblTelefone1.setText("Telefone 1");

        txtAsteristico8.setEditable(false);
        txtAsteristico8.setBorder(null);

        try {
            ftxtTelefone1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtTelefone1.setText("");
        ftxtTelefone1.setEnabled(false);

        lblAsteristico11.setText("*");

        lblAsteristico14.setText("*");

        lblcontato2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblcontato2.setText("Nome do contato 2");

        lblTelefone2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblTelefone2.setText("Telefone 2");

        txtNome_Contato2.setEnabled(false);

        try {
            ftxtTelefone2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtTelefone2.setEnabled(false);

        lblcontato3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblcontato3.setText("Nome do contato 3");

        txtNome_Contato3.setEnabled(false);

        try {
            ftxtCelularPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCelularPJ.setEnabled(false);

        lblCelular1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCelular1.setText("Celular");

        javax.swing.GroupLayout Painel_ContatoLayout = new javax.swing.GroupLayout(Painel_Contato);
        Painel_Contato.setLayout(Painel_ContatoLayout);
        Painel_ContatoLayout.setHorizontalGroup(
            Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(txtAsteristico8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                .addComponent(ftxtTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAsteristico14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ftxtTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtNome_Contato1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblcontato1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblAsteristico11))
                                    .addComponent(lblTelefone1))
                                .addGap(17, 17, 17)
                                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblcontato2)
                                    .addComponent(txtNome_Contato2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefone2))))
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAsteristico7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAsteristico3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCelular1)
                                    .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblcontato3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNome_Contato3))
                                    .addComponent(ftxtCelularPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel_ContatoLayout.setVerticalGroup(
            Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcontato1)
                    .addComponent(lblcontato2)
                    .addComponent(lblcontato3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome_Contato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico11)
                    .addComponent(txtNome_Contato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome_Contato3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefone1)
                            .addComponent(lblTelefone2)
                            .addComponent(lblCelular1))
                        .addGap(5, 5, 5)
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftxtTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAsteristico14)
                            .addComponent(ftxtTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftxtCelularPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_ContatoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtAsteristico3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addComponent(txtAsteristico8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(txtAsteristico7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtCodigoPJ.setEnabled(false);

        lvlCodigo_PJ.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lvlCodigo_PJ.setText("Código");

        javax.swing.GroupLayout Painel_Pessoa_JuridicaLayout = new javax.swing.GroupLayout(Painel_Pessoa_Juridica);
        Painel_Pessoa_Juridica.setLayout(Painel_Pessoa_JuridicaLayout);
        Painel_Pessoa_JuridicaLayout.setHorizontalGroup(
            Painel_Pessoa_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Pessoa_JuridicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_Pessoa_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_Pessoa_JuridicaLayout.createSequentialGroup()
                        .addComponent(lblCNPJ_Cliente_PJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxtConsultarCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultarPJuridica)
                        .addGap(18, 18, 18)
                        .addComponent(lblSituacao_PJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSituacao_PJ, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lvlCodigo_PJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_Pessoa_JuridicaLayout.createSequentialGroup()
                        .addGroup(Painel_Pessoa_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Painel_Pessoa_JuridicaLayout.createSequentialGroup()
                                .addComponent(btnVoltarPJuridica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLimparPJuridica))
                            .addComponent(Painel_Contato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(Painel_Cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(Painel_Pessoa_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(Painel_Pessoa_JuridicaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Painel_Endereço_PJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Painel_Pessoa_JuridicaLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnAlterarPJuridica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDesativarPJ)))
                        .addGap(278, 278, 278)))
                .addContainerGap())
        );
        Painel_Pessoa_JuridicaLayout.setVerticalGroup(
            Painel_Pessoa_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Pessoa_JuridicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_Pessoa_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCNPJ_Cliente_PJ)
                    .addComponent(ftxtConsultarCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarPJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(lblSituacao_PJ)
                    .addComponent(txtSituacao_PJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lvlCodigo_PJ)
                    .addComponent(txtCodigoPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(Painel_Pessoa_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_Pessoa_JuridicaLayout.createSequentialGroup()
                        .addComponent(Painel_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Painel_Contato, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Painel_Endereço_PJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(Painel_Pessoa_JuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarPJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesativarPJ)
                    .addComponent(btnVoltarPJuridica)
                    .addComponent(btnLimparPJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Painel_Alterar.addTab("Pessoa Jurídica", Painel_Pessoa_Juridica);

        lblAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Imagem Alterar.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Painel_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Painel_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblAlterar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao();
        conexao.setDriver();
        conexao.setConnectionString();
        daoPfisica = new DaoPFisica(conexao.conectar());
        daoPJuridica = new DaoPJuridica(conexao.conectar());

        daoVendedor = new DaoVendedor(conexao.conectar());

        ArrayList<Vendedor> vendedores = daoVendedor.listarVendedores();

        for (int x = 0; x < vendedores.size(); x++) {
            cbxVendedorRespPF.addItem(vendedores.get(x).getNome());
        }
        for (int x = 0; x < vendedores.size(); x++) {
            cbxVendedorRespPJ.addItem(vendedores.get(x).getNome());
        }

    }//GEN-LAST:event_formWindowOpened

    private void btnDesativarPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesativarPJActionPerformed
        if (btnDesativarPJ.getText().equals("Desativar Cliente")) {
            if (JOptionPane.showConfirmDialog(null, "Confirma Desativação?") == 0) {//Sim
                JOptionPane.showMessageDialog(null, "Desativação Efetuada com sucesso!");

                daoPJuridica.desativarOUativar(pessoaJuridica, "I");

                limpaCamposPJ();
            }
        } else {
            if (JOptionPane.showConfirmDialog(null, "Confirma Ativação?") == 0) {//Sim
                JOptionPane.showMessageDialog(null, "Ativação Efetuada com sucesso!");
                daoPJuridica.desativarOUativar(pessoaJuridica, "A");
                limpaCamposPJ();
            }

        }
    }//GEN-LAST:event_btnDesativarPJActionPerformed

    private void btnAlterarPJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPJuridicaActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0) {//Sim
            JOptionPane.showMessageDialog(null, "Alteração Efetuada com sucesso!");
            pessoaJuridica.setEmail(txtEmailPJ.getText());
            pessoaJuridica.setRua(txtRuaPJ.getText());
            pessoaJuridica.setNumero(txtNumeroPJ.getText());
            pessoaJuridica.setBairro(txtBairroPJ.getText());
            pessoaJuridica.setCidade(txtCidadePJ.getText());
            pessoaJuridica.setUf((String) cbxUF_PJ.getSelectedItem());
            pessoaJuridica.setCep(ftxtCEP_PJ.getText().replace("-", ""));
            pessoaJuridica.setComplemento(txtComplementoPJ.getText());
            pessoaJuridica.setContato1(txtNome_Contato1.getText());
            pessoaJuridica.setTel1(ftxtTelefone1.getText().replace("(", "").replace(")", "").replace("-", ""));
            pessoaJuridica.setContato2(txtNome_Contato2.getText());
            pessoaJuridica.setTel2(ftxtTelefone2.getText().replace("(", "").replace(")", "").replace("-", ""));
            pessoaJuridica.setContato3(txtNome_Contato3.getText());
            pessoaJuridica.setTel3(ftxtCelularPJ.getText().replace("(", "").replace(")", "").replace("-", ""));

            pessoaJuridica.setVendedor_responsavel((String) (cbxVendedorRespPJ.getSelectedItem()));

            daoVendedor = new DaoVendedor(conexao.conectar());

            ArrayList<Vendedor> vendedores = daoVendedor.listarVendedores();

            pessoaJuridica.setCod_vend_resp(vendedores.get(cbxVendedorRespPJ.getSelectedIndex()).getCodigo());

            daoPJuridica.alterar(pessoaJuridica);

            limpaCamposPJ();

            btnAlterarPJuridica.setEnabled(false);
            btnDesativarPJ.setEnabled(false);
            btnLimparPJuridica.setEnabled(false);
        }
    }//GEN-LAST:event_btnAlterarPJuridicaActionPerformed

    private void btnLimparPJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparPJuridicaActionPerformed
        limpaCamposPJ();
    }//GEN-LAST:event_btnLimparPJuridicaActionPerformed

    private void btnVoltarPJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarPJuridicaActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarPJuridicaActionPerformed

    private void btnConsultarPJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPJuridicaActionPerformed
        if (ftxtConsultarCNPJ.getText().replace(".", "").replace("-", "").replace(" ", "").
            replace("/", "").equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o CNPJ do Cliente desejado!");
            txtCodigoPJ.requestFocus();
            txtCodigoPJ.setText("");
        } else {
            daoVendedor = new DaoVendedor(conexao.conectar());

            ArrayList<Vendedor> vendedores = daoVendedor.listarVendedores();

            pessoaJuridica = null;
            pessoaJuridica = daoPJuridica.consultaCNPJ(ftxtConsultarCNPJ.getText().replace("-", "").replace(".", "").replace(" ", "").replace("/", ""));

            if (pessoaJuridica == null) {
                JOptionPane.showMessageDialog(null, "CNPJ não consta no Sistema!");
                txtCodigoPJ.requestFocus();
            } else {
                txtCodigoPJ.setText(pessoaJuridica.getCodigo());
                txtNome_Fantasia.setText(pessoaJuridica.getNome());
                ftxtTelefone1.setText(pessoaJuridica.getTel1());
                ftxtTelefone2.setText(pessoaJuridica.getTel2());
                ftxtCelularPJ.setText(pessoaJuridica.getTel3());

                txtNome_Contato1.setText(pessoaJuridica.getContato1());
                txtNome_Contato2.setText(pessoaJuridica.getContato2());
                txtNome_Contato3.setText(pessoaJuridica.getContato3());

                txtEmailPJ.setText(pessoaJuridica.getEmail());
                ftxtCNPJ.setText(pessoaJuridica.getCnpj());

                txtCidadePJ.setText(pessoaJuridica.getCidade());
                cbxUF_PJ.setSelectedItem(pessoaJuridica.getUf());
                txtRuaPJ.setText(pessoaJuridica.getRua());
                txtNumeroPJ.setText(pessoaJuridica.getNumero());
                ftxtCEP_PJ.setText(pessoaJuridica.getCep());
                txtBairroPJ.setText(pessoaJuridica.getBairro());
                txtComplementoPJ.setText(pessoaJuridica.getComplemento());
                if (pessoaJuridica.getAtivo().equals("A")) {
                    txtSituacao_PJ.setText("Ativo");
                    btnDesativarPJ.setText("Desativar Cliente");
                } else {
                    txtSituacao_PJ.setText("Inativo");
                    btnDesativarPJ.setText("Ativar Cliente");
                }

                cbxVendedorRespPJ.setSelectedItem(pessoaJuridica.getVendedor_responsavel());

                txtBairroPJ.setEnabled(true);
                txtRuaPJ.setEnabled(true);
                txtCidadePJ.setEnabled(true);
                txtComplementoPJ.setEnabled(true);
                txtNumeroPJ.setEnabled(true);
                ftxtCEP_PJ.setEnabled(true);
                cbxUF_PJ.setEnabled(true);
                txtEmailPJ.setEnabled(true);
                ftxtTelefone1.setEnabled(true);
                ftxtTelefone2.setEnabled(true);
                ftxtCelularPJ.setEnabled(true);
                cbxVendedorRespPJ.setEnabled(true);

                btnAlterarPJuridica.setEnabled(true);
                btnDesativarPJ.setEnabled(true);
                btnLimparPJuridica.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnConsultarPJuridicaActionPerformed

    private void btnVoltarPFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarPFisicaActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarPFisicaActionPerformed

    private void btnDesativarPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesativarPFActionPerformed
        if (btnDesativarPF.getText().equals("Desativar Cliente")) {
            if (JOptionPane.showConfirmDialog(null, "Confirma Desativação?") == 0) {//Sim
                JOptionPane.showMessageDialog(null, "Desativação Efetuada com sucesso!");

                daoPfisica.desativarOUativar(pessoaFisica, "I");

                limpaCamposPF();
            }
        } else {
            if (JOptionPane.showConfirmDialog(null, "Confirma Ativação?") == 0) {//Sim
                JOptionPane.showMessageDialog(null, "Ativação Efetuada com sucesso!");
                daoPfisica.desativarOUativar(pessoaFisica, "A");
                limpaCamposPF();
            }

        }
    }//GEN-LAST:event_btnDesativarPFActionPerformed

    private void btnConsultarPFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPFisicaActionPerformed
        if (ftxtConsultarCPF.getText().replace(".", "").replace("-", "").replace(" ", "").equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o código do Cliente desejado!");
            txtCodigoPFisica.requestFocus();
            txtCodigoPFisica.setText("");
        } else {
            daoVendedor = new DaoVendedor(conexao.conectar());

            ArrayList<Vendedor> vendedores = daoVendedor.listarVendedores();

            pessoaFisica = null;
            pessoaFisica = daoPfisica.consultarCPF(ftxtConsultarCPF.getText().replace("-", "").replace(".", "").replace(" ", ""));

            if (pessoaFisica == null) {
                JOptionPane.showMessageDialog(null, "CPF não consta no Sistema!");
                txtCodigoPFisica.requestFocus();
            } else {
                txtCodigoPFisica.setText(pessoaFisica.getCodigo());
                txtNomePF.setText(pessoaFisica.getNome());
                ftxtRGPF.setText(pessoaFisica.getRg());
                ftxtTelefonePF.setText(pessoaFisica.getTel());
                txtEmailPF.setText(pessoaFisica.getEmail());
                ftxtCPFPF.setText(pessoaFisica.getCpf());
                ftxtCelularPF.setText(pessoaFisica.getCel());
                ftxtData_NascPF.setText(pessoaFisica.getDtNasc());

                txtCidadePF.setText(pessoaFisica.getCidade());
                cbx_UFPF.setSelectedItem(pessoaFisica.getUf());
                txtRuaPF.setText(pessoaFisica.getRua());
                txtNumeroPF.setText(pessoaFisica.getNumero());
                ftxtCEPPF.setText(pessoaFisica.getCep());
                txtBairroPF.setText(pessoaFisica.getBairro());
                txtComplementoPF.setText(pessoaFisica.getComplemento());
                if (pessoaFisica.getAtivo().equals("A")) {
                    txtSituacao.setText("Ativo");
                    btnDesativarPF.setText("Desativar Cliente");
                } else {
                    txtSituacao.setText("Inativo");
                    btnDesativarPF.setText("Ativar Cliente");
                }

                cbxVendedorRespPF.setSelectedItem(pessoaFisica.getVendedor_responsavel());

                txtBairroPF.setEnabled(true);
                txtRuaPF.setEnabled(true);
                txtCidadePF.setEnabled(true);
                txtComplementoPF.setEnabled(true);
                txtNumeroPF.setEnabled(true);
                ftxtCEPPF.setEnabled(true);
                cbx_UFPF.setEnabled(true);
                txtEmailPF.setEnabled(true);
                ftxtCelularPF.setEnabled(true);
                ftxtTelefonePF.setEnabled(true);
                cbxVendedorRespPF.setEnabled(true);

                btnAlterarPFisica.setEnabled(true);
                btnDesativarPF.setEnabled(true);
                btnLimparPFisica.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnConsultarPFisicaActionPerformed

    private void btnAlterarPFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPFisicaActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirma Alteração?") == 0) {//Sim
            JOptionPane.showMessageDialog(null, "Alteração Efetuada com sucesso!");
            pessoaFisica.setEmail(txtEmailPF.getText());
            pessoaFisica.setTel(ftxtTelefonePF.getText());
            pessoaFisica.setCel(ftxtCelularPF.getText());
            pessoaFisica.setRua(txtRuaPF.getText());
            pessoaFisica.setNumero(txtNumeroPF.getText());
            pessoaFisica.setBairro(txtBairroPF.getText());
            pessoaFisica.setCidade(txtCidadePF.getText());
            pessoaFisica.setUf((String) cbx_UFPF.getSelectedItem());
            pessoaFisica.setCep(ftxtCEPPF.getText().replace("-", ""));
            pessoaFisica.setComplemento(txtComplementoPF.getText());
            pessoaFisica.setVendedor_responsavel((String) (cbxVendedorRespPF.getSelectedItem()));

            daoVendedor = new DaoVendedor(conexao.conectar());

            ArrayList<Vendedor> vendedores = daoVendedor.listarVendedores();

            pessoaFisica.setCod_vend_resp(vendedores.get(cbxVendedorRespPF.getSelectedIndex()).getCodigo());

            daoPfisica.alterar(pessoaFisica);

            txtCodigoPFisica.requestFocus();

            limpaCamposPF();

            btnAlterarPFisica.setEnabled(false);
            btnDesativarPF.setEnabled(false);
            btnLimparPFisica.setEnabled(false);

            txtBairroPF.setEnabled(false);
            txtRuaPF.setEnabled(false);
            txtCidadePF.setEnabled(false);
            txtComplementoPF.setEnabled(false);
            txtNumeroPF.setEnabled(false);
            ftxtCEPPF.setEnabled(false);
            cbx_UFPF.setEnabled(false);
            txtEmailPF.setEnabled(false);
            ftxtCelularPF.setEnabled(false);
            ftxtTelefonePF.setEnabled(false);
            ftxtData_NascPF.setEnabled(false);
            cbxVendedorRespPF.setEnabled(false);
        }
    }//GEN-LAST:event_btnAlterarPFisicaActionPerformed

    private void btnLimparPFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparPFisicaActionPerformed
        limpaCamposPF();
    }//GEN-LAST:event_btnLimparPFisicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiAlterar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiAlterar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiAlterar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiAlterar_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiAlterar_Cliente(login).setVisible(true);
            }
        });
    }

    private Conexao conexao = null;
    private DaoPFisica daoPfisica = null;
    private DaoPJuridica daoPJuridica = null;
    private PessoaFisica pessoaFisica = null;
    private PessoaJuridica pessoaJuridica = null;
    private DaoVendedor daoVendedor = null;
    private Vendedor vendedor = null;
    private static Login login = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Painel_Alterar;
    private javax.swing.JPanel Painel_Cadastro;
    private javax.swing.JPanel Painel_Contato;
    private javax.swing.JPanel Painel_Contato_Pessoa_Fisica;
    private javax.swing.JPanel Painel_Endereço;
    private javax.swing.JPanel Painel_Endereço_PJ;
    private javax.swing.JPanel Painel_Pessoa_Fisica;
    private javax.swing.JPanel Painel_Pessoa_Juridica;
    private javax.swing.JButton btnAlterarPFisica;
    private javax.swing.JButton btnAlterarPJuridica;
    private javax.swing.JButton btnConsultarPFisica;
    private javax.swing.JButton btnConsultarPJuridica;
    private javax.swing.JButton btnDesativarPF;
    private javax.swing.JButton btnDesativarPJ;
    private javax.swing.JButton btnLimparPFisica;
    private javax.swing.JButton btnLimparPJuridica;
    private javax.swing.JButton btnVoltarPFisica;
    private javax.swing.JButton btnVoltarPJuridica;
    private javax.swing.JComboBox<String> cbxUF_PJ;
    private javax.swing.JComboBox<String> cbxVendedorRespPF;
    private javax.swing.JComboBox<String> cbxVendedorRespPJ;
    private javax.swing.JComboBox<String> cbx_UFPF;
    private javax.swing.JFormattedTextField ftxtCEPPF;
    private javax.swing.JFormattedTextField ftxtCEP_PJ;
    private javax.swing.JFormattedTextField ftxtCNPJ;
    private javax.swing.JFormattedTextField ftxtCPFPF;
    private javax.swing.JFormattedTextField ftxtCelularPF;
    private javax.swing.JFormattedTextField ftxtCelularPJ;
    private javax.swing.JFormattedTextField ftxtConsultarCNPJ;
    private javax.swing.JFormattedTextField ftxtConsultarCPF;
    private javax.swing.JFormattedTextField ftxtData_NascPF;
    private javax.swing.JFormattedTextField ftxtRGPF;
    private javax.swing.JFormattedTextField ftxtTelefone1;
    private javax.swing.JFormattedTextField ftxtTelefone2;
    private javax.swing.JFormattedTextField ftxtTelefonePF;
    private javax.swing.JLabel lblAlterar;
    private javax.swing.JLabel lblAsteristico11;
    private javax.swing.JLabel lblAsteristico14;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblBairro_PJ;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCEP_PJ;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblCNPJ_Cliente_PJ;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPF_Cliente;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCelular1;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCidade_PJ;
    private javax.swing.JLabel lblCodigoPF;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblComplemento_PJ;
    private javax.swing.JLabel lblData_Nascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail_PJ;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome_Fantasia;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblNumero_PJ;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblRua_PJ;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblSituacao_PJ;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTelefone1;
    private javax.swing.JLabel lblTelefone2;
    private javax.swing.JLabel lblUF;
    private javax.swing.JLabel lblUF_PJ;
    private javax.swing.JLabel lblVendedor_Responsável;
    private javax.swing.JLabel lblVendedor_Responsável_PJ;
    private javax.swing.JLabel lblcontato1;
    private javax.swing.JLabel lblcontato2;
    private javax.swing.JLabel lblcontato3;
    private javax.swing.JLabel lvlCodigo_PJ;
    private javax.swing.JFormattedTextField txtAsteristico3;
    private javax.swing.JFormattedTextField txtAsteristico7;
    private javax.swing.JFormattedTextField txtAsteristico8;
    private javax.swing.JTextField txtBairroPF;
    private javax.swing.JTextField txtBairroPJ;
    private javax.swing.JTextField txtCidadePF;
    private javax.swing.JTextField txtCidadePJ;
    private javax.swing.JTextField txtCodigoPFisica;
    private javax.swing.JTextField txtCodigoPJ;
    private javax.swing.JTextField txtComplementoPF;
    private javax.swing.JTextField txtComplementoPJ;
    private javax.swing.JTextField txtEmailPF;
    private javax.swing.JTextField txtEmailPJ;
    private javax.swing.JTextField txtNomePF;
    private javax.swing.JTextField txtNome_Contato1;
    private javax.swing.JTextField txtNome_Contato2;
    private javax.swing.JTextField txtNome_Contato3;
    private javax.swing.JTextField txtNome_Fantasia;
    private javax.swing.JTextField txtNumeroPF;
    private javax.swing.JTextField txtNumeroPJ;
    private javax.swing.JTextField txtRuaPF;
    private javax.swing.JTextField txtRuaPJ;
    private javax.swing.JTextField txtSituacao;
    private javax.swing.JTextField txtSituacao_PJ;
    // End of variables declaration//GEN-END:variables
    private void limpaCamposPF() {
        ftxtConsultarCNPJ.requestFocus();
        ftxtConsultarCNPJ.setText("");

        ftxtRGPF.setText("");
        ftxtCEPPF.setText("");
        ftxtCPFPF.setText("");
        ftxtCelularPF.setText("");
        ftxtData_NascPF.setText("");
        ftxtTelefonePF.setText("");
        txtEmailPF.setText("");

        txtRuaPF.setText("");
        txtNumeroPF.setText("");
        txtBairroPF.setText("");
        txtCidadePF.setText("");
        cbx_UFPF.setSelectedIndex(0);
        cbxVendedorRespPF.setSelectedIndex(0);
        txtComplementoPF.setText("");
        txtSituacao.setText("");

        txtNomePF.setText("");
        txtCodigoPFisica.setText("");

        btnAlterarPFisica.setEnabled(false);
        btnDesativarPF.setEnabled(false);
        btnLimparPFisica.setEnabled(false);

        txtBairroPF.setEnabled(false);
        txtRuaPF.setEnabled(false);
        txtCidadePF.setEnabled(false);
        txtComplementoPF.setEnabled(false);
        txtNumeroPF.setEnabled(false);
        ftxtCEPPF.setEnabled(false);
        cbx_UFPF.setEnabled(false);
        cbxVendedorRespPF.setEnabled(false);
        txtEmailPF.setEnabled(false);
        ftxtCelularPF.setEnabled(false);
        ftxtTelefonePF.setEnabled(false);
        ftxtData_NascPF.setEnabled(false);
        cbxVendedorRespPF.setEnabled(false);
        ftxtConsultarCPF.setText("");

    }

    private void limpaCamposPJ() {
        ftxtConsultarCNPJ.requestFocus();
        ftxtConsultarCNPJ.setText("");

        txtCodigoPJ.setText("");
        ftxtCEP_PJ.setText("");
        ftxtCNPJ.setText("");
        txtEmailPJ.setText("");

        txtRuaPJ.setText("");
        txtNumeroPJ.setText("");
        txtBairroPJ.setText("");
        txtCidadePJ.setText("");
        cbxUF_PJ.setSelectedIndex(0);
        cbxVendedorRespPJ.setSelectedIndex(0);
        txtComplementoPJ.setText("");
        txtSituacao_PJ.setText("");
        txtNome_Fantasia.setText("");

        ftxtTelefone1.setText("");
        ftxtTelefone2.setText("");
        ftxtCelularPJ.setText("");
        txtNome_Contato1.setText("");
        txtNome_Contato3.setText("");
        txtNome_Contato2.setText("");;

        btnAlterarPJuridica.setEnabled(false);
        btnDesativarPJ.setEnabled(false);
        btnLimparPJuridica.setEnabled(false);

        txtBairroPJ.setEnabled(false);
        txtRuaPJ.setEnabled(false);
        txtCidadePJ.setEnabled(false);
        txtComplementoPJ.setEnabled(false);
        txtNumeroPJ.setEnabled(false);
        ftxtCEP_PJ.setEnabled(false);
        cbxUF_PJ.setEnabled(false);
        cbxVendedorRespPJ.setEnabled(false);
        txtEmailPJ.setEnabled(false);
        ftxtTelefone1.setEnabled(false);
        ftxtTelefone2.setEnabled(false);
        ftxtCelularPJ.setEnabled(false);
        cbxVendedorRespPF.setEnabled(false);
    }

}
