/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.vendas.view;

import java.awt.Image;
import java.awt.Toolkit;
import static java.lang.Integer.parseInt;
import java.net.URL;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import projeto.vendas.control.Conexao;
import projeto.vendas.control.DaoGerarPedido;
import projeto.vendas.control.DaoPFisica;
import projeto.vendas.control.DaoPJuridica;
import projeto.vendas.control.DaoVendedor;
import projeto.vendas.model.Login;
import projeto.vendas.model.NotaFiscal;
import projeto.vendas.model.Pedido;
import projeto.vendas.model.PessoaFisica;
import projeto.vendas.model.PessoaJuridica;
import projeto.vendas.model.Vendedor;
import projeto.vendas.tabelas.GuiControleEstrategicoRegiaoEspecifica;

/**
 *
 * @author 0030481521038
 */
public class GuiControle_Estratégico_por_Região_Especifica extends javax.swing.JFrame {

    /**
     * Creates new form GuiControle_Estratégico_por_Região
     */
    public GuiControle_Estratégico_por_Região_Especifica(Login login,
            String UF, String estado, int qtdCli, int qtdPF, int qtdPJ, int qtdVendas, double valorTotal,
            ArrayList<NotaFiscal> ListarNotaFiscal, String dtInicio, String dtFinal, int ativo, int inativo,
            ArrayList<PessoaFisica> ListarPessoasFisicas, ArrayList<PessoaJuridica> ListarPessoasJuridicas) {
        initComponents();
        this.login = login;
        this.UF = UF;
        this.estado = estado;
        this.qtdCli = qtdCli;
        this.qtdPF = qtdPF;
        this.qtdPJ = qtdPJ;
        this.qtdVendas = qtdVendas;
        this.valorTotal = valorTotal;
        this.ListarNotaFiscal = ListarNotaFiscal;
        this.dtInicio = dtInicio;
        this.dtFinal = dtFinal;
        this.ativo = ativo;
        this.inativo = inativo;
        this.ListarPessoasFisicas = ListarPessoasFisicas;
        this.ListarPessoasJuridicas = ListarPessoasJuridicas;

        GuiControle_Estratégico_por_Região_Especifica.this.setTitle("Controle Estratégico "
                + "por Região especifica    " + "Usuário:  " + login.getNome()
                + "         " + "Codigo:  " + login.getCodigo());

        DefaultTableModel modelo = (DefaultTableModel) tblRegiaoEspecifica.getModel();
        tblRegiaoEspecifica.setRowSorter(new TableRowSorter(modelo));

        URL caminhoIcone = getClass().getResource("/projeto/vendas/model/icones/logotipo.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Painel_Mapa = new javax.swing.JPanel();
        lblControle_Estrategico_Regiao = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        lblQtdClientes = new javax.swing.JLabel();
        txtQtdClientes = new javax.swing.JTextField();
        txtQtdClientesPF = new javax.swing.JTextField();
        lblQtdPJ = new javax.swing.JLabel();
        txtQtdClientePJ = new javax.swing.JTextField();
        lblAtivo = new javax.swing.JLabel();
        txtAtivo = new javax.swing.JTextField();
        lblInativo = new javax.swing.JLabel();
        txtInativo = new javax.swing.JTextField();
        Painel_Período_Pesquisa = new javax.swing.JPanel();
        lblData_Inicial = new javax.swing.JLabel();
        lblData_Final = new javax.swing.JLabel();
        ftxtData_Inicial = new javax.swing.JFormattedTextField();
        ftxtData_Final = new javax.swing.JFormattedTextField();
        Painel_Especifico = new javax.swing.JTabbedPane();
        Painel_RegiaoEscolhida = new javax.swing.JPanel();
        jScrollPaneVendedor1 = new javax.swing.JScrollPane();
        tblRegiaoEspecifica = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        lblQtdPF1 = new javax.swing.JLabel();
        lblqtdTotalCompras = new javax.swing.JLabel();
        txtqtdTotalCompras = new javax.swing.JTextField();
        lblInativo2 = new javax.swing.JLabel();
        txtValorCompras = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle Estratégico por Região");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout Painel_MapaLayout = new javax.swing.GroupLayout(Painel_Mapa);
        Painel_Mapa.setLayout(Painel_MapaLayout);
        Painel_MapaLayout.setHorizontalGroup(
            Painel_MapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        Painel_MapaLayout.setVerticalGroup(
            Painel_MapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblControle_Estrategico_Regiao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Controle estrategico por Região.png"))); // NOI18N

        lblEstado.setText("Estado:");

        lblQtdClientes.setText("Quantidade de clientes:");

        lblQtdPJ.setText("Qtd pessoa Juridica:");

        lblAtivo.setText("Clientes Ativos:");

        txtAtivo.setText("0");

        lblInativo.setText("Clientes Inativos:");

        txtInativo.setText("0");

        Painel_Período_Pesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Período da Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        lblData_Inicial.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblData_Inicial.setText("Data Inicial");

        lblData_Final.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblData_Final.setText("Data Final");

        try {
            ftxtData_Inicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtData_Inicial.setText("");
        ftxtData_Inicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtData_InicialActionPerformed(evt);
            }
        });

        try {
            ftxtData_Final.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtData_Final.setText("");
        ftxtData_Final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtData_FinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_Período_PesquisaLayout = new javax.swing.GroupLayout(Painel_Período_Pesquisa);
        Painel_Período_Pesquisa.setLayout(Painel_Período_PesquisaLayout);
        Painel_Período_PesquisaLayout.setHorizontalGroup(
            Painel_Período_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Período_PesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_Período_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ftxtData_Inicial, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(lblData_Inicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Painel_Período_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_Período_PesquisaLayout.createSequentialGroup()
                        .addComponent(lblData_Final)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_Período_PesquisaLayout.createSequentialGroup()
                        .addComponent(ftxtData_Final, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        Painel_Período_PesquisaLayout.setVerticalGroup(
            Painel_Período_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Período_PesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_Período_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData_Inicial)
                    .addComponent(lblData_Final))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_Período_PesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtData_Inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtData_Final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblRegiaoEspecifica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Cidade", "Qtd Compras", "Valor das compras", "Codigo do vendedor responsavel", "Nome do vendedor responsavel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblRegiaoEspecifica.setToolTipText("");
        jScrollPaneVendedor1.setViewportView(tblRegiaoEspecifica);

        javax.swing.GroupLayout Painel_RegiaoEscolhidaLayout = new javax.swing.GroupLayout(Painel_RegiaoEscolhida);
        Painel_RegiaoEscolhida.setLayout(Painel_RegiaoEscolhidaLayout);
        Painel_RegiaoEscolhidaLayout.setHorizontalGroup(
            Painel_RegiaoEscolhidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_RegiaoEscolhidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneVendedor1, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                .addContainerGap())
        );
        Painel_RegiaoEscolhidaLayout.setVerticalGroup(
            Painel_RegiaoEscolhidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_RegiaoEscolhidaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPaneVendedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        Painel_Especifico.addTab("Clientes por cidade", Painel_RegiaoEscolhida);

        btnVoltar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Voltar.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnImprimir.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Consultar.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        lblQtdPF1.setText("Qtd pessoa Fisica:");

        lblqtdTotalCompras.setText("Quantidade de vendas:");

        txtqtdTotalCompras.setText("0");

        lblInativo2.setText("Valor total das vendas");

        txtValorCompras.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblControle_Estrategico_Regiao, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstado)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQtdClientes)
                            .addComponent(txtQtdClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQtdClientePJ, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQtdClientesPF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQtdPF1)
                            .addComponent(lblQtdPJ))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Painel_Especifico, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblAtivo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAtivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblInativo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtInativo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnVoltar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnImprimir)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Painel_Período_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblqtdTotalCompras, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtqtdTotalCompras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblInativo2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValorCompras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(Painel_Mapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Painel_Mapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblControle_Estrategico_Regiao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblQtdClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtdClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQtdPF1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQtdClientesPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQtdPJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQtdClientePJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Painel_Especifico, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblInativo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnVoltar)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Painel_Período_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblAtivo))
                                        .addGap(0, 3, Short.MAX_VALUE)))
                                .addGap(0, 24, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addComponent(txtValorCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblInativo2))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addComponent(txtqtdTotalCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblqtdTotalCompras)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftxtData_InicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtData_InicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtData_InicialActionPerformed

    private void ftxtData_FinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtData_FinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtData_FinalActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        List lista = new ArrayList();
        for (int x = 0; x < tblRegiaoEspecifica.getRowCount(); x++) {

            //gambi
            String a = (String) tblRegiaoEspecifica.getValueAt(x, 4);
            a = a.replace(",", ".");
            double var = Double.parseDouble(a);
            
            GuiControleEstrategicoRegiaoEspecifica print
                    = new GuiControleEstrategicoRegiaoEspecifica();

            print.setCodigo((String) tblRegiaoEspecifica.getValueAt(x, 0));
            print.setNome((String) tblRegiaoEspecifica.getValueAt(x, 1));
            print.setCidade((String) tblRegiaoEspecifica.getValueAt(x, 2));
            print.setQtdCompras((int) tblRegiaoEspecifica.getValueAt(x, 3));
            print.setValorCompras(var);
            print.setCodVendResp((int) tblRegiaoEspecifica.getValueAt(x, 5));
            print.setVendResp((String) tblRegiaoEspecifica.getValueAt(x, 6));

            lista.add(print);
        }

        Map parameters = new HashMap();
        parameters.put("dtinicio", ftxtData_Inicial.getText());
        parameters.put("dtfinal", ftxtData_Final.getText());
        parameters.put("estado", txtEstado.getText());
        parameters.put("a", txtAtivo.getText());
        parameters.put("i", txtInativo.getText());
        parameters.put("qtdPJ", txtQtdClientePJ.getText());
        parameters.put("qtdPF", txtQtdClientesPF.getText());
        parameters.put("qtdCli", txtQtdClientes.getText());
        parameters.put("qtdvendas", txtqtdTotalCompras.getText());
        parameters.put("valorvendas", txtValorCompras.getText());

        JRBeanCollectionDataSource ds = new JRBeanCollectionDataSource(lista);
        try {

            JasperPrint jpPrint;
            jpPrint = JasperFillManager.fillReport("relatorios/EstrategiaPorRegiaoEspecifica.jasper",
                    parameters, ds);

            JasperViewer jv = new JasperViewer(jpPrint, false);
            jv.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(GuiControle_Estratégico_por_Região_Especifica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao();
        conexao.setDriver();
        conexao.setConnectionString();

        daoPFisica = new DaoPFisica(conexao.conectar());
        daoPJrudica = new DaoPJuridica(conexao.conectar());
        daoGerarPedido = new DaoGerarPedido(conexao.conectar());

        txtEstado.setText(estado);
        txtQtdClientePJ.setText(String.valueOf(qtdPJ));
        txtQtdClientesPF.setText(String.valueOf(qtdPF));
        txtQtdClientes.setText(String.valueOf(qtdCli));
        ftxtData_Inicial.setText(dtInicio);
        ftxtData_Final.setText(dtFinal);
        txtAtivo.setText(String.valueOf(ativo));
        txtInativo.setText(String.valueOf(inativo));
        txtqtdTotalCompras.setText(String.valueOf(qtdVendas));

        NumberFormat calculo;
        calculo = NumberFormat.getInstance();
        calculo.setMinimumFractionDigits(2);
        txtValorCompras.setText("R$ " + calculo.format(valorTotal) + " Reais");

        if (flagLimpaTabela1 == 1) {
            modelo.setRowCount(0);
        }
        int diaI = parseInt(ftxtData_Inicial.getText().substring(0, 2));
        int mesI = parseInt(ftxtData_Inicial.getText().substring(3, 5));
        int anoI = parseInt(ftxtData_Inicial.getText().substring(6, 10));
        LocalDate dataInicio = LocalDate.of(anoI, mesI, diaI);

        int diaF = parseInt(ftxtData_Final.getText().substring(0, 2));
        int mesF = parseInt(ftxtData_Final.getText().substring(3, 5));
        int anoF = parseInt(ftxtData_Final.getText().substring(6, 10));
        LocalDate dataFinal = LocalDate.of(anoF, mesF, diaF);

        for (int x = 0; x < ListarNotaFiscal.size(); x++) {
            int dia = parseInt(ListarNotaFiscal.get(x).getDataEmissao().substring(0, 2));
            int mes = parseInt(ListarNotaFiscal.get(x).getDataEmissao().substring(3, 5));
            int ano = parseInt(ListarNotaFiscal.get(x).getDataEmissao().substring(6, 10));
            LocalDate datainicio1 = LocalDate.of(ano, mes, dia);

            // testa se a data é maior que a data inicial da busca
            if (datainicio1.isAfter(dataInicio) || datainicio1.isEqual(dataInicio)) {
                //testa se a data é menor que a data final da busca
                if (datainicio1.isBefore(dataFinal) || datainicio1.isEqual(dataFinal)) {
                    pedido = daoGerarPedido.Consultar(ListarNotaFiscal.get(x).getPedidoCod());

                    //caso a tabela esteja vazia
                    if (!(tblRegiaoEspecifica.getRowCount() > 0)) {
                        if (pedido.getClienteCod().substring(0, 2).equals("PF")) {
                            pessoaFisica = daoPFisica.consultar(pedido.getClienteCod());
                            if (pessoaFisica.getUf().equals(UF)) {
                                Object[] row = {
                                    pessoaFisica.getCodigo(),
                                    pessoaFisica.getNome(),
                                    pessoaFisica.getCidade(),
                                    1,
                                    formatador.format(ListarNotaFiscal.get(x).getTotal()),
                                    pessoaFisica.getCod_vend_resp(),
                                    pessoaFisica.getVendedor_responsavel()};

                                modelo = (DefaultTableModel) tblRegiaoEspecifica.getModel();
                                modelo.addRow(row);
                                flagLimpaTabela1 = 1;
                            }
                        } else {
                            pessoaJuridica = daoPJrudica.consultar(pedido.getClienteCod());
                            if (pessoaJuridica.getUf().equals(UF)) {
                                Object[] row = {
                                    pessoaJuridica.getCodigo(),
                                    pessoaJuridica.getNome(),
                                    pessoaJuridica.getCidade(),
                                    0,
                                    "0,0",
                                    pessoaJuridica.getCod_vend_resp(),
                                    pessoaJuridica.getVendedor_responsavel()};

                                modelo = (DefaultTableModel) tblRegiaoEspecifica.getModel();
                                modelo.addRow(row);
                                flagLimpaTabela1 = 1;
                            }
                        }
                    } //caso a tabela tenha ao menos um registro
                    else {
                        if (pedido.getClienteCod().substring(0, 2).equals("PF")) {
                            pessoaFisica = daoPFisica.consultar(pedido.getClienteCod());
                            if (pessoaFisica.getUf().equals(UF)) {
                                int encontrou = 0;
                                for (int c = 0; c < tblRegiaoEspecifica.getRowCount(); c++) {
                                    if (pessoaFisica.getCodigo().equals((String) tblRegiaoEspecifica.getValueAt(c, 0))) {
                                        tblRegiaoEspecifica.setValueAt((int) tblRegiaoEspecifica.getValueAt(c, 3) + 1, c, 3);

                                        //gambi
                                        String a = (String) tblRegiaoEspecifica.getValueAt(c, 4);
                                        a = a.replace(",", ".");
                                        double b = Double.parseDouble(a);
                                        tblRegiaoEspecifica.setValueAt(formatador.format(b
                                                + ListarNotaFiscal.get(x).getTotal()), c, 4);
                                        encontrou = 1;
                                    }
                                }
                                if (encontrou == 0) {
                                    Object[] row = {
                                        pessoaFisica.getCodigo(),
                                        pessoaFisica.getNome(),
                                        pessoaFisica.getCidade(),
                                        1,
                                        formatador.format(ListarNotaFiscal.get(x).getTotal()),
                                        pessoaFisica.getCod_vend_resp(),
                                        pessoaFisica.getVendedor_responsavel()};

                                    modelo = (DefaultTableModel) tblRegiaoEspecifica.getModel();
                                    modelo.addRow(row);
                                    flagLimpaTabela1 = 1;
                                }
                            }
                        } else {
                            pessoaJuridica = daoPJrudica.consultar(pedido.getClienteCod());
                            if (pessoaJuridica.getUf().equals(UF)) {
                                int encontrou = 0;
                                for (int c = 0; c < tblRegiaoEspecifica.getRowCount(); c++) {
                                    if (pessoaJuridica.getCodigo().equals((String) tblRegiaoEspecifica.getValueAt(c, 0))) {
                                        tblRegiaoEspecifica.setValueAt((int) tblRegiaoEspecifica.getValueAt(c, 3) + 1, c, 3);

                                        //gambi
                                        String a = (String) tblRegiaoEspecifica.getValueAt(c, 4);
                                        a = a.replace(",", ".");
                                        double b = Double.parseDouble(a);
                                        tblRegiaoEspecifica.setValueAt(formatador.format(b
                                                + ListarNotaFiscal.get(x).getTotal()), c, 4);

                                        encontrou = 1;
                                    }
                                }
                                if (encontrou == 0) {
                                    Object[] row = {
                                        pessoaJuridica.getCodigo(),
                                        pessoaJuridica.getNome(),
                                        pessoaJuridica.getCidade(),
                                        1,
                                        formatador.format(ListarNotaFiscal.get(x).getTotal()),
                                        pessoaJuridica.getCod_vend_resp(),
                                        pessoaJuridica.getVendedor_responsavel()};

                                    modelo = (DefaultTableModel) tblRegiaoEspecifica.getModel();
                                    modelo.addRow(row);
                                    flagLimpaTabela1 = 1;
                                }
                            }
                        }
                    }
                }
            }
        }
        //fazer aqui a lista de clientes que nao tem pedidos feitos mais sejam da regiao
        for (int x = 0; x < ListarPessoasFisicas.size(); x++) {
            int b = 0;
            if (ListarPessoasFisicas.get(x).getUf().equals(UF)) {
                for (int a = 0; a < tblRegiaoEspecifica.getRowCount(); a++) {
                    if (ListarPessoasFisicas.get(x).getCodigo().equals((String) tblRegiaoEspecifica.getValueAt(a, 0))) {
                        b = 1;
                    }
                }
                if (b == 0) {
                    Object[] row = {
                        ListarPessoasFisicas.get(x).getCodigo(),
                        ListarPessoasFisicas.get(x).getNome(),
                        ListarPessoasFisicas.get(x).getCidade(),
                        0,
                        "0,0",
                        ListarPessoasFisicas.get(x).getCod_vend_resp(),
                        ListarPessoasFisicas.get(x).getVendedor_responsavel()};

                    modelo = (DefaultTableModel) tblRegiaoEspecifica.getModel();
                    modelo.addRow(row);
                }
            }
        }
        for (int x = 0; x < ListarPessoasJuridicas.size(); x++) {
            int b = 0;
            if (ListarPessoasJuridicas.get(x).getUf().equals(UF)) {
                for (int a = 0; a < tblRegiaoEspecifica.getRowCount(); a++) {
                    if (ListarPessoasJuridicas.get(x).getCodigo().equals((String) tblRegiaoEspecifica.getValueAt(a, 0))) {
                        b = 1;
                    }
                }
                if (b == 0) {
                    Object[] row = {
                        ListarPessoasJuridicas.get(x).getCodigo(),
                        ListarPessoasJuridicas.get(x).getNome(),
                        ListarPessoasJuridicas.get(x).getCidade(),
                        0,
                        "0,0",
                        ListarPessoasJuridicas.get(x).getCod_vend_resp(),
                        ListarPessoasJuridicas.get(x).getVendedor_responsavel()};

                    modelo = (DefaultTableModel) tblRegiaoEspecifica.getModel();
                    modelo.addRow(row);
                }
            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiControle_Estratégico_por_Região_Especifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiControle_Estratégico_por_Região_Especifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiControle_Estratégico_por_Região_Especifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiControle_Estratégico_por_Região_Especifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiControle_Estratégico_por_Região_Especifica(login, UF, estado, qtdCli,
                        qtdPF, qtdPJ, qtdVendas,
                        valorTotal, ListarNotaFiscal, dtInicio, dtFinal, ativo, inativo, ListarPessoasFisicas,
                        ListarPessoasJuridicas).setVisible(true);
            }
        });
    }
    private DecimalFormat formatador = new DecimalFormat("0.00");
    private int flagLimpaTabela1 = 0;
    private DefaultTableModel modelo = null;
    private Conexao conexao;
    private Vendedor vendedor = null;
    private DaoVendedor daoVendedor = null;
    private DaoPFisica daoPFisica = null;
    private DaoPJuridica daoPJrudica = null;
    private PessoaFisica pessoaFisica = null;
    private PessoaJuridica pessoaJuridica = null;
    private static Login login = null;
    private DaoGerarPedido daoGerarPedido = null;
    private Pedido pedido = null;
    private static String UF;
    private static String estado;
    private static int qtdCli;
    private static int qtdPF;
    private static int qtdPJ;
    private static int qtdVendas;
    private static double valorTotal;
    private static String dtInicio;
    private static String dtFinal;
    private static int ativo;
    private static int inativo;
    private static ArrayList<NotaFiscal> ListarNotaFiscal;
    private static ArrayList<PessoaFisica> ListarPessoasFisicas;
    private static ArrayList<PessoaJuridica> ListarPessoasJuridicas;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Painel_Especifico;
    private javax.swing.JPanel Painel_Mapa;
    private javax.swing.JPanel Painel_Período_Pesquisa;
    private javax.swing.JPanel Painel_RegiaoEscolhida;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JFormattedTextField ftxtData_Final;
    private javax.swing.JFormattedTextField ftxtData_Inicial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneVendedor1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAtivo;
    private javax.swing.JLabel lblControle_Estrategico_Regiao;
    private javax.swing.JLabel lblData_Final;
    private javax.swing.JLabel lblData_Inicial;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblInativo;
    private javax.swing.JLabel lblInativo2;
    private javax.swing.JLabel lblQtdClientes;
    private javax.swing.JLabel lblQtdPF1;
    private javax.swing.JLabel lblQtdPJ;
    private javax.swing.JLabel lblqtdTotalCompras;
    private javax.swing.JTable tblRegiaoEspecifica;
    private javax.swing.JTextField txtAtivo;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtInativo;
    private javax.swing.JTextField txtQtdClientePJ;
    private javax.swing.JTextField txtQtdClientes;
    private javax.swing.JTextField txtQtdClientesPF;
    private javax.swing.JTextField txtValorCompras;
    private javax.swing.JTextField txtqtdTotalCompras;
    // End of variables declaration//GEN-END:variables

    public double converte(String arg) throws ParseException {
        //obtem um NumberFormat para o Locale default (BR)
        NumberFormat nf = NumberFormat.getNumberInstance();
        //converte um nÃºmero com vÃ­rgulas ex: 2,56 para double
        double number = nf.parse(arg).doubleValue();
        return number;
    }

}
