/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.vendas.view;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Date;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import projeto.vendas.control.Conexao;
import projeto.vendas.control.DaoGerarPedido;
import projeto.vendas.control.DaoPFisica;
import projeto.vendas.control.DaoPJuridica;
import projeto.vendas.control.DaoProduto;
import projeto.vendas.model.Login;
import projeto.vendas.model.Pedido;
import projeto.vendas.model.PessoaFisica;
import projeto.vendas.model.PessoaJuridica;

/**
 *
 * @author Fernando
 */
public class GuiControle_EstrategicoCliente_Individual extends javax.swing.JFrame {

    /**
     * Creates new form GuiControle_EstrategicoCliente_Individual
     */
    public GuiControle_EstrategicoCliente_Individual(Login login, String codigo) {
        initComponents();
        this.codigo = codigo;
        this.login = login;
        GuiControle_EstrategicoCliente_Individual.this.setTitle("Controle Estratégico Cliente             " + "Usuário:  " + login.getNome()
                + "         " + "Codigo:  " + login.getCodigo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFuncionario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_qtdPedido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_QtdPedidosFaturados = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_FrequenciaCompra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_MediaPedidos = new javax.swing.JTextField();
        lbl_codigo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_nome = new javax.swing.JLabel();
        Btn_mapa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_MaiorCompra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_PercentualFaturados = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_ProdutoFavorito = new javax.swing.JTextField();
        painel = new javax.swing.JPanel();
        lbl_mapa = new javax.swing.JLabel();
        Btn_mapa1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblFuncionario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Alterar Funcionario.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Código: ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText(" Pedidos Realizados");

        txt_qtdPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qtdPedidoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Pedidos Faturados");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Frequência de Compra");

        txt_FrequenciaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FrequenciaCompraActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Produto Favorito");

        lbl_codigo.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lbl_codigo.setText("cdg");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Nome:");

        lbl_nome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_nome.setText("name");

        Btn_mapa.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Btn_mapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Consultar.png"))); // NOI18N
        Btn_mapa.setText("Buscar Localização Gráfica");
        Btn_mapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_mapaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Maior Compra");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("% Pedidos Faturados");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Valor Médio dos Pedidos");

        painel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        lbl_mapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/MapaTeste.png"))); // NOI18N

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lbl_mapa, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_mapa, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Btn_mapa1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Btn_mapa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Voltar.png"))); // NOI18N
        Btn_mapa1.setText("Voltar");
        Btn_mapa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_mapa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_codigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_nome))
                    .addComponent(lblFuncionario))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_mapa1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_mapa)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(txt_qtdPedido)
                            .addComponent(jLabel4)
                            .addComponent(txt_FrequenciaCompra))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txt_MaiorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_QtdPedidosFaturados, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(0, 54, Short.MAX_VALUE))
                                    .addComponent(txt_PercentualFaturados, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_MediaPedidos)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(txt_ProdutoFavorito)))
            .addComponent(painel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_codigo)
                            .addComponent(jLabel7)
                            .addComponent(lbl_nome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFuncionario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_qtdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_QtdPedidosFaturados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_PercentualFaturados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_FrequenciaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MaiorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MediaPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ProdutoFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_mapa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_mapa1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painel.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_mapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_mapaActionPerformed
        String chave = "AIzaSyClq1KlL77y-yFQg9tREoTL3RX5xHZgDN8";

        String endereco = "https://maps.googleapis.com/maps/api/staticmap?center=Brooklyn+Bridge,New+York,NY&zoom=13&size=1200x600&maptype=roadmap&markers=color:blue%7Clabel:S%7C40.702147,-74.015794&markers=color:green%7Clabel:G%7C40.711614,-74.012318&markers=color:red%7Clabel:C%7C40.718217,-73.998284&key=AIzaSyClq1KlL77y-yFQg9tREoTL3RX5xHZgDN8";
        BufferedImage img = null;

        try {
            URL url = new URL(endereco);
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            img = ImageIO.read(con.getInputStream());
        } catch (MalformedURLException ex) {
            Logger.getLogger(GuiControle_EstrategicoCliente_Individual.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GuiControle_EstrategicoCliente_Individual.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (img != null) {
            ImageIcon mapa = new ImageIcon(img);
            lbl_mapa.setIcon(mapa);
        } else {
            lbl_mapa.setText("Sem Mapa");
        }
    }//GEN-LAST:event_Btn_mapaActionPerformed

    private void txt_qtdPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qtdPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_qtdPedidoActionPerformed

    private void txt_FrequenciaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FrequenciaCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FrequenciaCompraActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao();
        conexao.setDriver();
        conexao.setConnectionString();

        daoPF = new DaoPFisica(conexao.conectar());
        daoPJ = new DaoPJuridica(conexao.conectar());
        daoPedido = new DaoGerarPedido(conexao.conectar());
        daoProduto = new DaoProduto(conexao.conectar());
        NumberFormat formatarFloat = new DecimalFormat("0.00");
        ArrayList<Pedido> listaPedido = new ArrayList<Pedido>();
        listaPedido = daoPedido.listarPedidosPorCod(codigo);

        System.out.println(codigo);

        if (codigo.substring(0, 2).contains("PF")) {
            PF = daoPF.consultar(codigo);
            if (listaPedido.size() >= 1) {
                int aprovado = 0, reprovado = 0, pendente = 0, faturado = 0;
                for (int i = 0; i < listaPedido.size(); i++) {

                    switch (listaPedido.get(i).getSituacao()) {
                        case 1:
                            aprovado++;
                            break;
                        case 2:
                            reprovado++;
                            break;
                        case 3:
                            pendente++;
                            break;
                        case 4:
                            faturado++;
                            break;
                    }
                }
                lbl_codigo.setText(codigo);
                lbl_nome.setText(PF.getNome());
                txt_FrequenciaCompra.setText(formatarFloat.format(daoPedido.FrequenciaDeCompras(codigo, formatarDate.format(data), PF.getDtInicio())));
                txt_MaiorCompra.setText(formatarFloat.format(daoPedido.MaiorCompra(codigo)));
                txt_MediaPedidos.setText(formatarFloat.format(daoPedido.MediaCompras(codigo)));
                if (daoPedido.ProdutosMaisComprados(codigo).size() == 0) {

                    txt_ProdutoFavorito.setText("Nenhum");
                } else {
                    txt_ProdutoFavorito.setText(daoProduto.consultar(daoPedido.ProdutosMaisComprados(codigo).get(0).getProdutoCod()).getNome());

                }
                txt_qtdPedido.setText(listaPedido.size() + "");
                txt_QtdPedidosFaturados.setText(faturado + "");
                txt_PercentualFaturados.setText(formatarFloat.format(((faturado + 0.00) / (listaPedido.size() + 0.00)) * 100) + " (%)");
                System.out.println(3.00 / 6.00);
                System.out.println(faturado + " / " + listaPedido.size());

            } else {
                lbl_codigo.setText(codigo);
                lbl_nome.setText(PF.getNome());
                txt_FrequenciaCompra.setText(formatarFloat.format(0));
                txt_MaiorCompra.setText(formatarFloat.format(0));
                txt_MediaPedidos.setText(formatarFloat.format(0));
                txt_ProdutoFavorito.setText("Nenhum");
                txt_qtdPedido.setText("0");
                txt_PercentualFaturados.setText("0.00 (%)");
                txt_QtdPedidosFaturados.setText("0");
            }

        } else {
            PJ = daoPJ.consultar(codigo);
            if (listaPedido.size() >= 1) {
                float aprovado = 0, reprovado = 0, pendente = 0, faturado = 0;
                for (int i = 0; i < listaPedido.size(); i++) {

                    switch (listaPedido.get(i).getSituacao()) {
                        case 1:
                            aprovado++;
                            break;
                        case 2:
                            reprovado++;
                            break;
                        case 3:
                            pendente++;
                            break;
                        case 4:
                            faturado++;
                            break;
                    }
                }
                lbl_codigo.setText(codigo);
                lbl_nome.setText(PJ.getNome());
                txt_FrequenciaCompra.setText(formatarFloat.format(daoPedido.FrequenciaDeCompras(codigo, formatarDate.format(data), PJ.getDtInicio())));
                txt_MaiorCompra.setText(formatarFloat.format(daoPedido.MaiorCompra(codigo)));
                txt_MediaPedidos.setText(formatarFloat.format(daoPedido.MediaCompras(codigo)));
                if (daoPedido.ProdutosMaisComprados(codigo).size() == 0) {

                    txt_ProdutoFavorito.setText("Nenhum");
                } else {
                    txt_ProdutoFavorito.setText(daoProduto.consultar(daoPedido.ProdutosMaisComprados(codigo).get(0).getProdutoCod()).getNome());

                }
                txt_qtdPedido.setText(listaPedido.size() + "");
                txt_QtdPedidosFaturados.setText(faturado + "");
                txt_PercentualFaturados.setText(formatarFloat.format(((faturado + 0.00) / (listaPedido.size() + 0.00)) * 100) + " (%)");
                System.out.println(faturado / listaPedido.size());
                System.out.println(faturado + " / " + listaPedido.size());

            } else {
                lbl_codigo.setText(codigo);
                lbl_nome.setText(PJ.getNome());
                txt_FrequenciaCompra.setText(formatarFloat.format(0));
                txt_MaiorCompra.setText(formatarFloat.format(0));
                txt_MediaPedidos.setText(formatarFloat.format(0));
                txt_ProdutoFavorito.setText("Nenhum");
                txt_qtdPedido.setText("0");
                txt_PercentualFaturados.setText("0.00 (%)");
                txt_QtdPedidosFaturados.setText("0");
            }
        }


    }//GEN-LAST:event_formWindowOpened

    private void Btn_mapa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_mapa1ActionPerformed
        dispose();
    }//GEN-LAST:event_Btn_mapa1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiControle_EstrategicoCliente_Individual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiControle_EstrategicoCliente_Individual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiControle_EstrategicoCliente_Individual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiControle_EstrategicoCliente_Individual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new GuiControle_EstrategicoCliente_Individual(login, codigo).setVisible(true);

            }
        });
    }
    private static Login login = null;
    private static String codigo;
    private Conexao conexao;
    private PessoaFisica PF;
    private PessoaJuridica PJ;
    private DaoPFisica daoPF;
    private DaoPJuridica daoPJ;
    private DaoGerarPedido daoPedido;
    private DaoProduto daoProduto;
    Date data = new Date(System.currentTimeMillis());
    SimpleDateFormat formatarDate = new SimpleDateFormat("dd/MM/yyyy");

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_mapa;
    private javax.swing.JButton Btn_mapa1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_mapa;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JPanel painel;
    private javax.swing.JTextField txt_FrequenciaCompra;
    private javax.swing.JTextField txt_MaiorCompra;
    private javax.swing.JTextField txt_MediaPedidos;
    private javax.swing.JTextField txt_PercentualFaturados;
    private javax.swing.JTextField txt_ProdutoFavorito;
    private javax.swing.JTextField txt_QtdPedidosFaturados;
    private javax.swing.JTextField txt_qtdPedido;
    // End of variables declaration//GEN-END:variables
}
