/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.vendas.view;

import static java.lang.Integer.parseInt;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import projeto.vendas.control.Conexao;
import projeto.vendas.control.DaoTesteExistencia;
import projeto.vendas.control.DaoVendedor;
import projeto.vendas.model.Vendedor;

/**
 *
 * @author Cleiton
 */
public class GuiCadastro_Vendedor extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_Funcionário
     */
    public GuiCadastro_Vendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        Painel_Cadastro_Vendedor = new javax.swing.JPanel();
        Painel_Registro_Vendedor = new javax.swing.JPanel();
        Painel_Contato = new javax.swing.JPanel();
        lblRG = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lblData_Nascimento = new javax.swing.JLabel();
        ftxtRG = new javax.swing.JFormattedTextField();
        ftxtTel = new javax.swing.JFormattedTextField();
        ftxtCPF = new javax.swing.JFormattedTextField();
        ftxtCel = new javax.swing.JFormattedTextField();
        ftxtData_Nasc = new javax.swing.JFormattedTextField();
        Painel_Endereço = new javax.swing.JPanel();
        txtCidade = new javax.swing.JTextField();
        lblRua = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        lblUF = new javax.swing.JLabel();
        txtUF = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblCEP = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        ftxtCEP = new javax.swing.JFormattedTextField();
        txtComplemento = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        Painel_Vendedor = new javax.swing.JPanel();
        lblBuscar_Por = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        lblBusca = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        Painel_Permissoes = new javax.swing.JPanel();
        cbxPermissoes = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaLegenda = new javax.swing.JTextArea();
        Painel_Nickname = new javax.swing.JPanel();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        lblcodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblNome_Colaborador = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Vendedor");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Painel_Registro_Vendedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Vendedor"));

        Painel_Contato.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));

        lblRG.setText("RG");

        lblEmail.setText("Email");

        txtEmail.setEnabled(false);

        lblTelefone.setText("Telefone");

        lblCPF.setText("CPF");

        lblCelular.setText("Celular");

        lblData_Nascimento.setText("Data Nascimento");

        try {
            ftxtRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtRG.setEnabled(false);

        try {
            ftxtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtTel.setEnabled(false);

        try {
            ftxtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCPF.setEnabled(false);

        try {
            ftxtCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCel.setEnabled(false);

        try {
            ftxtData_Nasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtData_Nasc.setEnabled(false);

        javax.swing.GroupLayout Painel_ContatoLayout = new javax.swing.GroupLayout(Painel_Contato);
        Painel_Contato.setLayout(Painel_ContatoLayout);
        Painel_ContatoLayout.setHorizontalGroup(
            Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail)
                            .addComponent(lblCelular)
                            .addComponent(ftxtCel, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblData_Nascimento)
                            .addComponent(ftxtCPF)
                            .addComponent(ftxtData_Nasc)))
                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(ftxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCPF)
                            .addComponent(lblTelefone)
                            .addComponent(ftxtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblRG, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );
        Painel_ContatoLayout.setVerticalGroup(
            Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftxtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCPF)
                            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ftxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRG, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                        .addComponent(lblCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                        .addComponent(lblData_Nascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxtData_Nasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Painel_Endereço.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        txtCidade.setEnabled(false);

        lblRua.setText("Rua");

        txtRua.setEnabled(false);

        lblUF.setText("UF");

        txtUF.setEnabled(false);

        lblNumero.setText("N°");

        txtNumero.setEnabled(false);

        lblCEP.setText("CEP");

        lblBairro.setText("Bairro");

        txtBairro.setEnabled(false);

        lblCidade.setText("Cidade");

        try {
            ftxtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCEP.setEnabled(false);

        txtComplemento.setEnabled(false);

        lblComplemento.setText("Complemento");

        javax.swing.GroupLayout Painel_EndereçoLayout = new javax.swing.GroupLayout(Painel_Endereço);
        Painel_Endereço.setLayout(Painel_EndereçoLayout);
        Painel_EndereçoLayout.setHorizontalGroup(
            Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCidade)
                                .addComponent(lblRua))
                            .addGap(100, 100, 100))
                        .addComponent(txtRua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCEP)
                            .addComponent(ftxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                        .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNumero)
                                .addComponent(txtUF, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addComponent(txtNumero))
                            .addComponent(lblUF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComplemento)
                            .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel_EndereçoLayout.setVerticalGroup(
            Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(lblUF)
                    .addComponent(lblComplemento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRua)
                    .addComponent(lblNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                        .addComponent(lblCEP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                        .addComponent(lblBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        Painel_Vendedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Vendedor"));

        lblBuscar_Por.setText("Buscar:");

        lblBusca.setText("Digite o Código:");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_VendedorLayout = new javax.swing.GroupLayout(Painel_Vendedor);
        Painel_Vendedor.setLayout(Painel_VendedorLayout);
        Painel_VendedorLayout.setHorizontalGroup(
            Painel_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_VendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Painel_VendedorLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnPesquisar)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Painel_VendedorLayout.createSequentialGroup()
                        .addGroup(Painel_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBuscar_Por, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        Painel_VendedorLayout.setVerticalGroup(
            Painel_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_VendedorLayout.createSequentialGroup()
                .addGroup(Painel_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar_Por, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(32, 32, 32)
                .addGroup(Painel_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.setEnabled(false);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setEnabled(false);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        Painel_Permissoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Permissões"));

        cbxPermissoes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Gerente de Vendas", "Supervisor de Vendas" }));
        cbxPermissoes.setEnabled(false);
        cbxPermissoes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxPermissoesItemStateChanged(evt);
            }
        });

        txaLegenda.setBackground(new java.awt.Color(240, 240, 240));
        txaLegenda.setColumns(20);
        txaLegenda.setRows(5);
        txaLegenda.setText("* Cadastrar Cliente;\n* Gerar Pedido;\n* Emitir Nota Fiscal.");
        jScrollPane1.setViewportView(txaLegenda);

        javax.swing.GroupLayout Painel_PermissoesLayout = new javax.swing.GroupLayout(Painel_Permissoes);
        Painel_Permissoes.setLayout(Painel_PermissoesLayout);
        Painel_PermissoesLayout.setHorizontalGroup(
            Painel_PermissoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_PermissoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_PermissoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(cbxPermissoes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Painel_PermissoesLayout.setVerticalGroup(
            Painel_PermissoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Painel_PermissoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxPermissoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
        );

        Painel_Nickname.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));

        lblSenha.setText("Senha");

        txtSenha.setEnabled(false);

        javax.swing.GroupLayout Painel_NicknameLayout = new javax.swing.GroupLayout(Painel_Nickname);
        Painel_Nickname.setLayout(Painel_NicknameLayout);
        Painel_NicknameLayout.setHorizontalGroup(
            Painel_NicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_NicknameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_NicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 186, Short.MAX_VALUE))
        );
        Painel_NicknameLayout.setVerticalGroup(
            Painel_NicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_NicknameLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        lblcodigo.setText("Código de Registro:");

        txtCodigo.setEnabled(false);

        lblNome_Colaborador.setText("Nome do Colaborador:");

        txtNome.setEnabled(false);

        javax.swing.GroupLayout Painel_Registro_VendedorLayout = new javax.swing.GroupLayout(Painel_Registro_Vendedor);
        Painel_Registro_Vendedor.setLayout(Painel_Registro_VendedorLayout);
        Painel_Registro_VendedorLayout.setHorizontalGroup(
            Painel_Registro_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Registro_VendedorLayout.createSequentialGroup()
                .addGroup(Painel_Registro_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_Registro_VendedorLayout.createSequentialGroup()
                        .addGroup(Painel_Registro_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_Registro_VendedorLayout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addGroup(Painel_Registro_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Painel_Contato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Painel_Endereço, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(Painel_Registro_VendedorLayout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(Painel_Registro_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Painel_Registro_VendedorLayout.createSequentialGroup()
                                .addComponent(btnLimpar)
                                .addGap(157, 157, 157)
                                .addComponent(btnCadastrar))
                            .addComponent(Painel_Nickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Painel_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Painel_Permissoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Painel_Registro_VendedorLayout.createSequentialGroup()
                        .addComponent(lblcodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblNome_Colaborador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        Painel_Registro_VendedorLayout.setVerticalGroup(
            Painel_Registro_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Registro_VendedorLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(Painel_Registro_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome_Colaborador)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(Painel_Registro_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Painel_Registro_VendedorLayout.createSequentialGroup()
                        .addComponent(Painel_Contato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Painel_Endereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Painel_Registro_VendedorLayout.createSequentialGroup()
                        .addComponent(Painel_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Painel_Permissoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Painel_Nickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Painel_Registro_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltar)
                    .addGroup(Painel_Registro_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimpar)
                        .addComponent(btnCadastrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Painel_Cadastro_VendedorLayout = new javax.swing.GroupLayout(Painel_Cadastro_Vendedor);
        Painel_Cadastro_Vendedor.setLayout(Painel_Cadastro_VendedorLayout);
        Painel_Cadastro_VendedorLayout.setHorizontalGroup(
            Painel_Cadastro_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Cadastro_VendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel_Registro_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        Painel_Cadastro_VendedorLayout.setVerticalGroup(
            Painel_Cadastro_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Cadastro_VendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel_Registro_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Painel_Cadastro_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Painel_Cadastro_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao();
        conexao.setDriver();
        conexao.setConnectionString();
        daoVendedor = new DaoVendedor(conexao.conectar());  
    }//GEN-LAST:event_formWindowOpened

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (btnCadastrar.getText() == "Reativar Vendedor") {
            if (JOptionPane.showConfirmDialog(null, "Confirma Reativação?") == 0) {
                JOptionPane.showMessageDialog(null, "Reativação Efetuada com sucesso!");
                vendedor.setAtivo("A");
                daoVendedor.reativarVendedor(vendedor);

                txtBusca.requestFocus();

                ftxtRG.setText("");
                ftxtCEP.setText("");
                ftxtCPF.setText("");
                ftxtCel.setText("");
                ftxtData_Nasc.setText("");
                ftxtTel.setText("");
                cbxPermissoes.setSelectedIndex(0);
                cbxPermissoes.setEnabled(false);

                txtRua.setText("");
                txtNumero.setText("");
                txtBairro.setText("");
                txtCidade.setText("");
                txtUF.setText("");
                txtComplemento.setText("");

                txtSenha.setText("");
                txtNome.setText("");
                txtCodigo.setText("");
                txtEmail.setText("");
                txtBusca.setText("");
                btnCadastrar.setText("Cadastrar");
                btnCadastrar.setEnabled(false);
            }
        } else {
            if (JOptionPane.showConfirmDialog(null, "Confirma Cadastro?") == 0) {
                JOptionPane.showMessageDialog(null, "Cadastro Efetuado com sucesso!");
                vendedor = new Vendedor(parseInt(txtCodigo.getText()), txtNome.getText(),
                        ftxtRG.getText().replace(".", "").replace("-", ""),
                        ftxtCPF.getText().replace(".", "").replace("-", ""), txtEmail.getText(),
                        ftxtTel.getText(), ftxtCel.getText(), ftxtData_Nasc.getText().replace("/", ""),
                        txtRua.getText(), txtNumero.getText(), txtBairro.getText(), txtCidade.getText(),
                        txtUF.getText(), ftxtCEP.getText().replace("-", ""));
                vendedor.setPermissao(cbxPermissoes.getSelectedIndex());
                vendedor.setSenha(txtSenha.getText());
                vendedor.setComplemento(txtComplemento.getText());

                //cria o formatador de data
                SimpleDateFormat formatador = new SimpleDateFormat("ddMMyyyy");  
		 //cria um objeto date com a data do sistema
		Date dataDoSistema = new Date(System.currentTimeMillis());
		 //passa o objeto dataDoSistema para uma String da forma que pediu
		String dataEmTexto = formatador.format(dataDoSistema);  
                //passa o valor como string para o atributo
                vendedor.setDtInicio(dataEmTexto);
                
                daoVendedor.inserir(vendedor);
                btnCadastrar.setEnabled(false);

                txtBusca.requestFocus();

                ftxtRG.setText("");
                ftxtCEP.setText("");
                ftxtCPF.setText("");
                ftxtCel.setText("");
                ftxtData_Nasc.setText("");
                ftxtTel.setText("");
                cbxPermissoes.setSelectedIndex(0);
                cbxPermissoes.setEnabled(false);

                txtRua.setText("");
                txtNumero.setText("");
                txtBairro.setText("");
                txtCidade.setText("");
                txtUF.setText("");
                txtComplemento.setText("");

                txtSenha.setText("");
                txtNome.setText("");
                txtCodigo.setText("");
                txtEmail.setText("");
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtBusca.requestFocus();

        ftxtRG.setText("");
        ftxtCEP.setText("");
        ftxtCPF.setText("");
        ftxtCel.setText("");
        ftxtData_Nasc.setText("");
        ftxtTel.setText("");
        cbxPermissoes.setSelectedIndex(0);
        cbxPermissoes.setEnabled(false);

        txtRua.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        txtUF.setText("");
        txtComplemento.setText("");

        txtSenha.setText("");
        txtNome.setText("");
        txtCodigo.setText("");
        txtEmail.setText("");
        txtSenha.setEnabled(false);
        btnLimpar.setEnabled(false);
        txtBusca.setText("");
        btnCadastrar.setEnabled(false);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        vendedor = null;
        if (txtBusca.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite um código!");
            txtBusca.requestFocus();
        } else {
            vendedor = daoVendedor.consultar(parseInt(txtBusca.getText()));

            if (vendedor == null) {
                JOptionPane.showMessageDialog(null, "Código inválido!");
                txtBusca.requestFocus();
            } else {
                vendedor1 = null;
                vendedor1 = daoVendedor.consultarTbVend(parseInt(txtBusca.getText()));
                if (vendedor1 == null) {
                    txtCodigo.setText(String.valueOf(vendedor.getCodigo()));
                    txtNome.setText(vendedor.getNome());
                    ftxtRG.setText(vendedor.getRg());
                    ftxtTel.setText(vendedor.getTel());
                    txtEmail.setText(vendedor.getEmail());
                    ftxtCPF.setText(vendedor.getCpf());
                    ftxtCel.setText(vendedor.getCel());
                    ftxtData_Nasc.setText(vendedor.getDataNasc());

                    txtCidade.setText(vendedor.getCidade());
                    txtUF.setText(vendedor.getUf());
                    txtRua.setText(vendedor.getRua());
                    txtNumero.setText(vendedor.getNumero());
                    ftxtCEP.setText(vendedor.getCep());
                    txtBairro.setText(vendedor.getBairro());
                    txtComplemento.setText(vendedor.getComplemento());
                    txtSenha.setText(vendedor.getCpf());

                    cbxPermissoes.requestFocus();
                    cbxPermissoes.setEnabled(true);
                    txtSenha.setEnabled(true);
                    btnCadastrar.setEnabled(true);
                    btnLimpar.setEnabled(true);
                } else {
                    txtCodigo.setText(String.valueOf(vendedor1.getCodigo()));
                    txtNome.setText(vendedor1.getNome());
                    ftxtRG.setText(vendedor1.getRg());
                    ftxtTel.setText(vendedor1.getTel());
                    txtEmail.setText(vendedor1.getEmail());
                    ftxtCPF.setText(vendedor1.getCpf());
                    ftxtCel.setText(vendedor1.getCel());
                    ftxtData_Nasc.setText(vendedor1.getDataNasc());

                    txtCidade.setText(vendedor1.getCidade());
                    txtUF.setText(vendedor1.getUf());
                    txtRua.setText(vendedor1.getRua());
                    txtNumero.setText(vendedor1.getNumero());
                    ftxtCEP.setText(vendedor1.getCep());
                    txtBairro.setText(vendedor1.getBairro());
                    txtComplemento.setText(vendedor1.getComplemento());
                    txtSenha.setText(vendedor1.getCpf());
                    cbxPermissoes.setSelectedIndex(vendedor1.getPermissao());

                    JOptionPane.showMessageDialog(null, "Este Colaborador já está Cadastrado!");
                    if (vendedor1.getAtivo().equals("I")) {
                        JOptionPane.showMessageDialog(null, "Este Colaborador ja foi cadastrado"
                                + " no passado, você pode reativa-lo se desejar!");
                        btnCadastrar.setText("Reativar Vendedor");
                        btnCadastrar.setEnabled(true);
                    } else {
                        txtBusca.requestFocus();
                        ftxtRG.setText("");
                        ftxtCEP.setText("");
                        ftxtCPF.setText("");
                        ftxtCel.setText("");
                        ftxtData_Nasc.setText("");
                        ftxtTel.setText("");
                        cbxPermissoes.setSelectedIndex(0);

                        txtRua.setText("");
                        txtNumero.setText("");
                        txtBairro.setText("");
                        txtCidade.setText("");
                        txtUF.setText("");
                        txtComplemento.setText("");

                        txtSenha.setText("");
                        txtNome.setText("");
                        txtCodigo.setText("");
                        txtEmail.setText("");
                        cbxPermissoes.setEnabled(false);
                        txtBusca.setText("");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void cbxPermissoesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxPermissoesItemStateChanged
        if (cbxPermissoes.getSelectedIndex() == 0) {
            txaLegenda.setText("* Cadastrar Cliente;\n"
                    + "* Gerar Pedido;\n"
                    + "* Emitir Nota Fiscal.");
        } else if (cbxPermissoes.getSelectedIndex() == 1) {
            txaLegenda.setText("* Cadastrar Cliente;\n"
                    + "* Gerar Pedido;\n"
                    + "* Emitir Nota Fiscal;\n"
                    + "* Controle Estratégico;\n"
                    + "* Funcionalidades Gerenciais;\n"
                    + "* Gerencia de exclusão e alteração.");
        } else {
            txaLegenda.setText("* Cadastrar Cliente;\n"
                    + "* Gerar Pedido;\n"
                    + "* Emitir Nota Fiscal;\n"
                    + "* Controle Estratégico;\n"
                    + "* Gerencia de exclusão e alteração.");
        }


    }//GEN-LAST:event_cbxPermissoesItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiCadastro_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiCadastro_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiCadastro_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiCadastro_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiCadastro_Vendedor().setVisible(true);
            }
        });
    }

    private Conexao conexao = null;
    private Vendedor vendedor = null;
    private Vendedor vendedor1 = null;
    private DaoVendedor daoVendedor = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_Cadastro_Vendedor;
    private javax.swing.JPanel Painel_Contato;
    private javax.swing.JPanel Painel_Endereço;
    private javax.swing.JPanel Painel_Nickname;
    private javax.swing.JPanel Painel_Permissoes;
    private javax.swing.JPanel Painel_Registro_Vendedor;
    private javax.swing.JPanel Painel_Vendedor;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbxPermissoes;
    private javax.swing.JFormattedTextField ftxtCEP;
    private javax.swing.JFormattedTextField ftxtCPF;
    private javax.swing.JFormattedTextField ftxtCel;
    private javax.swing.JFormattedTextField ftxtData_Nasc;
    private javax.swing.JFormattedTextField ftxtRG;
    private javax.swing.JFormattedTextField ftxtTel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblBuscar_Por;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblData_Nascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome_Colaborador;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUF;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JTextArea txaLegenda;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUF;
    // End of variables declaration//GEN-END:variables
}
