/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.vendas.view;

import java.awt.Image;
import java.awt.Toolkit;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.net.URL;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import projeto.vendas.control.Conexao;
import projeto.vendas.control.DaoDescobreCodigo;
import projeto.vendas.control.DaoLogin;
import projeto.vendas.control.DaoPJuridica;
import projeto.vendas.control.DaoVendedor;
import projeto.vendas.model.Coordenadas;
import projeto.vendas.model.Login;
import projeto.vendas.model.PessoaJuridica;
import projeto.vendas.model.Vendedor;
import projeto.vendas.model.validacoes.ValidaCNPJ;
import projeto.vendas.model.validacoes.ValidaEmail;
import static projeto.vendas.model.validacoes.ValidaEmail.validaEmail;

/**
 *
 * @author Cleiton
 */
public class GuiCadastroPessoa_Jurídica extends javax.swing.JFrame {

    /**
     * Creates new form Pessoa_Jurídica
     */
    public GuiCadastroPessoa_Jurídica(Login login) {
        initComponents();
        this.login = login;
        this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE); 
        GuiCadastroPessoa_Jurídica.this.setTitle("Cadastro Pessoa Juridica    " + "Usuário:  " + login.getNome()+
                "         " +"Codigo:  " + login.getCodigo());
        
        URL caminhoIcone = getClass().getResource("/projeto/vendas/model/icones/logotipo.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Pessoa_Jurídica = new javax.swing.JPanel();
        Painel_Dados = new javax.swing.JPanel();
        lblNome_Fantasia = new javax.swing.JLabel();
        txtNome_Fantasia = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblCNPJ = new javax.swing.JLabel();
        lblVendedor_Responsável = new javax.swing.JLabel();
        ftxtCNPJ = new javax.swing.JFormattedTextField();
        lblAsteristico = new javax.swing.JLabel();
        lblAsteristico1 = new javax.swing.JLabel();
        lblAsteristico2 = new javax.swing.JLabel();
        cbxVendedorResp = new javax.swing.JComboBox<>();
        lblAsteristico12 = new javax.swing.JLabel();
        lblCódigo_Cliente = new javax.swing.JLabel();
        Painel_Endereço = new javax.swing.JPanel();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblRua = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblCEP = new javax.swing.JLabel();
        ftxtCEP = new javax.swing.JFormattedTextField();
        lblAsteristico5 = new javax.swing.JLabel();
        lblAsteristico6 = new javax.swing.JLabel();
        lblAsteristico7 = new javax.swing.JLabel();
        lblAsteristico8 = new javax.swing.JLabel();
        lblAsteristico9 = new javax.swing.JLabel();
        lblAsteristico10 = new javax.swing.JLabel();
        lblComplemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblUF = new javax.swing.JLabel();
        cbxUF = new javax.swing.JComboBox<>();
        btnVoltar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        ftxtCodigo_PJ = new javax.swing.JFormattedTextField();
        Painel_Contato = new javax.swing.JPanel();
        lblcontato1 = new javax.swing.JLabel();
        txtNome_Contato1 = new javax.swing.JTextField();
        lblTelefone1 = new javax.swing.JLabel();
        ftxtTelefone1 = new javax.swing.JFormattedTextField();
        lblAsteristico11 = new javax.swing.JLabel();
        lblAsteristico14 = new javax.swing.JLabel();
        lblcontato2 = new javax.swing.JLabel();
        lblTelefone2 = new javax.swing.JLabel();
        txtNome_Contato2 = new javax.swing.JTextField();
        ftxtTelefone2 = new javax.swing.JFormattedTextField();
        lblcontato3 = new javax.swing.JLabel();
        txtNome_Contato3 = new javax.swing.JTextField();
        ftxtCelular = new javax.swing.JFormattedTextField();
        lblCelular = new javax.swing.JLabel();
        lblPessoa_Juridica = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Cliente Pessoa Jurídica");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Painel_Pessoa_Jurídica.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pessoa Jurídica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        Painel_Dados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Cadastrais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        lblNome_Fantasia.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblNome_Fantasia.setText("Nome Fantasia");

        lblEmail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmail.setText("Email");

        lblCNPJ.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCNPJ.setText("CNPJ");

        lblVendedor_Responsável.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblVendedor_Responsável.setText("Vendedor Responsável");

        try {
            ftxtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCNPJ.setText("");
        ftxtCNPJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtCNPJFocusLost(evt);
            }
        });

        lblAsteristico.setText("*");

        lblAsteristico1.setText("*");

        lblAsteristico2.setText("*");

        lblAsteristico12.setText("*");

        javax.swing.GroupLayout Painel_DadosLayout = new javax.swing.GroupLayout(Painel_Dados);
        Painel_Dados.setLayout(Painel_DadosLayout);
        Painel_DadosLayout.setHorizontalGroup(
            Painel_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_DadosLayout.createSequentialGroup()
                .addGroup(Painel_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_DadosLayout.createSequentialGroup()
                        .addComponent(txtNome_Fantasia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAsteristico))
                    .addGroup(Painel_DadosLayout.createSequentialGroup()
                        .addGroup(Painel_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome_Fantasia)
                            .addGroup(Painel_DadosLayout.createSequentialGroup()
                                .addComponent(ftxtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAsteristico12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Painel_DadosLayout.createSequentialGroup()
                                .addGroup(Painel_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxVendedorResp, javax.swing.GroupLayout.Alignment.LEADING, 0, 349, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Painel_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblAsteristico2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAsteristico1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lblVendedor_Responsável)
                            .addComponent(lblCNPJ)
                            .addComponent(lblEmail))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Painel_DadosLayout.setVerticalGroup(
            Painel_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_DadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNome_Fantasia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome_Fantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(lblCNPJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblVendedor_Responsável)
                .addGap(7, 7, 7)
                .addGroup(Painel_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxVendedorResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico2))
                .addContainerGap())
        );

        lblCódigo_Cliente.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lblCódigo_Cliente.setText("Código Cliente:");

        Painel_Endereço.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        lblCidade.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCidade.setText("Cidade");

        lblRua.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblRua.setText("Rua/Avenida/Estrada/Viela");

        lblBairro.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblBairro.setText("Bairro/Vila/Parque");

        lblNumero.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblNumero.setText("N°");

        lblCEP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCEP.setText("CEP");

        try {
            ftxtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCEP.setText("");

        lblAsteristico5.setText("*");

        lblAsteristico6.setText("*");

        lblAsteristico7.setText("*");

        lblAsteristico8.setText("*");

        lblAsteristico9.setText("*");

        lblAsteristico10.setText("*");

        lblComplemento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblComplemento.setText("Complemento");

        lblUF.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblUF.setText("UF");

        cbxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        javax.swing.GroupLayout Painel_EndereçoLayout = new javax.swing.GroupLayout(Painel_Endereço);
        Painel_Endereço.setLayout(Painel_EndereçoLayout);
        Painel_EndereçoLayout.setHorizontalGroup(
            Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                        .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblRua)
                            .addComponent(lblBairro)
                            .addComponent(txtBairro)
                            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAsteristico5)
                                .addGap(35, 35, 35)
                                .addComponent(ftxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAsteristico8))
                            .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                                .addComponent(lblAsteristico6)
                                .addGap(8, 8, 8)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAsteristico9))
                            .addComponent(lblAsteristico7)
                            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUF)
                                    .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNumero)
                                            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                                                .addComponent(cbxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblAsteristico10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE))
                    .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                        .addComponent(lblCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCEP)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComplemento)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel_EndereçoLayout.setVerticalGroup(
            Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(lblCEP)
                    .addComponent(lblUF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico5)
                    .addComponent(lblAsteristico8)
                    .addComponent(lblAsteristico10)
                    .addComponent(cbxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRua)
                    .addComponent(lblNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico6)
                    .addComponent(lblAsteristico9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBairro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComplemento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnVoltar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Voltar.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnCadastrar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Aprovar.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        try {
            ftxtCodigo_PJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("PJ#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCodigo_PJ.setText("");
        ftxtCodigo_PJ.setEnabled(false);

        Painel_Contato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        lblcontato1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblcontato1.setText("Nome do contato 1");

        lblTelefone1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblTelefone1.setText("Telefone 1");

        try {
            ftxtTelefone1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtTelefone1.setText("");

        lblAsteristico11.setText("*");

        lblAsteristico14.setText("*");

        lblcontato2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblcontato2.setText("Nome do contato 2");

        lblTelefone2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblTelefone2.setText("Telefone 2");

        try {
            ftxtTelefone2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblcontato3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblcontato3.setText("Nome do contato 3");

        try {
            ftxtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblCelular.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCelular.setText("Celular");

        javax.swing.GroupLayout Painel_ContatoLayout = new javax.swing.GroupLayout(Painel_Contato);
        Painel_Contato.setLayout(Painel_ContatoLayout);
        Painel_ContatoLayout.setHorizontalGroup(
            Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome_Contato2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcontato2)
                    .addComponent(lblcontato3)
                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                .addComponent(txtNome_Contato1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAsteristico11))
                            .addComponent(lblcontato1))
                        .addGap(19, 19, 19)
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                .addComponent(ftxtTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAsteristico14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTelefone1)))
                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                        .addComponent(txtNome_Contato3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftxtTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefone2)
                            .addComponent(lblCelular)
                            .addComponent(ftxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        Painel_ContatoLayout.setVerticalGroup(
            Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcontato1)
                    .addComponent(lblTelefone1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome_Contato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico11)
                    .addComponent(lblAsteristico14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                        .addComponent(lblcontato2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome_Contato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_ContatoLayout.createSequentialGroup()
                        .addComponent(lblTelefone2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxtTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcontato3)
                    .addComponent(lblCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome_Contato3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout Painel_Pessoa_JurídicaLayout = new javax.swing.GroupLayout(Painel_Pessoa_Jurídica);
        Painel_Pessoa_Jurídica.setLayout(Painel_Pessoa_JurídicaLayout);
        Painel_Pessoa_JurídicaLayout.setHorizontalGroup(
            Painel_Pessoa_JurídicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Pessoa_JurídicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_Pessoa_JurídicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_Pessoa_JurídicaLayout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpar)
                        .addGap(89, 89, 89)
                        .addComponent(btnCadastrar)
                        .addGap(100, 100, 100))
                    .addGroup(Painel_Pessoa_JurídicaLayout.createSequentialGroup()
                        .addGroup(Painel_Pessoa_JurídicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_Pessoa_JurídicaLayout.createSequentialGroup()
                                .addComponent(lblCódigo_Cliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftxtCodigo_PJ, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Painel_Pessoa_JurídicaLayout.createSequentialGroup()
                                .addComponent(Painel_Dados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Painel_Endereço, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Painel_Contato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Painel_Pessoa_JurídicaLayout.setVerticalGroup(
            Painel_Pessoa_JurídicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Pessoa_JurídicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_Pessoa_JurídicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtCodigo_PJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCódigo_Cliente))
                .addGap(7, 7, 7)
                .addGroup(Painel_Pessoa_JurídicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Painel_Pessoa_JurídicaLayout.createSequentialGroup()
                        .addComponent(Painel_Endereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Painel_Pessoa_JurídicaLayout.createSequentialGroup()
                        .addComponent(Painel_Dados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Painel_Contato, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Painel_Pessoa_JurídicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVoltar)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastrar))
                        .addGap(21, 21, 21))))
        );

        lblPessoa_Juridica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPessoa_Juridica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Pessoa Juridica.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPessoa_Juridica, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Painel_Pessoa_Jurídica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Painel_Pessoa_Jurídica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(lblPessoa_Juridica, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao();
        conexao.setDriver();
        conexao.setConnectionString();
        daoPJuridica = new DaoPJuridica(conexao.conectar());
        daoVendedor = new DaoVendedor(conexao.conectar());
        daoDescobreCodigo = new DaoDescobreCodigo(conexao.conectar());

        vendedores = daoVendedor.listarVendedores();

        for (int x = 0; x < vendedores.size(); x++) {
            cbxVendedorResp.addItem(vendedores.get(x).getNome());
        }
        //descobrir e gerar codigo sequencial
        int aux = daoDescobreCodigo.consultarCodPJ();
        if (aux == 0) {
            ftxtCodigo_PJ.setText("1");
        } else {
            aux = aux + 1;
            ftxtCodigo_PJ.setText(String.valueOf(aux));
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNome_Fantasia.requestFocus();

        txtNome_Fantasia.setText("");
        ftxtCNPJ.setText("");
        txtEmail.setText("");
        ftxtTelefone1.setText("");
        ftxtTelefone2.setText("");
        ftxtCelular.setText("");
        txtNome_Contato1.setText("");
        txtNome_Contato3.setText("");
        txtNome_Contato2.setText("");

        cbxVendedorResp.setSelectedIndex(0);

        ftxtCEP.setText("");
        txtRua.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        cbxUF.setSelectedIndex(0);
        txtComplemento.setText("");

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String alerta = "";
        if (txtNome_Fantasia.getText().equals("")) {
            alerta = alerta + "Digite o Nome Fantasia do cliente!" + "\n";
        }
        if (ftxtCNPJ.getText().replace(".", "").replace("-", "").replace(" ", "").replace("/", "").equals("")) {
            alerta = alerta + "Digite o CNPJ do cliente!" + "\n";
        }
        if (txtEmail.getText().equals("")) {
            alerta = alerta + "Digite o e-mail do cliente!" + "\n";
        }
        if (ValidaEmail.validaEmail(txtEmail.getText()) == false) {
            alerta = alerta + "Digite um e-mail valido!" + "\n";
        }
        if (txtRua.getText().equals("")) {
            alerta = alerta + "Digite a rua do cliente!" + "\n";
        }
        if (txtNumero.getText().equals("")) {
            alerta = alerta + "Digite o numero do cliente!" + "\n";
        }
        if (txtBairro.getText().equals("")) {
            alerta = alerta + "Digite o bairro do cliente!" + "\n";
        }
        if (txtCidade.getText().equals("")) {
            alerta = alerta + "Digite a cidade do cliente!" + "\n";
        }
        if (ftxtCEP.getText().replace("-", "").replace(" ", "").equals("")) {
            alerta = alerta + "Digite o CEP do cliente!" + "\n";
        }
        if (ftxtTelefone1.getText().replace("(", "").replace(")", "").
                replace("-","").replace(" ","").equals("")) {
            alerta = alerta + "Digite um numero de contato!" + "\n";
        }
        if (!(alerta == "")) {
            JOptionPane.showMessageDialog(null, alerta);
            alerta = "";
        } else {
            if (JOptionPane.showConfirmDialog(null, "Confirma Cadastro?") == 0) {//Sim
                JOptionPane.showMessageDialog(null, "Cadastro Efetuado com sucesso!");
                pessoaJuridica = new PessoaJuridica(ftxtCodigo_PJ.getText().replace(" ", ""), txtNome_Fantasia.getText(),
                        txtEmail.getText(), txtRua.getText(), txtNumero.getText(), txtBairro.getText(),
                        txtCidade.getText(), (String) cbxUF.getSelectedItem(), ftxtCEP.getText().replace("-", ""),
                        "A");
                pessoaJuridica.setCnpj(ftxtCNPJ.getText().replace(".", "").replace("-", "").replace("/", ""));

                pessoaJuridica.setContato1(txtNome_Contato1.getText());
                pessoaJuridica.setTel1(ftxtTelefone1.getText().replace("(", "").replace(")", "").replace("-", ""));
                pessoaJuridica.setContato2(txtNome_Contato2.getText());
                pessoaJuridica.setTel2(ftxtTelefone2.getText().replace("(", "").replace(")", "").replace("-", ""));
                pessoaJuridica.setContato3(txtNome_Contato3.getText());
                pessoaJuridica.setTel3(ftxtCelular.getText().replace("(", "").replace(")", "").replace("-", ""));
                pessoaJuridica.setComplemento(txtComplemento.getText());
                coordenadas.Buscar(txtNumero.getText(), txtRua.getText(), txtBairro.getText(), txtCidade.getText());
                pessoaJuridica.setLatitude(coordenadas.getLatitude());
                pessoaJuridica.setLongitude(coordenadas.getLongitude());

                ArrayList<Vendedor> vendedores = daoVendedor.listarVendedores();
                vendedor = daoVendedor.consultar(vendedores.get(cbxVendedorResp.getSelectedIndex()).getCodigo());
                pessoaJuridica.setVendedor_responsavel((String) cbxVendedorResp.getSelectedItem());
                pessoaJuridica.setCod_vend_resp(vendedor.getCodigo());

                //cria o formatador de data
                SimpleDateFormat formatador = new SimpleDateFormat("ddMMyyyy");
                //cria um objeto date com a data do sistema
                Date dataDoSistema = new Date(System.currentTimeMillis());
                //passa o objeto dataDoSistema para uma String da forma que pediu
                String dataEmTexto = formatador.format(dataDoSistema);
                //passa o valor como string para o atributo
                pessoaJuridica.setDtInicio(dataEmTexto);

                daoPJuridica.inserir(pessoaJuridica);

                int aux = parseInt(ftxtCodigo_PJ.getText().replace("PJ", "").replace(" ", ""));
                ftxtCodigo_PJ.setText(String.valueOf(aux + 1));

                txtNome_Fantasia.requestFocus();

                txtNome_Fantasia.setText("");
                ftxtCNPJ.setText("");
                txtEmail.setText("");
                ftxtTelefone1.setText("");
                ftxtTelefone2.setText("");
                ftxtCelular.setText("");
                txtNome_Contato1.setText("");
                txtNome_Contato3.setText("");
                txtNome_Contato2.setText("");;

                cbxVendedorResp.setSelectedIndex(0);

                ftxtCEP.setText("");
                txtRua.setText("");
                txtNumero.setText("");
                txtBairro.setText("");
                txtCidade.setText("");
                cbxUF.setSelectedIndex(0);
                txtComplemento.setText("");
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void ftxtCNPJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtCNPJFocusLost
        //if(ValidaCNPJ.validaCnpj(ftxtCNPJ.getText().replace("-","").replace(".","")
        //                            .replace(" ","").replace("/","")) == false){
        //     ftxtCNPJ.setText("");
        //   JOptionPane.showMessageDialog(null,"Digite um CNPJ válido!"); 
        //}
        pessoaJuridica = daoPJuridica.consultaCNPJ(ftxtCNPJ.getText().
                replace("-", "").replace(".", "").replace(" ", "").replace("/", ""));
        if (!(pessoaJuridica == null)) {
            ftxtCNPJ.setText("");
            JOptionPane.showMessageDialog(null, "Este CNPJ ja está cadastrado no sistema!");
        }
    }//GEN-LAST:event_ftxtCNPJFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiCadastroPessoa_Jurídica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiCadastroPessoa_Jurídica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiCadastroPessoa_Jurídica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiCadastroPessoa_Jurídica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiCadastroPessoa_Jurídica(login).setVisible(true);
            }
        });
    }
    private static Login login = null;
    private Conexao conexao = null;
    private DaoPJuridica daoPJuridica = null;
    private PessoaJuridica pessoaJuridica = null;
    private DaoVendedor daoVendedor = null;
    private Vendedor vendedor = null;
    private DaoDescobreCodigo daoDescobreCodigo = null;
    private ArrayList<Vendedor> vendedores = null;
    private Coordenadas coordenadas = new Coordenadas();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_Contato;
    private javax.swing.JPanel Painel_Dados;
    private javax.swing.JPanel Painel_Endereço;
    private javax.swing.JPanel Painel_Pessoa_Jurídica;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbxUF;
    private javax.swing.JComboBox<String> cbxVendedorResp;
    private javax.swing.JFormattedTextField ftxtCEP;
    private javax.swing.JFormattedTextField ftxtCNPJ;
    private javax.swing.JFormattedTextField ftxtCelular;
    private javax.swing.JFormattedTextField ftxtCodigo_PJ;
    private javax.swing.JFormattedTextField ftxtTelefone1;
    private javax.swing.JFormattedTextField ftxtTelefone2;
    private javax.swing.JLabel lblAsteristico;
    private javax.swing.JLabel lblAsteristico1;
    private javax.swing.JLabel lblAsteristico10;
    private javax.swing.JLabel lblAsteristico11;
    private javax.swing.JLabel lblAsteristico12;
    private javax.swing.JLabel lblAsteristico14;
    private javax.swing.JLabel lblAsteristico2;
    private javax.swing.JLabel lblAsteristico5;
    private javax.swing.JLabel lblAsteristico6;
    private javax.swing.JLabel lblAsteristico7;
    private javax.swing.JLabel lblAsteristico8;
    private javax.swing.JLabel lblAsteristico9;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblCódigo_Cliente;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome_Fantasia;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPessoa_Juridica;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblTelefone1;
    private javax.swing.JLabel lblTelefone2;
    private javax.swing.JLabel lblUF;
    private javax.swing.JLabel lblVendedor_Responsável;
    private javax.swing.JLabel lblcontato1;
    private javax.swing.JLabel lblcontato2;
    private javax.swing.JLabel lblcontato3;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome_Contato1;
    private javax.swing.JTextField txtNome_Contato2;
    private javax.swing.JTextField txtNome_Contato3;
    private javax.swing.JTextField txtNome_Fantasia;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
