/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.vendas.view;

import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import projeto.vendas.control.Conexao;
import projeto.vendas.control.DaoDescobreCodigo;
import projeto.vendas.control.DaoLogin;
import projeto.vendas.control.DaoPFisica;
import projeto.vendas.control.DaoVendedor;
import projeto.vendas.model.Login;
import projeto.vendas.model.PessoaFisica;
import projeto.vendas.model.Vendedor;
import projeto.vendas.model.validacoes.ValidaCPF;
import projeto.vendas.model.validacoes.ValidaEmail;
import static projeto.vendas.model.validacoes.ValidaEmail.validaEmail;

/**
 *
 * @author Cleiton
 */
public class GuiCadastroPessoa_Física extends javax.swing.JFrame {

    /**
     * Creates new form Pessoa_Física
     */
    public GuiCadastroPessoa_Física() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Pessoa_Física = new javax.swing.JPanel();
        Painel_Contato = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblRG = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblVendedor_Responsável = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        ftxtCelular = new javax.swing.JFormattedTextField();
        lblData_Nascimento = new javax.swing.JLabel();
        ftxtData_Nasc = new javax.swing.JFormattedTextField();
        ftxtTelefone = new javax.swing.JFormattedTextField();
        ftxtCPF = new javax.swing.JFormattedTextField();
        ftxtRG = new javax.swing.JFormattedTextField();
        lblAsteristico = new javax.swing.JLabel();
        lblAsteristico1 = new javax.swing.JLabel();
        lblAsteristico2 = new javax.swing.JLabel();
        lblAsteristico3 = new javax.swing.JLabel();
        lblAsteristico4 = new javax.swing.JLabel();
        lblAsteristico5 = new javax.swing.JLabel();
        cbxVendedorResp = new javax.swing.JComboBox<>();
        lblCódigo_Cliente = new javax.swing.JLabel();
        Painel_Endereço = new javax.swing.JPanel();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblRua = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblUF = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblCEP = new javax.swing.JLabel();
        ftxtCEP = new javax.swing.JFormattedTextField();
        lblAsteristico6 = new javax.swing.JLabel();
        lblAsteristico7 = new javax.swing.JLabel();
        lblAsteristico8 = new javax.swing.JLabel();
        lblAsteristico9 = new javax.swing.JLabel();
        lblAsteristico11 = new javax.swing.JLabel();
        lblAsteristico12 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        cbx_Uf = new javax.swing.JComboBox<>();
        btnVoltar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        ftxtCodigoCliente = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Cliente Pessoa Física");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Painel_Pessoa_Física.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoa Física"));

        Painel_Contato.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));

        lblNome.setText("Nome");

        lblRG.setText("RG");

        lblEmail.setText("Email");

        lblTelefone.setText("Telefone");

        lblCPF.setText("CPF");

        lblVendedor_Responsável.setText("Vendedor Responsável");

        lblCelular.setText("Celular");

        try {
            ftxtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblData_Nascimento.setText("Data Nascimento");

        try {
            ftxtData_Nasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftxtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftxtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCPF.setText("");
        ftxtCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtCPFFocusLost(evt);
            }
        });

        try {
            ftxtRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblAsteristico.setText("*");

        lblAsteristico1.setText("*");

        lblAsteristico2.setText("*");

        lblAsteristico3.setText("*");

        lblAsteristico4.setText("*");

        lblAsteristico5.setText("*");

        cbxVendedorResp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbxVendedorResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxVendedorRespActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_ContatoLayout = new javax.swing.GroupLayout(Painel_Contato);
        Painel_Contato.setLayout(Painel_ContatoLayout);
        Painel_ContatoLayout.setHorizontalGroup(
            Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome)
                    .addComponent(lblRG)
                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                        .addComponent(ftxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAsteristico1))
                    .addComponent(lblEmail)
                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAsteristico, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAsteristico2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                .addComponent(lblTelefone)
                                .addGap(114, 114, 114)
                                .addComponent(lblCelular))
                            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCPF)
                                    .addComponent(ftxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAsteristico3))
                            .addComponent(lblVendedor_Responsável))
                        .addContainerGap())
                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbxVendedorResp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                .addComponent(ftxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ftxtCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(lblData_Nascimento)
                                    .addComponent(ftxtData_Nasc))))
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAsteristico5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_ContatoLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lblAsteristico4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        Painel_ContatoLayout.setVerticalGroup(
            Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblTelefone)
                    .addComponent(lblCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRG)
                    .addComponent(lblCPF)
                    .addComponent(lblData_Nascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtData_Nasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico1)
                    .addComponent(lblAsteristico3)
                    .addComponent(lblAsteristico5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(lblVendedor_Responsável))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAsteristico4)
                        .addComponent(cbxVendedorResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAsteristico2)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lblCódigo_Cliente.setText("Código Cliente:");

        Painel_Endereço.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        lblCidade.setText("Cidade");

        lblRua.setText("Rua");

        lblBairro.setText("Bairro");

        lblUF.setText("UF");

        lblNumero.setText("n°");

        lblCEP.setText("CEP");

        try {
            ftxtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblAsteristico6.setText("*");

        lblAsteristico7.setText("*");

        lblAsteristico8.setText("*");

        lblAsteristico9.setText("*");

        lblAsteristico11.setText("*");

        lblAsteristico12.setText("*");

        lblComplemento.setText("Complemento");

        cbx_Uf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        javax.swing.GroupLayout Painel_EndereçoLayout = new javax.swing.GroupLayout(Painel_Endereço);
        Painel_Endereço.setLayout(Painel_EndereçoLayout);
        Painel_EndereçoLayout.setHorizontalGroup(
            Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCidade)
                    .addComponent(txtCidade)
                    .addComponent(lblRua)
                    .addComponent(txtRua)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                                .addComponent(ftxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAsteristico9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx_Uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCEP)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAsteristico6)
                                    .addComponent(lblAsteristico7))
                                .addGap(123, 123, 123)
                                .addComponent(lblUF)
                                .addGap(47, 47, 47))
                            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                                .addComponent(lblAsteristico8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAsteristico11)
                    .addComponent(lblAsteristico12)))
            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComplemento)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Painel_EndereçoLayout.setVerticalGroup(
            Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(lblUF)
                    .addComponent(lblCEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico6)
                    .addComponent(lblAsteristico11)
                    .addComponent(cbx_Uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRua)
                    .addComponent(lblNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico7)
                    .addComponent(lblAsteristico12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBairro)
                .addGap(0, 0, 0)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblComplemento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        try {
            ftxtCodigoCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("PF######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCodigoCliente.setEnabled(false);

        javax.swing.GroupLayout Painel_Pessoa_FísicaLayout = new javax.swing.GroupLayout(Painel_Pessoa_Física);
        Painel_Pessoa_Física.setLayout(Painel_Pessoa_FísicaLayout);
        Painel_Pessoa_FísicaLayout.setHorizontalGroup(
            Painel_Pessoa_FísicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Pessoa_FísicaLayout.createSequentialGroup()
                .addComponent(lblCódigo_Cliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Painel_Pessoa_FísicaLayout.createSequentialGroup()
                .addGroup(Painel_Pessoa_FísicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Painel_Contato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Painel_Pessoa_FísicaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Painel_Endereço, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_Pessoa_FísicaLayout.createSequentialGroup()
                .addContainerGap(614, Short.MAX_VALUE)
                .addComponent(btnLimpar)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar)
                .addGap(78, 78, 78))
        );
        Painel_Pessoa_FísicaLayout.setVerticalGroup(
            Painel_Pessoa_FísicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Pessoa_FísicaLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(Painel_Pessoa_FísicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCódigo_Cliente)
                    .addComponent(ftxtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_Pessoa_FísicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Painel_Pessoa_FísicaLayout.createSequentialGroup()
                        .addComponent(Painel_Contato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVoltar))
                    .addComponent(Painel_Endereço, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(Painel_Pessoa_FísicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnCadastrar))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel_Pessoa_Física, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Painel_Pessoa_Física, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNome.requestFocus();

        txtNome.setText("");
        ftxtRG.setText("");
        ftxtCPF.setText("");
        ftxtData_Nasc.setText("");
        txtEmail.setText("");
        ftxtTelefone.setText("");
        ftxtCelular.setText("");

        cbxVendedorResp.setSelectedIndex(0);

        ftxtCEP.setText("");
        txtRua.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        txtCidade.setText("");
        cbx_Uf.setSelectedIndex(0);
        txtComplemento.setText("");

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String alerta = "";
        if (txtNome.getText().equals("")) {
            alerta = alerta + "Digite o nome do cliente!" + "\n";
        }
        if (ftxtRG.getText().replace("-", "").replace(".", "").replace(" ", "").equals("")) {
            alerta = alerta + "Digite o RG do cliente!" + "\n";
        }
        if (ftxtCPF.getText().replace(".", "").replace("-", "").replace(" ", "").equals("")) {
            alerta = alerta + "Digite o CPF do cliente!" + "\n";
        }
        if (txtEmail.getText().equals("")) {
            alerta = alerta + "Digite o e-mail do cliente!" + "\n";
        }
        if (ValidaEmail.validaEmail(txtEmail.getText()) == false) {
            alerta = alerta + "Digite um e-mail valido!" + "\n";
        }
        if (txtRua.getText().equals("")) {
            alerta = alerta + "Digite a rua do cliente!" + "\n";
        }
        if (txtNumero.getText().equals("")) {
            alerta = alerta + "Digite o numero do cliente!" + "\n";
        }
        if (txtBairro.getText().equals("")) {
            alerta = alerta + "Digite o bairro do cliente!" + "\n";
        }
        if (txtCidade.getText().equals("")) {
            alerta = alerta + "Digite a cidade do cliente!" + "\n";
        }
        if (ftxtCEP.getText().replace("-", "").replace(" ", "").equals("")) {
            alerta = alerta + "Digite o CEP do cliente!" + "\n";
        }
        if (ftxtData_Nasc.getText().replace("/", "").replace(" ", "").equals("")) {
            alerta = alerta + "Digite a data de nascimento do cliente!" + "\n";
        }
        if (!(alerta == "")) {
            JOptionPane.showMessageDialog(null, alerta);
            alerta = "";
        } else {
            if (JOptionPane.showConfirmDialog(null, "Confirma Cadastro?") == 0) {//Sim
                JOptionPane.showMessageDialog(null, "Cadastro Efetuado com sucesso!");
                pessoaFisica = new PessoaFisica(ftxtCodigoCliente.getText().replace(" ",""), txtNome.getText(),
                        txtEmail.getText(), txtRua.getText(), txtNumero.getText(), txtBairro.getText(),
                        txtCidade.getText(),(String)cbx_Uf.getSelectedItem(), ftxtCEP.getText().replace("-", ""),
                        "A");
                pessoaFisica.setCpf(ftxtCPF.getText().replace(".", "").replace("-", ""));
                pessoaFisica.setRg(ftxtRG.getText().replace("-", "").replace(".", ""));
                pessoaFisica.setTel(ftxtTelefone.getText().replace("(", "").replace(")", "").replace("-", ""));
                pessoaFisica.setCel(ftxtCelular.getText().replace("(", "").replace(")", "").replace("-", ""));
                pessoaFisica.setDtNasc(ftxtData_Nasc.getText().replace("/", ""));
                pessoaFisica.setComplemento(txtComplemento.getText());

                ArrayList<Vendedor> vendedores = daoVendedor.listarVendedores();
                vendedor = daoVendedor.consultar(vendedores.get(cbxVendedorResp.getSelectedIndex()).getCodigo());
                pessoaFisica.setVendedor_responsavel((String) cbxVendedorResp.getSelectedItem());
                pessoaFisica.setCod_vend_resp(vendedor.getCodigo());
                
                //cria o formatador de data
                SimpleDateFormat formatador = new SimpleDateFormat("ddMMyyyy");  
		 //cria um objeto date com a data do sistema
		Date dataDoSistema = new Date(System.currentTimeMillis());
		 //passa o objeto dataDoSistema para uma String da forma que pediu
		String dataEmTexto = formatador.format(dataDoSistema);  
                //passa o valor como string para o atributo
                pessoaFisica.setDtInicio(dataEmTexto);
                
                daoPfisica.inserir(pessoaFisica);

                int aux = parseInt(ftxtCodigoCliente.getText().replace("PF", "").replace(" ", ""));
                ftxtCodigoCliente.setText(String.valueOf(aux + 1));

                txtNome.requestFocus();

                txtNome.setText("");
                ftxtRG.setText("");
                ftxtCPF.setText("");
                ftxtData_Nasc.setText("");
                txtEmail.setText("");
                ftxtTelefone.setText("");
                ftxtCelular.setText("");

                cbxVendedorResp.setSelectedIndex(0);

                ftxtCEP.setText("");
                txtRua.setText("");
                txtNumero.setText("");
                txtBairro.setText("");
                txtCidade.setText("");
                cbx_Uf.setSelectedIndex(0);
                txtComplemento.setText("");
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao();
        conexao.setDriver();
        conexao.setConnectionString();
        daoPfisica = new DaoPFisica(conexao.conectar());
        daoVendedor = new DaoVendedor(conexao.conectar());
        daoDescobreCodigo = new DaoDescobreCodigo(conexao.conectar());

        ArrayList<Vendedor> vendedores = daoVendedor.listarVendedores();

        for (int x = 0; x < vendedores.size(); x++) {
            cbxVendedorResp.addItem(vendedores.get(x).getNome());
        }
        //descobrir e gerar codigo sequencial
        int aux = daoDescobreCodigo.consultarCodPF();
        if (aux == 0) {
            ftxtCodigoCliente.setText("1");
        } else {
            aux = aux + 1;
            ftxtCodigoCliente.setText(String.valueOf(aux));
        }

    }//GEN-LAST:event_formWindowOpened

    private void cbxVendedorRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxVendedorRespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxVendedorRespActionPerformed

    private void ftxtCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtCPFFocusLost
        if (ValidaCPF.validaCpf(ftxtCPF.getText().replace("-", "").replace(".", "").replace(" ", "")) == false) {
            ftxtCPF.setText("");
            JOptionPane.showMessageDialog(null, "Digite um CPF válido!");
        }
    }//GEN-LAST:event_ftxtCPFFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiCadastroPessoa_Física.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiCadastroPessoa_Física.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiCadastroPessoa_Física.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiCadastroPessoa_Física.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiCadastroPessoa_Física().setVisible(true);
            }
        });
    }

    private Conexao conexao = null;
    private DaoPFisica daoPfisica = null;
    private PessoaFisica pessoaFisica = null;
    private DaoVendedor daoVendedor = null;
    private Vendedor vendedor = null;
    private DaoDescobreCodigo daoDescobreCodigo = null;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_Contato;
    private javax.swing.JPanel Painel_Endereço;
    private javax.swing.JPanel Painel_Pessoa_Física;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbxVendedorResp;
    private javax.swing.JComboBox<String> cbx_Uf;
    private javax.swing.JFormattedTextField ftxtCEP;
    private javax.swing.JFormattedTextField ftxtCPF;
    private javax.swing.JFormattedTextField ftxtCelular;
    private javax.swing.JFormattedTextField ftxtCodigoCliente;
    private javax.swing.JFormattedTextField ftxtData_Nasc;
    private javax.swing.JFormattedTextField ftxtRG;
    private javax.swing.JFormattedTextField ftxtTelefone;
    private javax.swing.JLabel lblAsteristico;
    private javax.swing.JLabel lblAsteristico1;
    private javax.swing.JLabel lblAsteristico11;
    private javax.swing.JLabel lblAsteristico12;
    private javax.swing.JLabel lblAsteristico2;
    private javax.swing.JLabel lblAsteristico3;
    private javax.swing.JLabel lblAsteristico4;
    private javax.swing.JLabel lblAsteristico5;
    private javax.swing.JLabel lblAsteristico6;
    private javax.swing.JLabel lblAsteristico7;
    private javax.swing.JLabel lblAsteristico8;
    private javax.swing.JLabel lblAsteristico9;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblCódigo_Cliente;
    private javax.swing.JLabel lblData_Nascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUF;
    private javax.swing.JLabel lblVendedor_Responsável;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
