/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.vendas.view;

import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import projeto.vendas.control.Conexao;
import projeto.vendas.control.DaoLogin;
import projeto.vendas.control.DaoPFisica;
import projeto.vendas.control.DaoPJuridica;
import projeto.vendas.control.DaoVendedor;
import projeto.vendas.model.Login;
import projeto.vendas.model.PessoaFisica;
import projeto.vendas.model.PessoaJuridica;
import projeto.vendas.model.Vendedor;
import projeto.vendas.model.validacoes.ValidaCNPJ;
import projeto.vendas.model.validacoes.ValidaEmail;
import static projeto.vendas.model.validacoes.ValidaEmail.validaEmail;

/**
 *
 * @author Cleiton
 */
public class GuiCadastroPessoa_Jurídica extends javax.swing.JFrame {

    /**
     * Creates new form Pessoa_Jurídica
     */
    public GuiCadastroPessoa_Jurídica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Pessoa_Jurídica = new javax.swing.JPanel();
        Painel_Contato = new javax.swing.JPanel();
        lblNome_Fantasia = new javax.swing.JLabel();
        txtNome_Fantasia = new javax.swing.JTextField();
        txtAsteristico2 = new javax.swing.JFormattedTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtAsteristico5 = new javax.swing.JFormattedTextField();
        lblTelefone = new javax.swing.JLabel();
        lblCNPJ = new javax.swing.JLabel();
        txtAsteristico6 = new javax.swing.JFormattedTextField();
        lblVendedor_Responsável = new javax.swing.JLabel();
        ftxtTelefone = new javax.swing.JFormattedTextField();
        ftxtCNPJ = new javax.swing.JFormattedTextField();
        lblAsteristico = new javax.swing.JLabel();
        lblAsteristico1 = new javax.swing.JLabel();
        lblAsteristico2 = new javax.swing.JLabel();
        lblAsteristico3 = new javax.swing.JLabel();
        lblAsteristico4 = new javax.swing.JLabel();
        cbxVendedorResp = new javax.swing.JComboBox<>();
        lblCódigo_Cliente = new javax.swing.JLabel();
        txtCodigo_Cliente = new javax.swing.JTextField();
        Painel_Endereço = new javax.swing.JPanel();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblRua = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblUF = new javax.swing.JLabel();
        txtUF = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblCEP = new javax.swing.JLabel();
        lblLatitude = new javax.swing.JLabel();
        txtLatitude = new javax.swing.JTextField();
        lblLongitude = new javax.swing.JLabel();
        txtLongitude = new javax.swing.JTextField();
        ftxtCEP = new javax.swing.JFormattedTextField();
        lblAsteristico5 = new javax.swing.JLabel();
        lblAsteristico6 = new javax.swing.JLabel();
        lblAsteristico7 = new javax.swing.JLabel();
        lblAsteristico8 = new javax.swing.JLabel();
        lblAsteristico9 = new javax.swing.JLabel();
        lblAsteristico10 = new javax.swing.JLabel();
        lblAsteristico11 = new javax.swing.JLabel();
        lblAsteristico12 = new javax.swing.JLabel();
        btnBuscar_Coordenadas = new javax.swing.JButton();
        lblComplemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Cliente Pessoa Jurídica");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Painel_Pessoa_Jurídica.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoa Jurídica"));

        Painel_Contato.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));

        lblNome_Fantasia.setText("Nome Fantasia");

        txtAsteristico2.setEditable(false);
        txtAsteristico2.setBorder(null);

        lblEmail.setText("Email");

        txtAsteristico5.setEditable(false);
        txtAsteristico5.setBorder(null);

        lblTelefone.setText("Telefone");

        lblCNPJ.setText("CNPJ");

        txtAsteristico6.setEditable(false);
        txtAsteristico6.setBorder(null);

        lblVendedor_Responsável.setText("Vendedor Responsável");

        try {
            ftxtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftxtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCNPJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtCNPJFocusLost(evt);
            }
        });

        lblAsteristico.setText("*");

        lblAsteristico1.setText("*");

        lblAsteristico2.setText("*");

        lblAsteristico3.setText("*");

        lblAsteristico4.setText("*");

        javax.swing.GroupLayout Painel_ContatoLayout = new javax.swing.GroupLayout(Painel_Contato);
        Painel_Contato.setLayout(Painel_ContatoLayout);
        Painel_ContatoLayout.setHorizontalGroup(
            Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                        .addComponent(txtNome_Fantasia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                        .addComponent(cbxVendedorResp, 0, 140, Short.MAX_VALUE)
                                        .addGap(4, 4, 4)))
                                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                        .addComponent(lblAsteristico2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAsteristico5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                        .addComponent(lblAsteristico)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAsteristico2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblNome_Fantasia)
                            .addComponent(lblEmail)
                            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAsteristico1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                .addComponent(ftxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAsteristico3))
                            .addComponent(lblTelefone)
                            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCNPJ)
                                    .addComponent(ftxtCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAsteristico4)
                                .addGap(33, 33, 33)
                                .addComponent(txtAsteristico6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblVendedor_Responsável))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel_ContatoLayout.setVerticalGroup(
            Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_ContatoLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome_Fantasia)
                    .addComponent(lblTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome_Fantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAsteristico2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico)
                    .addComponent(lblAsteristico3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCNPJ)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAsteristico6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico1)
                    .addComponent(lblAsteristico4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVendedor_Responsável)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Painel_ContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAsteristico5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico2)
                    .addComponent(cbxVendedorResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCódigo_Cliente.setText("Código Cliente:");

        txtCodigo_Cliente.setBackground(new java.awt.Color(240, 240, 240));
        txtCodigo_Cliente.setText("PJ");
        txtCodigo_Cliente.setBorder(null);
        txtCodigo_Cliente.setEnabled(false);

        Painel_Endereço.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        lblCidade.setText("Cidade");

        lblRua.setText("Rua");

        lblBairro.setText("Bairro");

        lblUF.setText("UF");

        lblNumero.setText("n°");

        lblCEP.setText("CEP");

        lblLatitude.setText("Latitude");

        lblLongitude.setText("Longitude");

        try {
            ftxtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblAsteristico5.setText("*");

        lblAsteristico6.setText("*");

        lblAsteristico7.setText("*");

        lblAsteristico8.setText("*");

        lblAsteristico9.setText("*");

        lblAsteristico10.setText("*");

        lblAsteristico11.setText("*");

        lblAsteristico12.setText("*");

        btnBuscar_Coordenadas.setText("Buscar Coordenadas");

        lblComplemento.setText("Complemento");

        javax.swing.GroupLayout Painel_EndereçoLayout = new javax.swing.GroupLayout(Painel_Endereço);
        Painel_Endereço.setLayout(Painel_EndereçoLayout);
        Painel_EndereçoLayout.setHorizontalGroup(
            Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCidade)
                    .addComponent(txtCidade)
                    .addComponent(lblRua)
                    .addComponent(txtRua)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAsteristico5)
                    .addComponent(lblAsteristico6)
                    .addComponent(lblAsteristico7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                        .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUF)
                            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLongitude)
                                    .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblNumero)
                                        .addComponent(txtUF, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                        .addComponent(txtNumero)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAsteristico8)
                                    .addComponent(lblAsteristico9))))
                        .addGap(18, 18, 18)
                        .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCEP)
                            .addComponent(lblLatitude)
                            .addComponent(txtLatitude)
                            .addComponent(ftxtCEP, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAsteristico10)
                            .addComponent(lblAsteristico11)))
                    .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(lblAsteristico12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar_Coordenadas)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblComplemento)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel_EndereçoLayout.setVerticalGroup(
            Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_EndereçoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(lblUF)
                    .addComponent(lblCEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico5)
                    .addComponent(lblAsteristico8)
                    .addComponent(lblAsteristico10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLatitude, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRua)
                        .addComponent(lblNumero)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico6)
                    .addComponent(lblAsteristico9)
                    .addComponent(lblAsteristico11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro)
                    .addComponent(lblLongitude))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico7)
                    .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAsteristico12)
                    .addComponent(btnBuscar_Coordenadas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComplemento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_Pessoa_JurídicaLayout = new javax.swing.GroupLayout(Painel_Pessoa_Jurídica);
        Painel_Pessoa_Jurídica.setLayout(Painel_Pessoa_JurídicaLayout);
        Painel_Pessoa_JurídicaLayout.setHorizontalGroup(
            Painel_Pessoa_JurídicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Pessoa_JurídicaLayout.createSequentialGroup()
                .addComponent(Painel_Contato, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Painel_Endereço, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Painel_Pessoa_JurídicaLayout.createSequentialGroup()
                .addComponent(lblCódigo_Cliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigo_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Painel_Pessoa_JurídicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpar)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar)
                .addGap(79, 79, 79))
        );
        Painel_Pessoa_JurídicaLayout.setVerticalGroup(
            Painel_Pessoa_JurídicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_Pessoa_JurídicaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Painel_Pessoa_JurídicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCódigo_Cliente)
                    .addComponent(txtCodigo_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_Pessoa_JurídicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Painel_Endereço, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Painel_Contato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_Pessoa_JurídicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnLimpar)
                    .addComponent(btnCadastrar))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel_Pessoa_Jurídica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Painel_Pessoa_Jurídica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao();
        conexao.setDriver();
        conexao.setConnectionString();
        daoPJuridica = new DaoPJuridica(conexao.conectar());
        daoVendedor = new DaoVendedor(conexao.conectar());
        
        
         ArrayList<Vendedor> vendedores = daoVendedor.listarVendedores();               
        
        for (int x=0; x<vendedores.size(); x++){
           cbxVendedorResp.addItem(vendedores.get(x).getNome()); 
        }

    }//GEN-LAST:event_formWindowOpened

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String alerta = "";
        if(txtNome_Fantasia.getText().equals("")){
            alerta = alerta + "Digite o nome fantasia da empresa!" + "\n";
        }
        if(ftxtCNPJ.getText().replace("-","").replace(".","").replace(" ","").replace("/","").equals("")){
            alerta = alerta + "Digite o CNPJ!" + "\n";
        }
        if(txtEmail.getText().equals("")){
            alerta = alerta + "Digite o e-mail do cliente!" + "\n";        
        }
        if(ValidaEmail.validaEmail(txtEmail.getText())== false){
            alerta = alerta + "Digite um e-mail valido!" + "\n";
        }
        if(txtRua.getText().equals("")){
            alerta = alerta + "Digite a rua do cliente!" + "\n";
        }
        if(txtNumero.getText().equals("")){
            alerta = alerta + "Digite o numero do cliente!" + "\n";
        }
        if(txtBairro.getText().equals("")){
            alerta = alerta + "Digite o bairro do cliente!" + "\n";
        }
        if(txtUF.getText().equals("")){
            alerta = alerta + "Digite a unidade federativa do cliente!" + "\n";
        }
        if(txtCidade.getText().equals("")){
            alerta = alerta + "Digite a cidade do cliente!" + "\n";
        }
        if(ftxtCEP.getText().replace("-","").replace(" ","").equals("")){
            alerta = alerta + "Digite o CEP do cliente!" + "\n";
        }
        
        if(txtLatitude.getText().equals("")){
            alerta = alerta + "Digite a latitude do cliente!" + "\n";
        }
        if(txtLongitude.getText().equals("")){
            alerta = alerta + "Digite a longitude do cliente!" + "\n";
        }
        if(!(alerta == "")){
            JOptionPane.showMessageDialog(null,alerta);
            alerta = "";
        }
        else{
            pessoaJuridica = new PessoaJuridica (txtCodigo_Cliente.getText(),txtNome_Fantasia.getText(),
                                            txtEmail.getText(),txtRua.getText(),txtNumero.getText(),txtBairro.getText(),
                                            txtCidade.getText(),txtUF.getText(),ftxtCEP.getText().replace("-",""),
                                            parseDouble(txtLatitude.getText()),
                                            parseDouble(txtLongitude.getText()),"A");
            pessoaJuridica.setCnpj(ftxtCNPJ.getText().replace(".","").replace("-","").replace("/",""));
            pessoaJuridica.setTel(ftxtTelefone.getText().replace("(","").replace(")","").replace("-",""));
            pessoaJuridica.setComplemento(txtComplemento.getText());
            
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void ftxtCNPJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtCNPJFocusLost
        if(ValidaCNPJ.validaCnpj(ftxtCNPJ.getText().replace("-","").replace(".","")
                                 .replace(" ","").replace("/","")) == false){
            ftxtCNPJ.setText("");
            JOptionPane.showMessageDialog(null,"Digite um CPF válido!");  
        }
    }//GEN-LAST:event_ftxtCNPJFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiCadastroPessoa_Jurídica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiCadastroPessoa_Jurídica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiCadastroPessoa_Jurídica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiCadastroPessoa_Jurídica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiCadastroPessoa_Jurídica().setVisible(true);
            }
        });
    }
    
    private Conexao conexao=null;;
    private PessoaJuridica pessoaJuridica=null;
    private DaoVendedor daoVendedor= null;
    private DaoPJuridica daoPJuridica = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_Contato;
    private javax.swing.JPanel Painel_Endereço;
    private javax.swing.JPanel Painel_Pessoa_Jurídica;
    private javax.swing.JButton btnBuscar_Coordenadas;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbxVendedorResp;
    private javax.swing.JFormattedTextField ftxtCEP;
    private javax.swing.JFormattedTextField ftxtCNPJ;
    private javax.swing.JFormattedTextField ftxtTelefone;
    private javax.swing.JLabel lblAsteristico;
    private javax.swing.JLabel lblAsteristico1;
    private javax.swing.JLabel lblAsteristico10;
    private javax.swing.JLabel lblAsteristico11;
    private javax.swing.JLabel lblAsteristico12;
    private javax.swing.JLabel lblAsteristico2;
    private javax.swing.JLabel lblAsteristico3;
    private javax.swing.JLabel lblAsteristico4;
    private javax.swing.JLabel lblAsteristico5;
    private javax.swing.JLabel lblAsteristico6;
    private javax.swing.JLabel lblAsteristico7;
    private javax.swing.JLabel lblAsteristico8;
    private javax.swing.JLabel lblAsteristico9;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblCódigo_Cliente;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLatitude;
    private javax.swing.JLabel lblLongitude;
    private javax.swing.JLabel lblNome_Fantasia;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUF;
    private javax.swing.JLabel lblVendedor_Responsável;
    private javax.swing.JFormattedTextField txtAsteristico2;
    private javax.swing.JFormattedTextField txtAsteristico5;
    private javax.swing.JFormattedTextField txtAsteristico6;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigo_Cliente;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLatitude;
    private javax.swing.JTextField txtLongitude;
    private javax.swing.JTextField txtNome_Fantasia;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtUF;
    // End of variables declaration//GEN-END:variables
}
