/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.vendas.view;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.text.NumberFormat;
import java.net.URL;
import java.sql.Connection;
import java.sql.Date;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.thrift.server.THsHaServer;
import projeto.vendas.control.Conexao;
import projeto.vendas.control.DaoEmitirNotaFiscal;
import projeto.vendas.control.DaoGerarPedido;
import projeto.vendas.control.DaoPFisica;
import projeto.vendas.control.DaoPJuridica;
import projeto.vendas.control.DaoPedidoProduto;
import projeto.vendas.control.DaoProduto;
import projeto.vendas.control.DaoVendedor;
import projeto.vendas.model.Login;
import projeto.vendas.model.NotaFiscal;
import projeto.vendas.model.Pedido;
import projeto.vendas.model.PessoaFisica;
import projeto.vendas.model.PessoaJuridica;
import projeto.vendas.model.Vendedor;
import projeto.vendas.tabelas.GuiControleEstrategicoVendedorEspecificoTVVendas;

/**
 *
 * @author 0030481521038
 */
public class GuiControle_Estratégico_por_Vendedor_Especifico extends javax.swing.JFrame {

    /**
     * Creates new form GuiControle_Estratégico_por_Vendedor
     */
    public GuiControle_Estratégico_por_Vendedor_Especifico(Login login, int codigo, ArrayList<NotaFiscal> Lista) {
        initComponents();

        this.login = login;
        this.codigo = codigo;
        this.ListarNotaFiscal = Lista;

        GuiControle_Estratégico_por_Vendedor_Especifico.this.setTitle(
                "Controle Estratégico por Vendedor    " + "Usuário:  " + login.getNome()
                + "         " + "Codigo:  " + login.getCodigo());

        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();

        DefaultTableModel modelo1 = (DefaultTableModel) tblVendas.getModel();

        tblClientes.setRowSorter(new TableRowSorter(modelo));
        tblVendas.setRowSorter(new TableRowSorter(modelo1));

        URL caminhoIcone = getClass().getResource("/projeto/vendas/model/icones/logotipo.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupVendedor = new javax.swing.ButtonGroup();
        Controle_Estratégico_Vendedor = new javax.swing.JPanel();
        btnFiltrarData = new javax.swing.JButton();
        jPanelVendedor = new javax.swing.JPanel();
        Painel_Vendas = new javax.swing.JTabbedPane();
        Painel_Dados = new javax.swing.JPanel();
        jPanelDados = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtFuncao = new javax.swing.JTextField();
        lblFuncao = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        ftxtTelefone = new javax.swing.JFormattedTextField();
        ftxtCelular = new javax.swing.JFormattedTextField();
        lblNome1 = new javax.swing.JLabel();
        ftxtDtNasc = new javax.swing.JFormattedTextField();
        ftxtCPF = new javax.swing.JFormattedTextField();
        ftxtRG = new javax.swing.JFormattedTextField();
        lblRG = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblCodigo1 = new javax.swing.JLabel();
        txtSituacao = new javax.swing.JTextField();
        lblNome2 = new javax.swing.JLabel();
        ftxtDtcadastro = new javax.swing.JFormattedTextField();
        Endereço = new javax.swing.JPanel();
        lblRua = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        lblCEP = new javax.swing.JLabel();
        cbxUF = new javax.swing.JComboBox<>();
        ftxtCEP = new javax.swing.JFormattedTextField();
        btnVisualizarVendedor = new javax.swing.JButton();
        txtComplemento = new javax.swing.JTextField();
        lblCidade1 = new javax.swing.JLabel();
        Painel_VendasFeitas = new javax.swing.JPanel();
        jScrollPaneVendedor = new javax.swing.JScrollPane();
        tblVendas = new javax.swing.JTable();
        btnVisualizarVendas = new javax.swing.JButton();
        Painel_Clientes = new javax.swing.JPanel();
        jScrollPaneVendedor1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnVisualizarCliente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblValorTotalVendas = new javax.swing.JLabel();
        txtValorTotalVendas = new javax.swing.JTextField();
        lblQtdeVendas = new javax.swing.JLabel();
        txtQtdeVendas = new javax.swing.JTextField();
        lblClienteInativo1 = new javax.swing.JLabel();
        txtTotalClientes = new javax.swing.JTextField();
        txtClientesAtivos = new javax.swing.JTextField();
        lblClienteAtivo = new javax.swing.JLabel();
        lblClienteInativo = new javax.swing.JLabel();
        txtClientesInativos = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        lblData_Inicial = new javax.swing.JLabel();
        ftxtData_Inicial = new javax.swing.JFormattedTextField();
        lblData_Final = new javax.swing.JLabel();
        ftxtData_Final = new javax.swing.JFormattedTextField();
        lblControle_Estrategico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle Estratégico Vendedor");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnFiltrarData.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnFiltrarData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Filtrar.png"))); // NOI18N
        btnFiltrarData.setText("Filtrar por data");
        btnFiltrarData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarDataActionPerformed(evt);
            }
        });

        Painel_Vendas.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N

        jPanelDados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        lblNome.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblNome.setText("Nome");

        lblCodigo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCodigo.setText("Codigo");

        lblFuncao.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblFuncao.setText("Função");

        lblTelefone.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblTelefone.setText("Telefone");

        lblEmail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmail.setText("Email");

        lblCelular.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCelular.setText("Celular");

        try {
            ftxtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtTelefone.setText("");
        ftxtTelefone.setEnabled(false);

        try {
            ftxtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCelular.setText("");
        ftxtCelular.setEnabled(false);

        lblNome1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblNome1.setText("Data de Nasc:");

        try {
            ftxtDtNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtDtNasc.setText("");

        try {
            ftxtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCPF.setText("");
        ftxtCPF.setEnabled(false);

        try {
            ftxtRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtRG.setText("");
        ftxtRG.setEnabled(false);

        lblRG.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblRG.setText("RG");

        lblCPF.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCPF.setText("CPF");

        lblCodigo1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCodigo1.setText("Situação");

        lblNome2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblNome2.setText("Data do Cadastro:");

        try {
            ftxtDtcadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtDtcadastro.setText("");

        javax.swing.GroupLayout jPanelDadosLayout = new javax.swing.GroupLayout(jPanelDados);
        jPanelDados.setLayout(jPanelDadosLayout);
        jPanelDadosLayout.setHorizontalGroup(
            jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosLayout.createSequentialGroup()
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFuncao)
                    .addGroup(jPanelDadosLayout.createSequentialGroup()
                        .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNome)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDadosLayout.createSequentialGroup()
                                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodigo))
                                .addGap(42, 42, 42)
                                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelefone)
                                    .addComponent(ftxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ftxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCelular)))
                            .addComponent(txtFuncao, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(ftxtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDadosLayout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(313, 313, 313)
                        .addComponent(lblNome1))
                    .addGroup(jPanelDadosLayout.createSequentialGroup()
                        .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDadosLayout.createSequentialGroup()
                                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail)
                                    .addComponent(lblRG, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(128, 128, 128)
                                .addComponent(lblCPF))
                            .addGroup(jPanelDadosLayout.createSequentialGroup()
                                .addComponent(ftxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ftxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigo1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftxtDtcadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome2)))
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelDadosLayout.setVerticalGroup(
            jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosLayout.createSequentialGroup()
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblNome1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(lblTelefone)
                    .addComponent(lblCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFuncao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(txtFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelDadosLayout.createSequentialGroup()
                            .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCPF)
                                .addComponent(lblRG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ftxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ftxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosLayout.createSequentialGroup()
                            .addComponent(lblNome2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ftxtDtcadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDadosLayout.createSequentialGroup()
                        .addComponent(lblCodigo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Endereço.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 12))); // NOI18N

        lblRua.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblRua.setText("Rua");

        lblNumero.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblNumero.setText("Numero");

        lblBairro.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblBairro.setText("Bairro");

        lblCidade.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCidade.setText("Cidade");

        lblEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEstado.setText("Estado");

        lblCEP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCEP.setText("CEP");

        cbxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        try {
            ftxtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnVisualizarVendedor.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnVisualizarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Visualizar.png"))); // NOI18N
        btnVisualizarVendedor.setText("Visualizar Vendedor");
        btnVisualizarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarVendedorActionPerformed(evt);
            }
        });

        lblCidade1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCidade1.setText("Complemento:");

        javax.swing.GroupLayout EndereçoLayout = new javax.swing.GroupLayout(Endereço);
        Endereço.setLayout(EndereçoLayout);
        EndereçoLayout.setHorizontalGroup(
            EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EndereçoLayout.createSequentialGroup()
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EndereçoLayout.createSequentialGroup()
                        .addComponent(cbxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtComplemento))
                    .addGroup(EndereçoLayout.createSequentialGroup()
                        .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EndereçoLayout.createSequentialGroup()
                                .addComponent(lblEstado)
                                .addGap(18, 18, 18)
                                .addComponent(lblCidade1))
                            .addGroup(EndereçoLayout.createSequentialGroup()
                                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRua)
                                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNumero)))
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBairro)
                            .addGroup(EndereçoLayout.createSequentialGroup()
                                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCidade))
                                .addGap(18, 18, 18)
                                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCEP)
                                    .addComponent(ftxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EndereçoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVisualizarVendedor))
        );
        EndereçoLayout.setVerticalGroup(
            EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EndereçoLayout.createSequentialGroup()
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRua)
                    .addComponent(lblNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBairro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(lblCEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(lblCidade1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EndereçoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVisualizarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout Painel_DadosLayout = new javax.swing.GroupLayout(Painel_Dados);
        Painel_Dados.setLayout(Painel_DadosLayout);
        Painel_DadosLayout.setHorizontalGroup(
            Painel_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_DadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Endereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel_DadosLayout.setVerticalGroup(
            Painel_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_DadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_DadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Endereço, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Painel_Vendas.addTab("Dados", Painel_Dados);

        tblVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Cliente", "Nome Cliente", "Nota Fiscal", "Valor da Nota", "data de Emissão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneVendedor.setViewportView(tblVendas);

        btnVisualizarVendas.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnVisualizarVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Visualizar.png"))); // NOI18N
        btnVisualizarVendas.setText("Visualizar Vendas");
        btnVisualizarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarVendasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_VendasFeitasLayout = new javax.swing.GroupLayout(Painel_VendasFeitas);
        Painel_VendasFeitas.setLayout(Painel_VendasFeitasLayout);
        Painel_VendasFeitasLayout.setHorizontalGroup(
            Painel_VendasFeitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
            .addGroup(Painel_VendasFeitasLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(btnVisualizarVendas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel_VendasFeitasLayout.setVerticalGroup(
            Painel_VendasFeitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_VendasFeitasLayout.createSequentialGroup()
                .addComponent(jScrollPaneVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVisualizarVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        Painel_Vendas.addTab("Vendas", Painel_VendasFeitas);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "Ativo/Inativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneVendedor1.setViewportView(tblClientes);

        btnVisualizarCliente.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnVisualizarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Visualizar.png"))); // NOI18N
        btnVisualizarCliente.setText("Visualizar Cliente");
        btnVisualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_ClientesLayout = new javax.swing.GroupLayout(Painel_Clientes);
        Painel_Clientes.setLayout(Painel_ClientesLayout);
        Painel_ClientesLayout.setHorizontalGroup(
            Painel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneVendedor1, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
            .addGroup(Painel_ClientesLayout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(btnVisualizarCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel_ClientesLayout.setVerticalGroup(
            Painel_ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_ClientesLayout.createSequentialGroup()
                .addComponent(jScrollPaneVendedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVisualizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        Painel_Vendas.addTab("Clientes", Painel_Clientes);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumo"));

        lblValorTotalVendas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblValorTotalVendas.setText("Valor total das Vendas");

        lblQtdeVendas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblQtdeVendas.setText("Quantidade de Vendas");

        lblClienteInativo1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblClienteInativo1.setText("Responsavel por:");

        lblClienteAtivo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblClienteAtivo.setText("Clientes Ativos");

        lblClienteInativo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblClienteInativo.setText("Clientes Inativos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQtdeVendas)
                    .addComponent(txtQtdeVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClienteInativo1)
                    .addComponent(lblClienteAtivo)
                    .addComponent(txtClientesAtivos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClienteInativo)
                    .addComponent(txtClientesInativos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtValorTotalVendas, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblValorTotalVendas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblQtdeVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtQtdeVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValorTotalVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorTotalVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClienteInativo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClienteAtivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClientesAtivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblClienteInativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClientesInativos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelVendedorLayout = new javax.swing.GroupLayout(jPanelVendedor);
        jPanelVendedor.setLayout(jPanelVendedorLayout);
        jPanelVendedorLayout.setHorizontalGroup(
            jPanelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendedorLayout.createSequentialGroup()
                .addComponent(Painel_Vendas, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVendedorLayout.setVerticalGroup(
            jPanelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Painel_Vendas)
                    .addGroup(jPanelVendedorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        btnVoltar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Voltar.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblData_Inicial.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblData_Inicial.setText("Data Inicial");

        try {
            ftxtData_Inicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtData_Inicial.setText("01012000");

        lblData_Final.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblData_Final.setText("Data Final");

        try {
            ftxtData_Final.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtData_Final.setText("");

        javax.swing.GroupLayout Controle_Estratégico_VendedorLayout = new javax.swing.GroupLayout(Controle_Estratégico_Vendedor);
        Controle_Estratégico_Vendedor.setLayout(Controle_Estratégico_VendedorLayout);
        Controle_Estratégico_VendedorLayout.setHorizontalGroup(
            Controle_Estratégico_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Controle_Estratégico_VendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Controle_Estratégico_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Controle_Estratégico_VendedorLayout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Controle_Estratégico_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblData_Inicial)
                            .addComponent(ftxtData_Inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(Controle_Estratégico_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblData_Final)
                            .addGroup(Controle_Estratégico_VendedorLayout.createSequentialGroup()
                                .addComponent(ftxtData_Final, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFiltrarData)))
                        .addGap(399, 399, 399))
                    .addGroup(Controle_Estratégico_VendedorLayout.createSequentialGroup()
                        .addComponent(jPanelVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Controle_Estratégico_VendedorLayout.setVerticalGroup(
            Controle_Estratégico_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Controle_Estratégico_VendedorLayout.createSequentialGroup()
                .addComponent(jPanelVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(Controle_Estratégico_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData_Inicial)
                    .addComponent(lblData_Final))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Controle_Estratégico_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtData_Inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtData_Final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrarData, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblControle_Estrategico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Controle estrategico.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(lblControle_Estrategico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Controle_Estratégico_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Controle_Estratégico_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblControle_Estrategico, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao();
        conexao.setDriver();
        conexao.setConnectionString();

        daoPFisica = new DaoPFisica(conexao.conectar());
        daoPJrudica = new DaoPJuridica(conexao.conectar());
        daoVendedor = new DaoVendedor(conexao.conectar());
        daoGerarPedido = new DaoGerarPedido(conexao.conectar());

        SimpleDateFormat formatador = new SimpleDateFormat("ddMMyyyy");
        Date dataDoSistema = new Date(System.currentTimeMillis());
        String dataEmTexto = formatador.format(dataDoSistema);
        ftxtData_Final.setText(dataEmTexto);

        vendedor = daoVendedor.consultarTbVend(codigo);
        preencherTela(vendedor);

        ArrayList<PessoaFisica> clientesPF = daoPFisica.ListarPFPorCodVend(codigo);
        ArrayList<PessoaJuridica> clientesPJ = daoPJrudica.ListarPJPorCodVend(codigo);

        preencherTblClientes(clientesPF, clientesPJ);

        preencherTblVendas(ListarNotaFiscal, vendedor);

        double valorTotal = 0;
        for (int i = 0; i < tblVendas.getRowCount(); i++) {
            
            //gambi
            String a = (String) model.getValueAt(i, 3);
            a = a.replace(",", ".");
            double var = Double.parseDouble(a);
            valorTotal = valorTotal + var;
        }
        txtTotalClientes.setText(String.valueOf(tblClientes.getRowCount()));
        txtQtdeVendas.setText(String.valueOf(tblVendas.getRowCount()));

        NumberFormat calculo;
        calculo = NumberFormat.getInstance();
        calculo.setMinimumFractionDigits(2);
        txtValorTotalVendas.setText("R$ " + calculo.format(valorTotal) + " Reais");

    }//GEN-LAST:event_formWindowOpened

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnVisualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarClienteActionPerformed
        String codCli = "";
        Map parameters = new HashMap();
        if (tblClientes.getSelectedRow() >= 0) {
            codCli = (String) tblClientes.getValueAt(tblClientes.getSelectedRow(), 0);
            if (codCli.substring(0, 2).equals("PF")) {
                try {
                    parameters.put("codigo", (String) tblClientes.getValueAt(tblClientes.getSelectedRow(), 0));
                    JasperPrint jpPrint;
                    jpPrint = JasperFillManager.fillReport("relatorios/EspelhoClientePF.jasper",
                            parameters, conexao.conectar());

                    JasperViewer jv = new JasperViewer(jpPrint, false);
                    jv.setVisible(true);

                } catch (JRException ex) {
                    Logger.getLogger(GuiControle_Estratégico_por_Vendedor_Especifico.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    parameters.put("codigo", (String) tblClientes.getValueAt(tblClientes.getSelectedRow(), 0));
                    JasperPrint jpPrint;
                    jpPrint = JasperFillManager.fillReport("relatorios/EspelhoClientePJ.jasper",
                            parameters, conexao.conectar());

                    JasperViewer jv = new JasperViewer(jpPrint, false);
                    jv.setVisible(true);

                } catch (JRException ex) {
                    Logger.getLogger(GuiControle_Estratégico_por_Vendedor_Especifico.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Escolha um cliente!");
        }
    }//GEN-LAST:event_btnVisualizarClienteActionPerformed

    private void btnFiltrarDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarDataActionPerformed
        preencherTela(vendedor);

        preencherTblVendas(ListarNotaFiscal, vendedor);

        double valorTotal = 0;
        for (int i = 0; i < tblVendas.getRowCount(); i++) {
            valorTotal = valorTotal + (double) model.getValueAt(i, 3);
        }
        txtTotalClientes.setText(String.valueOf(tblClientes.getRowCount()));
        txtQtdeVendas.setText(String.valueOf(tblVendas.getRowCount()));
        txtValorTotalVendas.setText(String.valueOf(valorTotal));
    }//GEN-LAST:event_btnFiltrarDataActionPerformed

    private void btnVisualizarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarVendedorActionPerformed
        Map parameters1 = new HashMap();

        try {
            parameters1.put("codigo", txtCodigo.getText());
            parameters1.put("nome", txtNome.getText());
            parameters1.put("telefone", ftxtTelefone.getText());
            parameters1.put("celular", ftxtCelular.getText());
            parameters1.put("funcao", txtFuncao.getText());
            parameters1.put("email", txtEmail.getText());
            parameters1.put("rua", txtRua.getText());
            parameters1.put("numero", txtNumero.getText());
            parameters1.put("bairro", txtBairro.getText());
            parameters1.put("cidade", txtCidade.getText());
            parameters1.put("cep", ftxtCEP.getText());
            parameters1.put("uf", (String) cbxUF.getSelectedItem());
            parameters1.put("complemento", txtComplemento.getText());
            parameters1.put("dtnasc", ftxtDtNasc.getText());
            parameters1.put("cpf", ftxtCPF.getText());
            parameters1.put("rg", ftxtDtNasc.getText());
            parameters1.put("dtcadastro", ftxtDtcadastro.getText());
            parameters1.put("ativo", txtSituacao.getText());

            parameters1.put("qtdA", txtClientesAtivos.getText());
            parameters1.put("qtdI", txtClientesInativos.getText());
            parameters1.put("qtdV", txtQtdeVendas.getText());
            parameters1.put("qtdC", txtTotalClientes.getText());
            parameters1.put("valortotal", txtValorTotalVendas.getText());
            parameters1.put("dtI", ftxtData_Inicial.getText());
            parameters1.put("dtF", ftxtData_Final.getText());

            JasperPrint jpPrint1;
            jpPrint1 = JasperFillManager.fillReport("relatorios/EspelhoVendedor.jasper",
                    parameters1, conexao.conectar());

            JasperViewer jv1 = new JasperViewer(jpPrint1, false);
            jv1.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(GuiControle_Estratégico_por_Vendedor_Especifico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVisualizarVendedorActionPerformed

    private void btnVisualizarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarVendasActionPerformed
        Map parameters1 = new HashMap();

        List lista = new ArrayList();
        for (int x = 0; x < tblVendas.getRowCount(); x++) {
            
            //gambi
            String a = (String) tblVendas.getValueAt(x, 3);
            a = a.replace(",", ".");
            double var = Double.parseDouble(a);
            
            GuiControleEstrategicoVendedorEspecificoTVVendas print
                    = new GuiControleEstrategicoVendedorEspecificoTVVendas();

            print.setCodCli((String) tblVendas.getValueAt(x, 0));
            print.setNomeCli((String) tblVendas.getValueAt(x, 1));
            print.setNotaFiscal((int) tblVendas.getValueAt(x, 2));
            print.setValorNota(var);
            print.setDtEmissao((String) tblVendas.getValueAt(x, 4));

            lista.add(print);
        }

        try {
            parameters1.put("codigo", txtCodigo.getText());
            parameters1.put("nome", txtNome.getText());
            parameters1.put("funcao", txtFuncao.getText());
            parameters1.put("dtinicio", ftxtData_Inicial.getText());
            parameters1.put("dtfinal", ftxtData_Inicial.getText());

            JRBeanCollectionDataSource ds = new JRBeanCollectionDataSource(lista);

            JasperPrint jpPrint1;
            jpPrint1 = JasperFillManager.fillReport("relatorios/RelatorioVendedorVendas.jasper",
                    parameters1, ds);

            JasperViewer jv1 = new JasperViewer(jpPrint1, false);
            jv1.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(GuiControle_Estratégico_por_Vendedor_Especifico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVisualizarVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiControle_Estratégico_por_Vendedor_Especifico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiControle_Estratégico_por_Vendedor_Especifico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiControle_Estratégico_por_Vendedor_Especifico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiControle_Estratégico_por_Vendedor_Especifico.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiControle_Estratégico_por_Vendedor_Especifico(login, codigo, ListarNotaFiscal).setVisible(true);
            }
        });
    }
    private DecimalFormat formatador = new DecimalFormat("0.00");
    private int flagLimpaTabela1 = 0;
    private int flagLimpaTabela = 0;
    private static ArrayList<NotaFiscal> ListarNotaFiscal;
    private static int codigo;
    private Conexao conexao;
    private Vendedor vendedor = null;
    private DaoVendedor daoVendedor = null;
    private DaoPFisica daoPFisica = null;
    private DaoPJuridica daoPJrudica = null;
    private PessoaFisica pessoaFisica = null;
    private PessoaJuridica pessoaJuridica = null;
    private static Login login = null;
    private DaoGerarPedido daoGerarPedido = null;
    private Pedido pedido = null;
    //private String nome;
    private DefaultTableModel model1 = null;
    private DefaultTableModel model = null;
    private String legendaSituacao = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Controle_Estratégico_Vendedor;
    private javax.swing.JPanel Endereço;
    private javax.swing.JPanel Painel_Clientes;
    private javax.swing.JPanel Painel_Dados;
    private javax.swing.JTabbedPane Painel_Vendas;
    private javax.swing.JPanel Painel_VendasFeitas;
    private javax.swing.JButton btnFiltrarData;
    private javax.swing.JButton btnVisualizarCliente;
    private javax.swing.JButton btnVisualizarVendas;
    private javax.swing.JButton btnVisualizarVendedor;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroupVendedor;
    private javax.swing.JComboBox<String> cbxUF;
    private javax.swing.JFormattedTextField ftxtCEP;
    private javax.swing.JFormattedTextField ftxtCPF;
    private javax.swing.JFormattedTextField ftxtCelular;
    private javax.swing.JFormattedTextField ftxtData_Final;
    private javax.swing.JFormattedTextField ftxtData_Inicial;
    private javax.swing.JFormattedTextField ftxtDtNasc;
    private javax.swing.JFormattedTextField ftxtDtcadastro;
    private javax.swing.JFormattedTextField ftxtRG;
    private javax.swing.JFormattedTextField ftxtTelefone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDados;
    private javax.swing.JPanel jPanelVendedor;
    private javax.swing.JScrollPane jScrollPaneVendedor;
    private javax.swing.JScrollPane jScrollPaneVendedor1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCidade1;
    private javax.swing.JLabel lblClienteAtivo;
    private javax.swing.JLabel lblClienteInativo;
    private javax.swing.JLabel lblClienteInativo1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigo1;
    private javax.swing.JLabel lblControle_Estrategico;
    private javax.swing.JLabel lblData_Final;
    private javax.swing.JLabel lblData_Inicial;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFuncao;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblQtdeVendas;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblValorTotalVendas;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTable tblVendas;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtClientesAtivos;
    private javax.swing.JTextField txtClientesInativos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFuncao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtQtdeVendas;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtSituacao;
    private javax.swing.JTextField txtTotalClientes;
    private javax.swing.JTextField txtValorTotalVendas;
    // End of variables declaration//GEN-END:variables
    public void preencherTela(Vendedor vendedor) {
        // painel dados pessoais
        txtNome.setText(vendedor.getNome());
        txtCodigo.setText(String.valueOf(vendedor.getCodigo()));
        switch (vendedor.getPermissao()) {
            case 0:
                txtFuncao.setText("Vendedor");
                break;
            case 1:
                txtFuncao.setText("Gerente de Vendas");
                break;
            case 2:
                txtFuncao.setText("Supervisor de Vendas");
                break;
        }
        ftxtTelefone.setText(vendedor.getTel());
        ftxtCelular.setText(vendedor.getCel());
        txtEmail.setText(vendedor.getEmail());
        ftxtCPF.setText(vendedor.getCpf());
        ftxtRG.setText(vendedor.getRg());
        ftxtDtNasc.setText(vendedor.getDataNasc());
        txtComplemento.setText(vendedor.getComplemento());
        ftxtDtcadastro.setText(vendedor.getDtInicio());

        if (vendedor.getAtivo().equals("A")) {
            txtSituacao.setText("ATIVO");
        } else {
            txtSituacao.setText("INATIVO");
        }

        //painel endereço
        txtRua.setText(vendedor.getRua());
        txtNumero.setText(vendedor.getNumero());
        txtBairro.setText(vendedor.getBairro());
        txtCidade.setText(vendedor.getCidade());
        cbxUF.setSelectedItem(vendedor.getUf());
        ftxtCEP.setText(vendedor.getCep());
    }

    public void preencherTblClientes(ArrayList<PessoaFisica> clientesPF, ArrayList<PessoaJuridica> clientesPJ) {
        if (flagLimpaTabela1 == 1) {
            model1.setRowCount(0);
        }
        String ativo = "";
        String cpfcnpj = "";
        int i = 0;
        int a = 0;
        for (int x = 0; x < clientesPF.size(); x++) {
            cpfcnpj = clientesPF.get(x).getCpf().substring(0, 3) + "."
                    + clientesPF.get(x).getCpf().substring(3, 6) + "."
                    + clientesPF.get(x).getCpf().substring(6, 9) + "-"
                    + clientesPF.get(x).getCpf().substring(9, 11);
            if (clientesPF.get(x).getAtivo().equals("A")) {
                ativo = "ATIVO";
                a++;
            } else {
                ativo = "INATIVO";
                i++;
            }
            Object[] row = {
                clientesPF.get(x).getCodigo(),
                clientesPF.get(x).getNome(),
                cpfcnpj,
                ativo};

            model1 = (DefaultTableModel) tblClientes.getModel();
            model1.addRow(row);
            flagLimpaTabela1 = 1;
        }
        for (int x = 0; x < clientesPJ.size(); x++) {
            cpfcnpj = clientesPJ.get(x).getCnpj().subSequence(0, 2) + "."
                    + clientesPJ.get(x).getCnpj().subSequence(2, 5) + "."
                    + clientesPJ.get(x).getCnpj().subSequence(5, 8) + "/"
                    + clientesPJ.get(x).getCnpj().subSequence(8, 12) + "-"
                    + clientesPJ.get(x).getCnpj().subSequence(12, 14);
            if (clientesPJ.get(x).getAtivo().equals("A")) {
                ativo = "ATIVO";
                a++;
            } else {
                ativo = "INATIVO";
                i++;
            }
            Object[] row = {
                clientesPJ.get(x).getCodigo(),
                clientesPJ.get(x).getNome(),
                cpfcnpj,
                ativo};

            model1 = (DefaultTableModel) tblClientes.getModel();
            model1.addRow(row);
            flagLimpaTabela1 = 1;
        }
        txtClientesAtivos.setText(String.valueOf(a));
        txtClientesInativos.setText(String.valueOf(i));
    }

    public void preencherTblVendas(ArrayList<NotaFiscal> ListarNotaFiscal, Vendedor vendedor) {
        if (flagLimpaTabela == 1) {
            model.setRowCount(0);
        }
        int diaI = parseInt(ftxtData_Inicial.getText().substring(0, 2));
        int mesI = parseInt(ftxtData_Inicial.getText().substring(3, 5));
        int anoI = parseInt(ftxtData_Inicial.getText().substring(6, 10));
        LocalDate dataInicio = LocalDate.of(anoI, mesI, diaI);

        int diaF = parseInt(ftxtData_Final.getText().substring(0, 2));
        int mesF = parseInt(ftxtData_Final.getText().substring(3, 5));
        int anoF = parseInt(ftxtData_Final.getText().substring(6, 10));
        LocalDate dataFinal = LocalDate.of(anoF, mesF, diaF);

        for (int x = 0; x < ListarNotaFiscal.size(); x++) {
            int dia = parseInt(ListarNotaFiscal.get(x).getDataEmissao().substring(0, 2));
            int mes = parseInt(ListarNotaFiscal.get(x).getDataEmissao().substring(3, 5));
            int ano = parseInt(ListarNotaFiscal.get(x).getDataEmissao().substring(6, 10));
            LocalDate dataPedido = LocalDate.of(ano, mes, dia);

            // testa se a data é maior que a data inicial da busca
            if (dataPedido.isAfter(dataInicio) || dataPedido.isEqual(dataInicio)) {
                //testa se a data é menor que a data final da busca
                if (dataPedido.isBefore(dataFinal) || dataPedido.isEqual(dataFinal)) {
                    //fazer busca para ver quem efetuou o pedido
                    pedido = daoGerarPedido.Consultar(ListarNotaFiscal.get(x).getPedidoCod());
                    if (vendedor.getCodigo() == pedido.getVendedorCod()) {
                        String nome;
                        if (pedido.getClienteCod().substring(0, 2).equals("PF")) {
                            pessoaFisica = daoPFisica.consultar(pedido.getClienteCod());
                            nome = pessoaFisica.getNome();
                        } else {
                            pessoaJuridica = daoPJrudica.consultar(pedido.getClienteCod());
                            nome = pessoaJuridica.getNome();
                        }
                        Object[] row = {
                            pedido.getClienteCod(),
                            nome,
                            ListarNotaFiscal.get(x).getNumero(),
                            formatador.format(ListarNotaFiscal.get(x).getTotal()),
                            ListarNotaFiscal.get(x).getDataEmissao()
                        };

                        model = (DefaultTableModel) tblVendas.getModel();
                        model.addRow(row);
                        flagLimpaTabela = 1;
                    }

                }
            }
        }
    }
}
