/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.vendas.view;

import java.awt.Color;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projeto.vendas.control.Conexao;
import projeto.vendas.control.DaoEmitirNotaFiscal;
import projeto.vendas.control.DaoGerarPedido;
import projeto.vendas.control.DaoNotaFiscalItens;
import projeto.vendas.control.DaoPFisica;
import projeto.vendas.control.DaoPJuridica;
import projeto.vendas.control.DaoPedidoProduto;
import projeto.vendas.control.DaoProduto;
import projeto.vendas.model.Login;
import projeto.vendas.model.NotaFiscal;
import projeto.vendas.model.NotaFiscalItens;
import projeto.vendas.model.Pedido;
import projeto.vendas.model.PedidoProduto;
import projeto.vendas.model.PessoaFisica;
import projeto.vendas.model.PessoaJuridica;
import projeto.vendas.model.Produto;

/**
 *
 * @author Cleiton
 */
public class GuiEmitir_nota_fiscal extends javax.swing.JFrame {

    /**
     * Creates new form GuiEmitir_nota_fiscal
     */
    public GuiEmitir_nota_fiscal(Pedido pPedido, Login login) {
        initComponents();
        recebePedido = pPedido;
        this.login = login;
        GuiEmitir_nota_fiscal.this.setTitle("Emitir Nota Fiscal   " + "Usuário:  " + login.getNome()
                + "         " + "Codigo:  " + login.getCodigo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelNota_Fiscal = new javax.swing.JPanel();
        jPanelTipo_nota = new javax.swing.JPanel();
        rbtnSaida = new javax.swing.JRadioButton();
        rbtnEntrada = new javax.swing.JRadioButton();
        jPanelNatureza_da_Operacao = new javax.swing.JPanel();
        lblCFOP = new javax.swing.JLabel();
        cbxCFOP = new javax.swing.JComboBox<>();
        lbl_Descricao_CFOP = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnGerar_NF = new javax.swing.JButton();
        jPanelDescricao_Nota_Fiscal = new javax.swing.JTabbedPane();
        jPanelDados_Emitente = new javax.swing.JPanel();
        lblEmpresa_Emitente = new javax.swing.JLabel();
        cbxEmpresa_Emitente = new javax.swing.JComboBox<>();
        lblCNPJ_Emitente = new javax.swing.JLabel();
        ftxtCNPJ_Emitente = new javax.swing.JFormattedTextField();
        lblRazao_Social_Emitente = new javax.swing.JLabel();
        txtRazao_Social_Emitente = new javax.swing.JTextField();
        jPanelEndereco_Emitente = new javax.swing.JPanel();
        lblRua_Emitente = new javax.swing.JLabel();
        txtRua_Emitente = new javax.swing.JTextField();
        lblNumero_Emitente = new javax.swing.JLabel();
        txtNumero_Emitente = new javax.swing.JTextField();
        lblComplemento_Emitente = new javax.swing.JLabel();
        txtComplemento_Emitente = new javax.swing.JTextField();
        lblBairro_Emitente = new javax.swing.JLabel();
        txtBairro_Emitente = new javax.swing.JTextField();
        lblCEP_Emitente = new javax.swing.JLabel();
        ftxtCEP_Emitente = new javax.swing.JFormattedTextField();
        lblCidade_Emitente = new javax.swing.JLabel();
        txtCidade_Emitente = new javax.swing.JTextField();
        lblUF_Emitente = new javax.swing.JLabel();
        txtUF_Emitente = new javax.swing.JTextField();
        jPanelRemetente = new javax.swing.JPanel();
        jPanelDados_Remetente = new javax.swing.JPanel();
        lblNome_Fantasia_Remetente = new javax.swing.JLabel();
        txt_NomeDestinario = new javax.swing.JTextField();
        lblTelefone_Remetente = new javax.swing.JLabel();
        ftxtTelefone_Remetente = new javax.swing.JFormattedTextField();
        lblEmail_Remetente = new javax.swing.JLabel();
        txtEmail_Remetente = new javax.swing.JTextField();
        jPanelEndereco_Remetente = new javax.swing.JPanel();
        lblRua_Remetente = new javax.swing.JLabel();
        txtRua_Remetente = new javax.swing.JTextField();
        lblNumero_Remetente = new javax.swing.JLabel();
        txtNumero_Remetente = new javax.swing.JTextField();
        lblComplemento_Remetente = new javax.swing.JLabel();
        txtComplemento_Remetente = new javax.swing.JTextField();
        lblBairro_Remetente = new javax.swing.JLabel();
        txtBairro_Remetente = new javax.swing.JTextField();
        lblCEP_Remetente = new javax.swing.JLabel();
        ftxtCEP_Remetente = new javax.swing.JFormattedTextField();
        lblCidade_Remetente = new javax.swing.JLabel();
        txtCidade_Remetente = new javax.swing.JTextField();
        lblUF_Remetente = new javax.swing.JLabel();
        txtUF_Remetente = new javax.swing.JTextField();
        jPanelProdutos = new javax.swing.JPanel();
        jScrollPaneProduto = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        jPanelTransportadora = new javax.swing.JPanel();
        jPanelTotais = new javax.swing.JPanel();
        lblValor_Total_Nota = new javax.swing.JLabel();
        txtValor_Total_Nota = new javax.swing.JTextField();
        jPanelProduto = new javax.swing.JPanel();
        lblTotal_Produtos = new javax.swing.JLabel();
        txtTotal_Produtos = new javax.swing.JTextField();
        lblTotal_desc_Produto = new javax.swing.JLabel();
        txtTotal_Desc_Produto = new javax.swing.JTextField();
        jPanelICMS = new javax.swing.JPanel();
        lblBase_Calculo_ICMS = new javax.swing.JLabel();
        txtBase_Calculo_ICMS = new javax.swing.JTextField();
        lblValor_ICMS = new javax.swing.JLabel();
        txtValor_ICMS = new javax.swing.JTextField();
        jPanelPIS_COFINS = new javax.swing.JPanel();
        lblValor_PIS = new javax.swing.JLabel();
        txtValor_PIS = new javax.swing.JTextField();
        lblValor_COFINS = new javax.swing.JLabel();
        txtValor_COFINS = new javax.swing.JTextField();
        lblValor_IPI = new javax.swing.JLabel();
        txtValor_IPI = new javax.swing.JTextField();
        jPanelDados_Nota_Fiscal = new javax.swing.JPanel();
        lblSerie_Nota_Fiscal = new javax.swing.JLabel();
        txtSerie_Nota_Fiscal = new javax.swing.JTextField();
        lblNumero_Nota_Fiscal = new javax.swing.JLabel();
        txtNumero_Nota_Fiscal = new javax.swing.JTextField();
        lblData_Emissao = new javax.swing.JLabel();
        ftxtData_Emissao = new javax.swing.JFormattedTextField();
        lblHora_Emissao = new javax.swing.JLabel();
        ftxtHora_Emissao = new javax.swing.JFormattedTextField();
        jPanelSaida = new javax.swing.JPanel();
        lblData_Saida = new javax.swing.JLabel();
        ftxtData_Saida = new javax.swing.JFormattedTextField();
        lblHora_Saida = new javax.swing.JLabel();
        ftxtHora_Saida = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emitir Nota Fiscal");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelTipo_nota.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo da Nota"));

        buttonGroup1.add(rbtnSaida);
        rbtnSaida.setSelected(true);
        rbtnSaida.setText("Saída");

        buttonGroup1.add(rbtnEntrada);
        rbtnEntrada.setText("Entrada");
        rbtnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTipo_notaLayout = new javax.swing.GroupLayout(jPanelTipo_nota);
        jPanelTipo_nota.setLayout(jPanelTipo_notaLayout);
        jPanelTipo_notaLayout.setHorizontalGroup(
            jPanelTipo_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipo_notaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnSaida)
                .addGap(18, 18, 18)
                .addComponent(rbtnEntrada)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanelTipo_notaLayout.setVerticalGroup(
            jPanelTipo_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTipo_notaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTipo_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnSaida)
                    .addComponent(rbtnEntrada))
                .addGap(16, 16, 16))
        );

        jPanelNatureza_da_Operacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Natureza da Operação"));

        lblCFOP.setText("CFOP");

        cbxCFOP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5101", "5102", "5910", "5911", "5915", "5949" }));
        cbxCFOP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCFOPItemStateChanged(evt);
            }
        });

        lbl_Descricao_CFOP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanelNatureza_da_OperacaoLayout = new javax.swing.GroupLayout(jPanelNatureza_da_Operacao);
        jPanelNatureza_da_Operacao.setLayout(jPanelNatureza_da_OperacaoLayout);
        jPanelNatureza_da_OperacaoLayout.setHorizontalGroup(
            jPanelNatureza_da_OperacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNatureza_da_OperacaoLayout.createSequentialGroup()
                .addGroup(jPanelNatureza_da_OperacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCFOP)
                    .addGroup(jPanelNatureza_da_OperacaoLayout.createSequentialGroup()
                        .addComponent(cbxCFOP, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Descricao_CFOP)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNatureza_da_OperacaoLayout.setVerticalGroup(
            jPanelNatureza_da_OperacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNatureza_da_OperacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCFOP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNatureza_da_OperacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCFOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Descricao_CFOP))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnGerar_NF.setText("Gerar NF-e");
        btnGerar_NF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerar_NFActionPerformed(evt);
            }
        });

        lblEmpresa_Emitente.setText("Empresa de Emissão");

        cbxEmpresa_Emitente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pet Happy" }));

        lblCNPJ_Emitente.setText("CNPJ");

        try {
            ftxtCNPJ_Emitente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCNPJ_Emitente.setText("50.000.000/0000-01");

        lblRazao_Social_Emitente.setText("Razão Social");

        txtRazao_Social_Emitente.setText("Servir bem os Animais.");

        jPanelEndereco_Emitente.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        lblRua_Emitente.setText("Rua");

        txtRua_Emitente.setText("Santiago Idalgo Ruiz");

        lblNumero_Emitente.setText("Número");

        txtNumero_Emitente.setText("69");
        txtNumero_Emitente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero_EmitenteActionPerformed(evt);
            }
        });

        lblComplemento_Emitente.setText("Complemento");

        txtComplemento_Emitente.setText("Não Existe");

        lblBairro_Emitente.setText("Bairro");

        txtBairro_Emitente.setText("Jardim Maria Antonia Prado");

        lblCEP_Emitente.setText("CEP");

        try {
            ftxtCEP_Emitente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCEP_Emitente.setText("18.076-120");

        lblCidade_Emitente.setText("Cidade");

        txtCidade_Emitente.setText("Sorocaba");

        lblUF_Emitente.setText("UF");

        txtUF_Emitente.setText("SP");

        javax.swing.GroupLayout jPanelEndereco_EmitenteLayout = new javax.swing.GroupLayout(jPanelEndereco_Emitente);
        jPanelEndereco_Emitente.setLayout(jPanelEndereco_EmitenteLayout);
        jPanelEndereco_EmitenteLayout.setHorizontalGroup(
            jPanelEndereco_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEndereco_EmitenteLayout.createSequentialGroup()
                .addComponent(lblRua_Emitente)
                .addGap(198, 198, 198)
                .addComponent(lblNumero_Emitente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(lblComplemento_Emitente)
                .addGap(112, 112, 112))
            .addGroup(jPanelEndereco_EmitenteLayout.createSequentialGroup()
                .addGroup(jPanelEndereco_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEndereco_EmitenteLayout.createSequentialGroup()
                        .addGroup(jPanelEndereco_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEndereco_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtBairro_Emitente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addComponent(txtRua_Emitente, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblBairro_Emitente))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEndereco_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEndereco_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ftxtCEP_Emitente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(txtNumero_Emitente, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblCEP_Emitente))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEndereco_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCidade_Emitente)
                            .addComponent(txtComplemento_Emitente)
                            .addComponent(txtCidade_Emitente, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                    .addComponent(lblUF_Emitente)
                    .addComponent(txtUF_Emitente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelEndereco_EmitenteLayout.setVerticalGroup(
            jPanelEndereco_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEndereco_EmitenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEndereco_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRua_Emitente)
                    .addComponent(lblNumero_Emitente)
                    .addComponent(lblComplemento_Emitente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEndereco_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRua_Emitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero_Emitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComplemento_Emitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEndereco_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro_Emitente)
                    .addComponent(lblCEP_Emitente)
                    .addComponent(lblCidade_Emitente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEndereco_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairro_Emitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCEP_Emitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade_Emitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUF_Emitente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(txtUF_Emitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelDados_EmitenteLayout = new javax.swing.GroupLayout(jPanelDados_Emitente);
        jPanelDados_Emitente.setLayout(jPanelDados_EmitenteLayout);
        jPanelDados_EmitenteLayout.setHorizontalGroup(
            jPanelDados_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDados_EmitenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDados_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDados_EmitenteLayout.createSequentialGroup()
                        .addComponent(jPanelEndereco_Emitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelDados_EmitenteLayout.createSequentialGroup()
                        .addGroup(jPanelDados_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmpresa_Emitente)
                            .addComponent(cbxEmpresa_Emitente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanelDados_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftxtCNPJ_Emitente, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCNPJ_Emitente))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDados_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRazao_Social_Emitente, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRazao_Social_Emitente))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelDados_EmitenteLayout.setVerticalGroup(
            jPanelDados_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDados_EmitenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDados_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpresa_Emitente)
                    .addComponent(lblCNPJ_Emitente)
                    .addComponent(lblRazao_Social_Emitente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDados_EmitenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxEmpresa_Emitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCNPJ_Emitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRazao_Social_Emitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanelEndereco_Emitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDescricao_Nota_Fiscal.addTab("Remetente", jPanelDados_Emitente);

        lblNome_Fantasia_Remetente.setText("Nome Fantasia");

        lblTelefone_Remetente.setText("Telefone");

        try {
            ftxtTelefone_Remetente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblEmail_Remetente.setText("Email");

        jPanelEndereco_Remetente.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        lblRua_Remetente.setText("Rua");

        lblNumero_Remetente.setText("Número");

        lblComplemento_Remetente.setText("Complemento");

        lblBairro_Remetente.setText("Bairro");

        lblCEP_Remetente.setText("CEP");

        try {
            ftxtCEP_Remetente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblCidade_Remetente.setText("Cidade");

        lblUF_Remetente.setText("UF");

        javax.swing.GroupLayout jPanelEndereco_RemetenteLayout = new javax.swing.GroupLayout(jPanelEndereco_Remetente);
        jPanelEndereco_Remetente.setLayout(jPanelEndereco_RemetenteLayout);
        jPanelEndereco_RemetenteLayout.setHorizontalGroup(
            jPanelEndereco_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEndereco_RemetenteLayout.createSequentialGroup()
                .addGroup(jPanelEndereco_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEndereco_RemetenteLayout.createSequentialGroup()
                        .addGroup(jPanelEndereco_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEndereco_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtBairro_Remetente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addComponent(txtRua_Remetente, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanelEndereco_RemetenteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblBairro_Remetente)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEndereco_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEndereco_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ftxtCEP_Remetente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(txtNumero_Remetente, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblCEP_Remetente))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEndereco_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCidade_Remetente)
                            .addComponent(txtComplemento_Remetente)
                            .addComponent(txtCidade_Remetente, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                    .addComponent(txtUF_Remetente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelEndereco_RemetenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEndereco_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEndereco_RemetenteLayout.createSequentialGroup()
                        .addComponent(lblRua_Remetente)
                        .addGap(188, 188, 188)
                        .addComponent(lblNumero_Remetente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(lblComplemento_Remetente)
                        .addGap(112, 112, 112))
                    .addGroup(jPanelEndereco_RemetenteLayout.createSequentialGroup()
                        .addComponent(lblUF_Remetente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelEndereco_RemetenteLayout.setVerticalGroup(
            jPanelEndereco_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEndereco_RemetenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEndereco_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRua_Remetente)
                    .addComponent(lblNumero_Remetente)
                    .addComponent(lblComplemento_Remetente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEndereco_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRua_Remetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero_Remetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComplemento_Remetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEndereco_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro_Remetente)
                    .addComponent(lblCEP_Remetente)
                    .addComponent(lblCidade_Remetente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEndereco_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairro_Remetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtCEP_Remetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade_Remetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUF_Remetente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtUF_Remetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanelDados_RemetenteLayout = new javax.swing.GroupLayout(jPanelDados_Remetente);
        jPanelDados_Remetente.setLayout(jPanelDados_RemetenteLayout);
        jPanelDados_RemetenteLayout.setHorizontalGroup(
            jPanelDados_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDados_RemetenteLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelDados_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDados_RemetenteLayout.createSequentialGroup()
                        .addComponent(jPanelEndereco_Remetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelDados_RemetenteLayout.createSequentialGroup()
                        .addGroup(jPanelDados_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome_Fantasia_Remetente)
                            .addComponent(txt_NomeDestinario, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDados_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftxtTelefone_Remetente, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefone_Remetente))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDados_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail_Remetente, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail_Remetente))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelDados_RemetenteLayout.setVerticalGroup(
            jPanelDados_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDados_RemetenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDados_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome_Fantasia_Remetente)
                    .addComponent(lblTelefone_Remetente)
                    .addComponent(lblEmail_Remetente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDados_RemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtTelefone_Remetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail_Remetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NomeDestinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanelEndereco_Remetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelRemetenteLayout = new javax.swing.GroupLayout(jPanelRemetente);
        jPanelRemetente.setLayout(jPanelRemetenteLayout);
        jPanelRemetenteLayout.setHorizontalGroup(
            jPanelRemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemetenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDados_Remetente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(345, Short.MAX_VALUE))
        );
        jPanelRemetenteLayout.setVerticalGroup(
            jPanelRemetenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemetenteLayout.createSequentialGroup()
                .addComponent(jPanelDados_Remetente, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelDescricao_Nota_Fiscal.addTab("Destinatário", jPanelRemetente);

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Valor Unitário", "Qtd", "Seguro", "Frete", "Outras Desp.", "Valor Total", "ICMS", "PIS", "COFINS", "IPI", "CFOP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneProduto.setViewportView(tblProduto);

        javax.swing.GroupLayout jPanelProdutosLayout = new javax.swing.GroupLayout(jPanelProdutos);
        jPanelProdutos.setLayout(jPanelProdutosLayout);
        jPanelProdutosLayout.setHorizontalGroup(
            jPanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelProdutosLayout.setVerticalGroup(
            jPanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutosLayout.createSequentialGroup()
                .addComponent(jScrollPaneProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        jPanelDescricao_Nota_Fiscal.addTab("Produtos", jPanelProdutos);

        javax.swing.GroupLayout jPanelTransportadoraLayout = new javax.swing.GroupLayout(jPanelTransportadora);
        jPanelTransportadora.setLayout(jPanelTransportadoraLayout);
        jPanelTransportadoraLayout.setHorizontalGroup(
            jPanelTransportadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 913, Short.MAX_VALUE)
        );
        jPanelTransportadoraLayout.setVerticalGroup(
            jPanelTransportadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        jPanelDescricao_Nota_Fiscal.addTab("Transporte/Frete", jPanelTransportadora);

        lblValor_Total_Nota.setText("Valor Total da Nota");

        txtValor_Total_Nota.setText("0");
        txtValor_Total_Nota.setEnabled(false);

        jPanelProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos"));

        lblTotal_Produtos.setText("Total dos Produtos");

        txtTotal_Produtos.setText("0");
        txtTotal_Produtos.setEnabled(false);

        lblTotal_desc_Produto.setText("Total de Desconto nos Produtos");

        txtTotal_Desc_Produto.setText("0");
        txtTotal_Desc_Produto.setEnabled(false);

        jPanelICMS.setBorder(javax.swing.BorderFactory.createTitledBorder("ICMS"));

        lblBase_Calculo_ICMS.setText("Base Calculo ICMS");

        txtBase_Calculo_ICMS.setText("0");
        txtBase_Calculo_ICMS.setEnabled(false);

        lblValor_ICMS.setText("Valor ICMS");

        txtValor_ICMS.setText("0");
        txtValor_ICMS.setEnabled(false);

        javax.swing.GroupLayout jPanelICMSLayout = new javax.swing.GroupLayout(jPanelICMS);
        jPanelICMS.setLayout(jPanelICMSLayout);
        jPanelICMSLayout.setHorizontalGroup(
            jPanelICMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelICMSLayout.createSequentialGroup()
                .addGroup(jPanelICMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBase_Calculo_ICMS)
                    .addComponent(txtBase_Calculo_ICMS, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanelICMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValor_ICMS)
                    .addComponent(txtValor_ICMS, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelICMSLayout.setVerticalGroup(
            jPanelICMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelICMSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelICMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBase_Calculo_ICMS)
                    .addComponent(lblValor_ICMS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelICMSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBase_Calculo_ICMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor_ICMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelPIS_COFINS.setBorder(javax.swing.BorderFactory.createTitledBorder("PIS/COFINS"));

        lblValor_PIS.setText("Valor PIS");

        txtValor_PIS.setText("0");
        txtValor_PIS.setEnabled(false);

        lblValor_COFINS.setText("Valor COFINS");

        txtValor_COFINS.setText("0");
        txtValor_COFINS.setEnabled(false);

        lblValor_IPI.setText("Valor IPI");

        txtValor_IPI.setText("0");
        txtValor_IPI.setEnabled(false);

        javax.swing.GroupLayout jPanelPIS_COFINSLayout = new javax.swing.GroupLayout(jPanelPIS_COFINS);
        jPanelPIS_COFINS.setLayout(jPanelPIS_COFINSLayout);
        jPanelPIS_COFINSLayout.setHorizontalGroup(
            jPanelPIS_COFINSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPIS_COFINSLayout.createSequentialGroup()
                .addGroup(jPanelPIS_COFINSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValor_PIS)
                    .addComponent(txtValor_PIS, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanelPIS_COFINSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValor_COFINS)
                    .addComponent(txtValor_COFINS, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanelPIS_COFINSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValor_IPI)
                    .addComponent(txtValor_IPI, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 344, Short.MAX_VALUE))
        );
        jPanelPIS_COFINSLayout.setVerticalGroup(
            jPanelPIS_COFINSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPIS_COFINSLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPIS_COFINSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPIS_COFINSLayout.createSequentialGroup()
                        .addGroup(jPanelPIS_COFINSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValor_PIS)
                            .addComponent(lblValor_COFINS)
                            .addComponent(lblValor_IPI))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPIS_COFINSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtValor_PIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtValor_COFINS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtValor_IPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanelProdutoLayout = new javax.swing.GroupLayout(jPanelProduto);
        jPanelProduto.setLayout(jPanelProdutoLayout);
        jPanelProdutoLayout.setHorizontalGroup(
            jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelICMS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelProdutoLayout.createSequentialGroup()
                .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal_Produtos)
                    .addComponent(txtTotal_Produtos, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTotal_desc_Produto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTotal_Desc_Produto))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanelPIS_COFINS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelProdutoLayout.setVerticalGroup(
            jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal_Produtos)
                    .addComponent(lblTotal_desc_Produto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal_Produtos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal_Desc_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelICMS, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPIS_COFINS, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanelTotaisLayout = new javax.swing.GroupLayout(jPanelTotais);
        jPanelTotais.setLayout(jPanelTotaisLayout);
        jPanelTotaisLayout.setHorizontalGroup(
            jPanelTotaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTotaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTotaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelTotaisLayout.createSequentialGroup()
                        .addGroup(jPanelTotaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValor_Total_Nota)
                            .addComponent(txtValor_Total_Nota, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelTotaisLayout.setVerticalGroup(
            jPanelTotaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTotaisLayout.createSequentialGroup()
                .addComponent(lblValor_Total_Nota)
                .addGap(5, 5, 5)
                .addComponent(txtValor_Total_Nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDescricao_Nota_Fiscal.addTab("Totais", jPanelTotais);

        jPanelDados_Nota_Fiscal.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Nota Fiscal"));

        lblSerie_Nota_Fiscal.setText("Série da Nota Fiscal");

        txtSerie_Nota_Fiscal.setText("551");

        lblNumero_Nota_Fiscal.setText("Número da Nota Fiscal");

        lblData_Emissao.setText("Data Emissão");

        try {
            ftxtData_Emissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblHora_Emissao.setText("Hora Emissão");

        try {
            ftxtHora_Emissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanelDados_Nota_FiscalLayout = new javax.swing.GroupLayout(jPanelDados_Nota_Fiscal);
        jPanelDados_Nota_Fiscal.setLayout(jPanelDados_Nota_FiscalLayout);
        jPanelDados_Nota_FiscalLayout.setHorizontalGroup(
            jPanelDados_Nota_FiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDados_Nota_FiscalLayout.createSequentialGroup()
                .addGroup(jPanelDados_Nota_FiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtSerie_Nota_Fiscal, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSerie_Nota_Fiscal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanelDados_Nota_FiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNumero_Nota_Fiscal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNumero_Nota_Fiscal))
                .addGap(18, 18, 18)
                .addGroup(jPanelDados_Nota_FiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblData_Emissao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ftxtData_Emissao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDados_Nota_FiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHora_Emissao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ftxtHora_Emissao))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelDados_Nota_FiscalLayout.setVerticalGroup(
            jPanelDados_Nota_FiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDados_Nota_FiscalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDados_Nota_FiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerie_Nota_Fiscal)
                    .addComponent(lblNumero_Nota_Fiscal)
                    .addComponent(lblData_Emissao)
                    .addComponent(lblHora_Emissao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDados_Nota_FiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerie_Nota_Fiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero_Nota_Fiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtData_Emissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtHora_Emissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanelSaida.setBorder(javax.swing.BorderFactory.createTitledBorder("Saída/Entrada da Mercadoria"));

        lblData_Saida.setText("Data");

        try {
            ftxtData_Saida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblHora_Saida.setText("Hora");

        try {
            ftxtHora_Saida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtHora_Saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtHora_SaidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSaidaLayout = new javax.swing.GroupLayout(jPanelSaida);
        jPanelSaida.setLayout(jPanelSaidaLayout);
        jPanelSaidaLayout.setHorizontalGroup(
            jPanelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSaidaLayout.createSequentialGroup()
                .addGroup(jPanelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblData_Saida)
                    .addComponent(ftxtData_Saida, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftxtHora_Saida, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHora_Saida))
                .addGap(55, 55, 55))
        );
        jPanelSaidaLayout.setVerticalGroup(
            jPanelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData_Saida)
                    .addComponent(lblHora_Saida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtData_Saida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtHora_Saida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelNota_FiscalLayout = new javax.swing.GroupLayout(jPanelNota_Fiscal);
        jPanelNota_Fiscal.setLayout(jPanelNota_FiscalLayout);
        jPanelNota_FiscalLayout.setHorizontalGroup(
            jPanelNota_FiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNota_FiscalLayout.createSequentialGroup()
                .addGroup(jPanelNota_FiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelNota_FiscalLayout.createSequentialGroup()
                        .addComponent(jPanelTipo_nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelNatureza_da_Operacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelNota_FiscalLayout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(76, 76, 76)
                        .addComponent(btnImprimir)
                        .addGap(106, 106, 106)
                        .addComponent(btnGerar_NF))
                    .addComponent(jPanelDados_Nota_Fiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDescricao_Nota_Fiscal))
        );
        jPanelNota_FiscalLayout.setVerticalGroup(
            jPanelNota_FiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNota_FiscalLayout.createSequentialGroup()
                .addGroup(jPanelNota_FiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDescricao_Nota_Fiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelNota_FiscalLayout.createSequentialGroup()
                        .addComponent(jPanelDados_Nota_Fiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelNota_FiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelTipo_nota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelNatureza_da_Operacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelNota_FiscalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVoltar)
                            .addComponent(btnImprimir)
                            .addComponent(btnGerar_NF))))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelNota_Fiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelNota_Fiscal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnEntradaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnGerar_NFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerar_NFActionPerformed
        String TipoNota = "";
        if (rbtnSaida.isSelected()) {
            TipoNota = "Saida";
        } else {
            TipoNota = "Entrada";
        }
        txtNumero_Nota_Fiscal.setText("" + daoEmitirNF.getProximoCodigo());
        nf = new NotaFiscal(Integer.parseInt(txtNumero_Nota_Fiscal.getText()), Integer.parseInt(txtSerie_Nota_Fiscal.getText()), recebePedido.getCodigo(), TipoNota, cbxCFOP.getSelectedItem().toString(), recebePedido.getTotal(), ftxtData_Emissao.getText(), ftxtHora_Emissao.getText(), recebePedido.getCodigo());

        if (daoEmitirNF.inserir(nf)) {
            daoNotaFiscalItems.inserir(nfItens);
            daoGerarPedido.Faturar(recebePedido.getCodigo());
            JOptionPane.showMessageDialog(null, "Pedido Faturado e Nota Fiscal Emitida !!", "Parabéns", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Falha na Geração da NFE.", "Erro Crítico", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnGerar_NFActionPerformed

    private void ftxtHora_SaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtHora_SaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtHora_SaidaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        conexao = new Conexao();
        conexao.setDriver();
        conexao.setConnectionString();
        daoGerarPedido = new DaoGerarPedido(conexao.conectar());
        daoPJuridica = new DaoPJuridica(conexao.conectar());
        daoPFisica = new DaoPFisica(conexao.conectar());
        daoPedidoProduto = new DaoPedidoProduto(conexao.conectar());
        daoProduto = new DaoProduto(conexao.conectar());
        daoEmitirNF = new DaoEmitirNotaFiscal(conexao.conectar());
        daoNotaFiscalItems = new DaoNotaFiscalItens(conexao.conectar());

        Date data = new Date(System.currentTimeMillis());
        Calendar calendar = new GregorianCalendar();
        SimpleDateFormat formatarDate = new SimpleDateFormat("dd/MM/yyyy");

        txtNumero_Nota_Fiscal.setText("" + daoEmitirNF.getProximoCodigo());
        ftxtData_Emissao.setText(formatarDate.format(data));
        ftxtData_Saida.setText(formatarDate.format(data));
        ftxtHora_Emissao.setText(String.format("%02d", calendar.get(Calendar.HOUR_OF_DAY)) + ":" + (String.format("%02d", calendar.get(Calendar.MINUTE))));
        ftxtHora_Saida.setText(String.format("%02d", calendar.get(Calendar.HOUR_OF_DAY)) + ":" + (String.format("%02d", calendar.get(Calendar.MINUTE))));
        nfItens = new NotaFiscalItens(Integer.parseInt(txtNumero_Nota_Fiscal.getText()));

        System.out.println("Horas = " + calendar.get(Calendar.HOUR_OF_DAY) + ":" + calendar.get(Calendar.MINUTE));

        ftxtData_Emissao.setText(recebePedido.getDtPedido().substring(0, recebePedido.getDtPedido().indexOf("-")).replace("/", ""));
        System.out.println(recebePedido.getDtPedido().substring(0, recebePedido.getDtPedido().indexOf("-")).replace("/", ""));
        System.out.println(recebePedido.getClienteCod().subSequence(0, 2));

        if (recebePedido.getClienteCod().substring(0, 2).equals("PF")) {

            pessoaFisica = daoPFisica.consultar(recebePedido.getClienteCod());
            txt_NomeDestinario.setText(pessoaFisica.getNome());
            ftxtTelefone_Remetente.setText(pessoaFisica.getTel());
            txtEmail_Remetente.setText(pessoaFisica.getEmail());
            txtCidade_Remetente.setText(pessoaFisica.getCidade());
            txtRua_Remetente.setText(pessoaFisica.getRua());
            txtNumero_Remetente.setText(pessoaFisica.getNumero());
            txtComplemento_Remetente.setText(pessoaFisica.getComplemento());
            txtBairro_Remetente.setText(pessoaFisica.getBairro());
            ftxtCEP_Remetente.setText(pessoaFisica.getCep());
            txtCidade_Remetente.setText(pessoaFisica.getCidade());
            txtUF_Remetente.setText(pessoaFisica.getUf());
        } else {
            pessoaJuridica = daoPJuridica.consultar(recebePedido.getClienteCod());
            txt_NomeDestinario.setText(pessoaJuridica.getNome());
            ftxtTelefone_Remetente.setText(pessoaJuridica.getTel1());
            txtEmail_Remetente.setText(pessoaJuridica.getEmail());
            txtCidade_Remetente.setText(pessoaJuridica.getCidade());
            txtRua_Remetente.setText(pessoaJuridica.getRua());
            txtNumero_Remetente.setText(pessoaJuridica.getNumero());
            txtComplemento_Remetente.setText(pessoaJuridica.getComplemento());
            txtBairro_Remetente.setText(pessoaJuridica.getBairro());
            ftxtCEP_Remetente.setText(pessoaJuridica.getCep());
            txtCidade_Remetente.setText(pessoaJuridica.getCidade());
            txtUF_Remetente.setText(pessoaJuridica.getUf());
            txtTotal_Produtos.setText("" + recebePedido.getTotal());

        }
        ListaPedidoProduto = daoPedidoProduto.listarPedidoProduto(recebePedido.getCodigo());

        if (ListaPedidoProduto != null) {
            DefaultTableModel model = (DefaultTableModel) tblProduto.getModel();
            tblProduto.setBackground(Color.white);
//            tblProduto.setBounds(350, 350, 250, 270);
//            tblProduto.setFont(new java.awt.Font("Comic Sans", 1, 15));
            tblProduto.setForeground(Color.DARK_GRAY);
            tblProduto.setGridColor(Color.BLUE);
            tblProduto.setShowGrid(true);
//            tblProduto.setTableHeader(tableHeader);
            int linhasTabela = model.getRowCount();
            for (int i = 0; i < linhasTabela; i++) {
                model.removeRow(0);
            }
            for (int i = 0; i < ListaPedidoProduto.size(); i++) {

                produto = daoProduto.consultar(ListaPedidoProduto.get(i).getProdutoCod());
                nfItens.addProduto(produto);
                nfItens.addQtdProduto(ListaPedidoProduto.get(i).getProdutoQtd());
                Object[] row = {ListaPedidoProduto.get(i).getProdutoCod(), produto.getDescricao(),
                    produto.getValorUnitario(), ListaPedidoProduto.get(i).getProdutoQtd(),
                    "Sim", "Não", "Outras", produto.getValorUnitario() * ListaPedidoProduto.get(i).getProdutoQtd(),
                    produto.getImpostoIcms(), produto.getImpostoPis(), produto.getImpostoConfins(), (produto.getValorUnitario() * ListaPedidoProduto.get(i).getProdutoQtd()) * produto.getImpostoIpi(),
                    "CFOP"};
                model.addRow(row);
                //Preenchendo os TXT de Impostos
                txtValor_COFINS.setText((((float) tblProduto.getValueAt(i, 7) * produto.getImpostoConfins()) + Float.parseFloat(txtValor_COFINS.getText())) + "");
                txtValor_ICMS.setText((((float) tblProduto.getValueAt(i, 7) * produto.getImpostoIcms()) + Float.parseFloat(txtValor_ICMS.getText())) + "");
                txtValor_IPI.setText((((float) tblProduto.getValueAt(i, 7) * produto.getImpostoIpi()) + Float.parseFloat(txtValor_IPI.getText())) + "");
                txtValor_PIS.setText((((float) tblProduto.getValueAt(i, 7) * produto.getImpostoPis()) + Float.parseFloat(txtValor_PIS.getText())) + "");
            }

        }


    }//GEN-LAST:event_formWindowOpened

    private void txtNumero_EmitenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero_EmitenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero_EmitenteActionPerformed

    private void cbxCFOPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCFOPItemStateChanged

        switch (cbxCFOP.getSelectedIndex()) {
            case 0:
                lbl_Descricao_CFOP.setText("0 -> Venda de produção do estabelecimento.");
                break;
            case 1:
                lbl_Descricao_CFOP.setText("1 -> Venda de mercadoria adquirida ou recebida de terceiros.");
                break;
            case 2:
                lbl_Descricao_CFOP.setText("3 ->  Remessa em bonificação, doação ou brinde");
                break;
            case 3:
                lbl_Descricao_CFOP.setText("3 ->  Remessa de amostra grátis.");
                break;
            case 4:
                lbl_Descricao_CFOP.setText("4 -> Remessa de mercadoria ou bem para conserto ou reparo");
                break;
            case 5:
                lbl_Descricao_CFOP.setText("5 -> Outra saída de mercadoria ou prestação de serviço não especificado");
                break;
        }
    }//GEN-LAST:event_cbxCFOPItemStateChanged

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        System.out.println(String.format("%04d", 1000));
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiEmitir_nota_fiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiEmitir_nota_fiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiEmitir_nota_fiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiEmitir_nota_fiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiEmitir_nota_fiscal(recebePedido, login).setVisible(true);
            }
        });
    }

    private static Login login = null;
    private Conexao conexao;
    private DaoGerarPedido daoGerarPedido;
    private static Pedido recebePedido;
    private DaoPFisica daoPFisica;
    private DaoPJuridica daoPJuridica;
    private DaoPedidoProduto daoPedidoProduto;
    private PessoaFisica pessoaFisica;
    private Produto produto = null;
    private ArrayList<Produto> ListaProduto;
    private PessoaJuridica pessoaJuridica = null;
    private ArrayList<PedidoProduto> ListaPedidoProduto;
    private DaoProduto daoProduto;
    private DaoEmitirNotaFiscal daoEmitirNF;
    private NotaFiscal nf;
    private NotaFiscalItens nfItens = null;
    private DaoNotaFiscalItens daoNotaFiscalItems;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar_NF;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxCFOP;
    private javax.swing.JComboBox<String> cbxEmpresa_Emitente;
    private javax.swing.JFormattedTextField ftxtCEP_Emitente;
    private javax.swing.JFormattedTextField ftxtCEP_Remetente;
    private javax.swing.JFormattedTextField ftxtCNPJ_Emitente;
    private javax.swing.JFormattedTextField ftxtData_Emissao;
    private javax.swing.JFormattedTextField ftxtData_Saida;
    private javax.swing.JFormattedTextField ftxtHora_Emissao;
    private javax.swing.JFormattedTextField ftxtHora_Saida;
    private javax.swing.JFormattedTextField ftxtTelefone_Remetente;
    private javax.swing.JPanel jPanelDados_Emitente;
    private javax.swing.JPanel jPanelDados_Nota_Fiscal;
    private javax.swing.JPanel jPanelDados_Remetente;
    private javax.swing.JTabbedPane jPanelDescricao_Nota_Fiscal;
    private javax.swing.JPanel jPanelEndereco_Emitente;
    private javax.swing.JPanel jPanelEndereco_Remetente;
    private javax.swing.JPanel jPanelICMS;
    private javax.swing.JPanel jPanelNatureza_da_Operacao;
    private javax.swing.JPanel jPanelNota_Fiscal;
    private javax.swing.JPanel jPanelPIS_COFINS;
    private javax.swing.JPanel jPanelProduto;
    private javax.swing.JPanel jPanelProdutos;
    private javax.swing.JPanel jPanelRemetente;
    private javax.swing.JPanel jPanelSaida;
    private javax.swing.JPanel jPanelTipo_nota;
    private javax.swing.JPanel jPanelTotais;
    private javax.swing.JPanel jPanelTransportadora;
    private javax.swing.JScrollPane jScrollPaneProduto;
    private javax.swing.JLabel lblBairro_Emitente;
    private javax.swing.JLabel lblBairro_Remetente;
    private javax.swing.JLabel lblBase_Calculo_ICMS;
    private javax.swing.JLabel lblCEP_Emitente;
    private javax.swing.JLabel lblCEP_Remetente;
    private javax.swing.JLabel lblCFOP;
    private javax.swing.JLabel lblCNPJ_Emitente;
    private javax.swing.JLabel lblCidade_Emitente;
    private javax.swing.JLabel lblCidade_Remetente;
    private javax.swing.JLabel lblComplemento_Emitente;
    private javax.swing.JLabel lblComplemento_Remetente;
    private javax.swing.JLabel lblData_Emissao;
    private javax.swing.JLabel lblData_Saida;
    private javax.swing.JLabel lblEmail_Remetente;
    private javax.swing.JLabel lblEmpresa_Emitente;
    private javax.swing.JLabel lblHora_Emissao;
    private javax.swing.JLabel lblHora_Saida;
    private javax.swing.JLabel lblNome_Fantasia_Remetente;
    private javax.swing.JLabel lblNumero_Emitente;
    private javax.swing.JLabel lblNumero_Nota_Fiscal;
    private javax.swing.JLabel lblNumero_Remetente;
    private javax.swing.JLabel lblRazao_Social_Emitente;
    private javax.swing.JLabel lblRua_Emitente;
    private javax.swing.JLabel lblRua_Remetente;
    private javax.swing.JLabel lblSerie_Nota_Fiscal;
    private javax.swing.JLabel lblTelefone_Remetente;
    private javax.swing.JLabel lblTotal_Produtos;
    private javax.swing.JLabel lblTotal_desc_Produto;
    private javax.swing.JLabel lblUF_Emitente;
    private javax.swing.JLabel lblUF_Remetente;
    private javax.swing.JLabel lblValor_COFINS;
    private javax.swing.JLabel lblValor_ICMS;
    private javax.swing.JLabel lblValor_IPI;
    private javax.swing.JLabel lblValor_PIS;
    private javax.swing.JLabel lblValor_Total_Nota;
    private javax.swing.JLabel lbl_Descricao_CFOP;
    private javax.swing.JRadioButton rbtnEntrada;
    private javax.swing.JRadioButton rbtnSaida;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtBairro_Emitente;
    private javax.swing.JTextField txtBairro_Remetente;
    private javax.swing.JTextField txtBase_Calculo_ICMS;
    private javax.swing.JTextField txtCidade_Emitente;
    private javax.swing.JTextField txtCidade_Remetente;
    private javax.swing.JTextField txtComplemento_Emitente;
    private javax.swing.JTextField txtComplemento_Remetente;
    private javax.swing.JTextField txtEmail_Remetente;
    private javax.swing.JTextField txtNumero_Emitente;
    private javax.swing.JTextField txtNumero_Nota_Fiscal;
    private javax.swing.JTextField txtNumero_Remetente;
    private javax.swing.JTextField txtRazao_Social_Emitente;
    private javax.swing.JTextField txtRua_Emitente;
    private javax.swing.JTextField txtRua_Remetente;
    private javax.swing.JTextField txtSerie_Nota_Fiscal;
    private javax.swing.JTextField txtTotal_Desc_Produto;
    private javax.swing.JTextField txtTotal_Produtos;
    private javax.swing.JTextField txtUF_Emitente;
    private javax.swing.JTextField txtUF_Remetente;
    private javax.swing.JTextField txtValor_COFINS;
    private javax.swing.JTextField txtValor_ICMS;
    private javax.swing.JTextField txtValor_IPI;
    private javax.swing.JTextField txtValor_PIS;
    private javax.swing.JTextField txtValor_Total_Nota;
    private javax.swing.JTextField txt_NomeDestinario;
    // End of variables declaration//GEN-END:variables
}
