/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.vendas.view;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import projeto.vendas.control.Conexao;
import projeto.vendas.control.DaoGerarPedido;
import projeto.vendas.control.DaoPFisica;
import projeto.vendas.control.DaoPJuridica;
import projeto.vendas.control.DaoProduto;
import projeto.vendas.model.Login;
import projeto.vendas.model.Pedido;
import projeto.vendas.model.PessoaFisica;
import projeto.vendas.model.PessoaJuridica;

/**
 *
 * @author 0030481621028
 */
public class GuiPedidos_Aprovados extends javax.swing.JFrame {

    /**
     * Creates new form GuiPedidos_Aprovados
     */
    public GuiPedidos_Aprovados(Login login) {
        initComponents();

        this.login = login;
        GuiPedidos_Aprovados.this.setTitle("Pedidos Aprovados    " + "Usuário:  " + login.getNome()
                + "         " + "Codigo:  " + login.getCodigo());
        DefaultTableModel modelo = (DefaultTableModel) tbl_PedidosAprovados.getModel();
        tbl_PedidosAprovados.setRowSorter(new TableRowSorter(modelo));
        
        URL caminhoIcone = getClass().getResource("/projeto/vendas/model/icones/logotipo.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_PedidosAprovados = new javax.swing.JTable();
        btnSelecionar = new javax.swing.JButton();
        btnRetornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tbl_PedidosAprovados.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbl_PedidosAprovados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número do Pedido", "Cliente", "Valor do Pedido", "Pedido Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_PedidosAprovados.setRowHeight(20);
        tbl_PedidosAprovados.setRowMargin(2);
        tbl_PedidosAprovados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_PedidosAprovados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_PedidosAprovadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_PedidosAprovados);

        btnSelecionar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Nota Fiscal.png"))); // NOI18N
        btnSelecionar.setText("Selecione o Pedido E Click Aqui Para Emitir a Nota Fiscal.");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        btnRetornar.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        btnRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/vendas/model/icones/Voltar.png"))); // NOI18N
        btnRetornar.setText("Retornar");
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_PedidosAprovadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_PedidosAprovadosMouseClicked

    }//GEN-LAST:event_tbl_PedidosAprovadosMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao();
        conexao.setDriver();
        conexao.setConnectionString();

        daoGerarPedido = new DaoGerarPedido(conexao.conectar());
        daoPFisica = new DaoPFisica(conexao.conectar());
        daoPJuridica = new DaoPJuridica(conexao.conectar());
        ListaPedidos = daoGerarPedido.ListarPedidos();
        model = (DefaultTableModel) tbl_PedidosAprovados.getModel();

        for (int i = 0; i < ListaPedidos.size(); i++) {
            if (ListaPedidos.get(i).getSituacao() == 1) {
                if (ListaPedidos.get(i).getClienteCod().substring(0, 2).equals("PF")) {
                    pf = daoPFisica.consultar(ListaPedidos.get(i).getClienteCod());
                    Object[] row = {
                        ListaPedidos.get(i).getCodigo(),
                        "(" + ListaPedidos.get(i).getClienteCod() + ")   " + pf.getNome(),
                        formatador.format(ListaPedidos.get(i).getTotal()),
                        "Aprovado"};
                    model.addRow(row);
                } else {
                    pj = daoPJuridica.consultar(ListaPedidos.get(i).getClienteCod());
                    Object[] row = {ListaPedidos.get(i).getCodigo(),
                        "(" + ListaPedidos.get(i).getClienteCod() + ")   " + pj.getNome(),
                        formatador.format(ListaPedidos.get(i).getTotal()),
                        "Aprovado"};
                    System.out.println(pj.getNome());
                    model.addRow(row);
                }
            }

        }
    }//GEN-LAST:event_formWindowOpened

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed

        if (tbl_PedidosAprovados.getSelectedRow() >= 0) {
            GuiEmitir_nota_fiscal NF = new GuiEmitir_nota_fiscal(
                    daoGerarPedido.Consultar(Integer.parseInt(""
                            + tbl_PedidosAprovados.getValueAt(
                                    tbl_PedidosAprovados.getSelectedRow(), 0))), login,GuiPedidos_Aprovados.this.model);
            NF.setVisible(true);
            
            

        }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
        dispose();
    }//GEN-LAST:event_btnRetornarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiPedidos_Aprovados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiPedidos_Aprovados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiPedidos_Aprovados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiPedidos_Aprovados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiPedidos_Aprovados(login).setVisible(true);

            }
        });
    }
    private DecimalFormat formatador = new DecimalFormat("0.00");
    private static Login login = null;
    private DefaultTableModel model;
    private ArrayList<Pedido> ListaPedidos;
    private DaoGerarPedido daoGerarPedido;
    private DaoPFisica daoPFisica;
    private DaoPJuridica daoPJuridica;
    private PessoaFisica pf;
    private PessoaJuridica pj;
    private Conexao conexao;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetornar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_PedidosAprovados;
    // End of variables declaration//GEN-END:variables
}
